# Station Stacking v15 - KATL

Experimental notebook for `KATL`.

V15 is a three-arm weather ablation family. It reruns a fresh v11-current baseline as `v15_base`, then tests `forecast_temp_at_as_of` additions and `precip_cloud` additions in separate output folders under `data/calibration/station_stacking_v15`.

In [1]:
from pathlib import Path
import os
import sys
import warnings

warnings.filterwarnings("ignore", message="IProgress not found.*")
warnings.filterwarnings("ignore", message="Skipping features without any observed values.*")

PROJECT_ROOT = Path.cwd().resolve()
while not (PROJECT_ROOT / "src" / "calibration" / "station_stacking.py").exists():
    if PROJECT_ROOT.parent == PROJECT_ROOT:
        raise RuntimeError("Could not find project root containing src/calibration/station_stacking.py")
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

os.environ["WEATHER_RESEARCH_INCLUDE_DIRECT_NBM"] = "1"

STATION_ID = "KATL"
PROVIDERS = ("gfs", "hrrr", "nbm")
TREND_COLUMNS = [
    "observed_temp_change_last_1h_f",
    "observed_temp_change_last_3h_f",
    "observed_morning_warmup_rate_f_per_hour",
    "observed_high_so_far_change_since_9am_f",
]
TIMING_MODE = "same_day_11am_live_safe"
TARGET_SOURCE = "iem_hourly"
FAST_MODE = False
OPTUNA_TRIALS = 30
STACK_OPTUNA_TRIALS = 30
OPTUNA_STARTUP_TRIALS = 15
STACK_OPTUNA_STARTUP_TRIALS = 15
OPTUNA_METRIC = "mae_f"
OPTUNA_VERBOSE = True
EXPORT_MODEL_WEIGHTS = True
OUTPUT_DIR = PROJECT_ROOT / "data" / "calibration" / "station_stacking_v15"
ARMS = [
    {
        "arm": "base",
        "feature_version": "v15_base",
        "model_version": "station_high_regressor_v15_base_v11_current_stack",
    },
    {
        "arm": "forecast_temp_at_as_of",
        "feature_version": "v15_forecast_temp_at_as_of",
        "model_version": "station_high_regressor_v15_forecast_temp_at_as_of_stack",
    },
    {
        "arm": "precip_cloud",
        "feature_version": "v15_precip_cloud",
        "model_version": "station_high_regressor_v15_precip_cloud_stack",
    },
]

PROJECT_ROOT

WindowsPath('D:/dev/weather-research')

In [2]:
import numpy as np
import pandas as pd

from scripts.run_station_stacking_v15 import write_station_comparisons
from src.export_station_stacking_v2_models import export_station_model_weights
from src.calibration.station_stacking import (
    StationStackingConfig,
    V15_ADDITIONAL_FEATURE_COLUMNS,
    V15_BASE_FEATURE_COLUMNS,
    V15_DROPPED_FEATURE_COLUMNS,
    V15_FORECAST_TEMP_AT_AS_OF_FEATURE_COLUMNS,
    V15_PRECIP_CLOUD_FEATURE_COLUMNS,
    YEAR_SPLIT_EXPANDING_FOLDS,
    missing_model_dependencies,
    provider_availability,
    run_station_year_split_experiment,
)

## V15 Contract

`v15_base` is a fresh v11-current baseline. The added-feature arms always keep the full v11 base, block raw provider weather fields and provider-diff sprawl, and only select their explicit aggregate allowlists after train-year coverage passes.

In [3]:
fold_spec = pd.DataFrame(
    [
        {
            "fold": fold.name,
            "train_start_year": fold.train_start_year,
            "train_end_year": fold.train_end_year,
            "validation_year": fold.validation_year,
        }
        for fold in YEAR_SPLIT_EXPANDING_FOLDS
    ]
)

arm_spec = pd.DataFrame(ARMS)
fold_spec, arm_spec

(                     fold  train_start_year  train_end_year  validation_year
 0  fold_2021_2023_to_2024              2021            2023             2024
 1  fold_2021_2024_to_2025              2021            2024             2025,
                       arm             feature_version  \
 0                    base                    v15_base
 1  forecast_temp_at_as_of  v15_forecast_temp_at_as_of
 2            precip_cloud            v15_precip_cloud

                                        model_version
 0  station_high_regressor_v15_base_v11_current_stack
 1  station_high_regressor_v15_forecast_temp_at_as...
 2      station_high_regressor_v15_precip_cloud_stack  )

In [4]:
{
    "base_columns": V15_BASE_FEATURE_COLUMNS,
    "forecast_temp_at_as_of_additions": V15_FORECAST_TEMP_AT_AS_OF_FEATURE_COLUMNS,
    "precip_cloud_additions": V15_PRECIP_CLOUD_FEATURE_COLUMNS,
    "dropped_columns": sorted(V15_DROPPED_FEATURE_COLUMNS),
}

{'base_columns': ['v2_recent_heat_anomaly_f',
  'v2_recent_heat_momentum_f',
  'v2_morning_warmup_to_consensus_f',
  'v2_consensus_minus_7d_actual_f',
  'v2_spread_per_warmup_f',
  'v2_humidity_warmup_interaction',
  'v3_high_so_far_above_current_f',
  'v3_remaining_warmup_from_high_so_far_f',
  'v3_high_so_far_minus_lag_1d_f',
  'v3_high_so_far_minus_7d_actual_f',
  'v3_remaining_warmup_per_spread_f',
  'v3_humidity_remaining_warmup_interaction',
  'v4_forecast_precip_total_mean_mm',
  'v4_forecast_precip_total_max_mm',
  'v4_forecast_precip_total_spread_mm',
  'v4_forecast_precip_max_1h_mean_mm',
  'v4_forecast_precip_hours_mean',
  'v4_forecast_precip_intensity_mean',
  'v4_forecast_precip_intensity_max',
  'v4_any_forecast_precip',
  'v4_all_forecast_precip',
  'v4_observed_precip_any',
  'v4_observed_precip_recent_mm_est',
  'v4_forecast_total_minus_observed_recent_mm',
  'v4_forecast_observed_precip_match',
  'v4_forecast_wet_observed_dry',
  'v4_observed_wet_forecast_dry',
  'v4_precip_humidity_interaction',
  'v4_precip_remaining_warmup_interaction',
  'observed_temp_change_last_1h_f',
  'observed_temp_change_last_3h_f',
  'observed_morning_warmup_rate_f_per_hour',
  'observed_high_so_far_change_since_9am_f',
  'v8_provider_max_remaining_from_high_so_far_f',
  'v8_provider_min_remaining_from_high_so_far_f',
  'v8_provider_median_remaining_from_high_so_far_f',
  'v8_provider_spread_per_remaining_warmup_f',
  'v8_month_remaining_warmup_mean_f',
  'v8_month_remaining_warmup_count',
  'v8_recent_remaining_warmup_7d_mean_f',
  'v8_recent_remaining_warmup_30d_mean_f',
  'v8_provider_mean_remaining_vs_month_normal_f',
  'v8_cloud_cover_mean_remaining_warmup_interaction',
  'v8_cloud_cover_max_remaining_warmup_interaction',
  'v8_precip_total_remaining_warmup_interaction',
  'v8_precip_max_1h_remaining_warmup_interaction',
  'v8_wind_speed_mean_remaining_warmup_interaction',
  'v8_wind_gust_max_remaining_warmup_interaction',
  'v8_forecast_dewpoint_mean_f',
  'v8_forecast_dewpoint_depression_mean_f',
  'v8_dewpoint_mean_remaining_warmup_interaction',
  'v8_dewpoint_depression_remaining_warmup_interaction',
  'climatology_high_10y_f',
  'climatology_high_10y_std_f',
  'climatology_high_10y_count',
  'provider_mean_minus_climatology_10y_f',
  'observed_temp_minus_climatology_10y_f',
  'observed_high_so_far_minus_climatology_10y_f'],
 'forecast_temp_at_as_of_additions': ['v13_forecast_temp_at_as_of_mean_f',
  'v13_forecast_temp_at_as_of_minus_observed_mean_f',
  'v13_forecast_temp_at_as_of_spread_f',
  'v13_forecast_temp_bias_remaining_warmup_interaction'],
 'precip_cloud_additions': ['v13_cloud_cover_mean_pct',
  'v13_cloud_cover_max_pct',
  'v13_cloud_cover_remaining_warmup_interaction',
  'v13_precip_cloud_remaining_warmup_interaction'],
 'dropped_columns': ['actual_minus_climatology_10y_f_DIAGNOSTIC_ONLY',
  'climatology_source_end_year',
  'climatology_source_start_year',
  'gfs_as_of_hour_local',
  'gfs_available',
  'gfs_forecast_window_hours',
  'gfs_grid_dist_km_mean',
  'gfs_horizon_hours',
  'gfs_hrrr_grid_dist_km_mean_abs_diff_f',
  'gfs_hrrr_grid_dist_km_mean_diff_f',
  'gfs_issue_hour_utc',
  'gfs_missing',
  'hrrr_as_of_hour_local',
  'hrrr_available',
  'hrrr_forecast_hour_max',
  'hrrr_forecast_hour_min',
  'hrrr_forecast_lead_hours',
  'hrrr_forecast_window_hours',
  'hrrr_grid_dist_km_mean',
  'hrrr_horizon_hours',
  'hrrr_issue_hour_local',
  'hrrr_issue_hour_utc',
  'hrrr_missing',
  'is_active_polymarket_station',
  'lat',
  'lon',
  'nbm_as_of_hour_local',
  'nbm_available',
  'nbm_forecast_window_hours',
  'nbm_horizon_hours',
  'nbm_issue_hour_local',
  'nbm_issue_hour_utc',
  'nbm_missing',
  'observed_fetch_status',
  'observed_observation_type',
  'observed_pressure_source',
  'provider_count_available',
  'year']}

## Data Availability

In [5]:
availability = provider_availability(
    PROJECT_ROOT,
    timing_mode=TIMING_MODE,
    providers=PROVIDERS,
)

availability.loc[availability["station_id"].eq(STATION_ID)]

  station_id provider  row_count first_contract_date last_contract_date
0       KATL      gfs       1998          2021-01-01         2026-06-21
1       KATL     hrrr       1998          2021-01-01         2026-06-21
2       KATL      nbm       1997          2021-01-01         2026-06-21

## Run Three Arms

In [6]:
missing_packages = missing_model_dependencies()
if missing_packages:
    raise ImportError(
        "Missing station-stacking ML packages: "
        + ", ".join(missing_packages)
        + ". Install them with: python -m pip install -r requirements.txt"
    )

results = {}
for arm in ARMS:
    arm_dir = OUTPUT_DIR / arm["arm"]
    config = StationStackingConfig(
        station_id=STATION_ID,
        project_root=PROJECT_ROOT,
        timing_mode=TIMING_MODE,
        providers=PROVIDERS,
        fast_mode=FAST_MODE,
        optuna_trials=OPTUNA_TRIALS,
        stack_optuna_trials=STACK_OPTUNA_TRIALS,
        optuna_startup_trials=OPTUNA_STARTUP_TRIALS,
        stack_optuna_startup_trials=STACK_OPTUNA_STARTUP_TRIALS,
        optuna_metric=OPTUNA_METRIC,
        optuna_verbose=OPTUNA_VERBOSE,
        feature_version=arm["feature_version"],
        target_mode="remaining_warmup",
        target_source=TARGET_SOURCE,
        base_model_methods=("xgboost", "lightgbm", "catboost"),
        stack_enabled=True,
        hyperparameter_space="wide",
        year_split_folds=YEAR_SPLIT_EXPANDING_FOLDS,
        year_split_test_train_years=(2021, 2025),
        year_split_test_year=2026,
        output_dir=arm_dir,
        climatology_normals_path=PROJECT_ROOT / "data" / "calibration" / "station_stacking_v9" / "station_rolling_10y_daily_high_normals.csv",
    )
    print(f"Running {STATION_ID} {arm['arm']}: {config.resolved_optuna_storage_uri()}")
    result = run_station_year_split_experiment(config)
    results[arm["arm"]] = result
    display(result.scoreboard.assign(arm=arm["arm"], feature_version=arm["feature_version"]))
    if EXPORT_MODEL_WEIGHTS:
        exported_weights = export_station_model_weights(
            project_root=PROJECT_ROOT,
            station_id=STATION_ID,
            artifact_dir=config.resolved_output_dir(),
            model_version=arm["model_version"],
            timing_mode=config.timing_mode,
            providers=tuple(config.providers),
            feature_version=config.effective_feature_version,
            optuna_metric=config.effective_optuna_metric,
            target_mode=config.effective_target_mode,
            target_source=config.effective_target_source,
            base_model_methods=tuple(config.effective_base_model_methods),
            stack_enabled=config.stack_enabled,
            source_pipeline="notebooks/station_stacking_v15",
        )
        print(f"Exported {arm['arm']}: {exported_weights.bundle_path}")

write_station_comparisons(OUTPUT_DIR, STATION_ID, [arm["arm"] for arm in ARMS])

Running KATL base: sqlite:///D:/dev/weather-research/data/calibration/station_stacking_v15/base/KATL_optuna.sqlite3

[I 2026-06-29 15:32:16,796] A new study created in RDB with name: KATL_v15_base_remaining_warmup_base_xgboost_mae_f
[I 2026-06-29 15:32:27,133] Trial 0 finished with value: 11.672274447074303 and parameters: {'n_estimators': 1342, 'learning_rate': 0.19043899115982607, 'max_depth': 9, 'min_child_weight': 2.481040974867813, 'gamma': 2.340279606636548, 'subsample': 0.4513964382185317, 'colsample_bytree': 0.3877543479093296, 'reg_alpha': 2.478071022662141, 'reg_lambda': 0.6132587025321562}. Best is trial 0 with value: 11.672274447074303.
[I 2026-06-29 15:32:28,000] Trial 1 finished with value: 11.672274447074303 and parameters: {'n_estimators': 2493, 'learning_rate': 0.001120367191095075, 'max_depth': 12, 'min_child_weight': 21.368329072358772, 'gamma': 3.185086660174142, 'subsample': 0.4681862286846154, 'colsample_bytree': 0.46921293140473197, 'reg_alpha': 4.476173538513514e-07, 'reg_lambda': 0.20253776634919213}. Best is trial 0 with value: 11.672274447074303.
[I 2026-06-29 15:32:44,957] Trial 2 finished with value: 2.3361405294267152 and parameters: {'n_estimators': 1540, 'learning_rate': 0.004992867109217114, 'max_depth': 8, 'min_child_weight': 0.03613894271216528, 'gamma': 4.3821697280282725, 'subsample': 0.5881351981408995, 'colsample_bytree': 0.6464454897410734, 'reg_alpha': 0.26430874752361627, 'reg_lambda': 0.0018119678627933364}. Best is trial 2 with value: 2.3361405294267152.
[I 2026-06-29 15:32:50,175] Trial 3 finished with value: 5.067074908604988 and parameters: {'n_estimators': 1824, 'learning_rate': 0.026337502897485255, 'max_depth': 1, 'min_child_weight': 2.69264691008618, 'gamma': 2.557861855309373, 'subsample': 0.39228353544043165, 'colsample_bytree': 0.9667755992146666, 'reg_alpha': 38.6887231523051, 'reg_lambda': 12.408975837016275}. Best is trial 2 with value: 2.3361405294267152.
[I 2026-06-29 15:33:12,893] Trial 4 finished with value: 1.8322454076348755 and parameters: {'n_estimators': 1101, 'learning_rate': 0.0017147936629846843, 'max_depth': 9, 'min_child_weight': 0.5762487216478605, 'gamma': 1.8305735226716824, 'subsample': 0.6718649915723256, 'colsample_bytree': 0.37235253872489193, 'reg_alpha': 8.162906555194692, 'reg_lambda': 0.004271500153828077}. Best is trial 4 with value: 1.8322454076348755.
[I 2026-06-29 15:33:44,098] Trial 5 finished with value: 1.9404760221537651 and parameters: {'n_estimators': 2336, 'learning_rate': 0.00559067775661512, 'max_depth': 7, 'min_child_weight': 1.5375920235481764, 'gamma': 2.7728168328829055, 'subsample': 0.980230008046963, 'colsample_bytree': 0.8538363351847245, 'reg_alpha': 18.792618557420877, 'reg_lambda': 43.484449457612314}. Best is trial 4 with value: 1.8322454076348755.
[I 2026-06-29 15:33:46,538] Trial 6 finished with value: 1.7641160305616455 and parameters: {'n_estimators': 2113, 'learning_rate': 0.16240489353272883, 'max_depth': 2, 'min_child_weight': 0.06080390190296603, 'gamma': 0.678409333658071, 'subsample': 0.5614647149961218, 'colsample_bytree': 0.6026402382981633, 'reg_alpha': 1.8037999945880162e-07, 'reg_lambda': 16.668629892722056}. Best is trial 6 with value: 1.7641160305616455.
[I 2026-06-29 15:33:57,892] Trial 7 finished with value: 2.0240148185658584 and parameters: {'n_estimators': 1281, 'learning_rate': 0.0047169807141865345, 'max_depth': 7, 'min_child_weight': 0.0366181922039243, 'gamma': 12.032954711310595, 'subsample': 0.398457918391851, 'colsample_bytree': 0.9914765087903362, 'reg_alpha': 0.18490013641000916, 'reg_lambda': 0.0017869543989965139}. Best is trial 6 with value: 1.7641160305616455.
[I 2026-06-29 15:33:58,861] Trial 8 pruned.
[I 2026-06-29 15:34:16,959] Trial 9 finished with value: 1.8124153960932576 and parameters: {'n_estimators': 2201, 'learning_rate': 0.006215464818952927, 'max_depth': 1, 'min_child_weight': 0.17535949529764422, 'gamma': 4.877749830401205, 'subsample': 0.8242440159197416, 'colsample_bytree': 0.7644123563808884, 'reg_alpha': 4.4315220126915325, 'reg_lambda': 0.09450187118503514}. Best is trial 6 with value: 1.7641160305616455.
[I 2026-06-29 15:34:21,126] Trial 10 finished with value: 1.8205475554564496 and parameters: {'n_estimators': 462, 'learning_rate': 0.051323729958866915, 'max_depth': 10, 'min_child_weight': 1.7583640270008525, 'gamma': 11.564507699318415, 'subsample': 0.670967137636854, 'colsample_bytree': 0.689776339098296, 'reg_alpha': 1.3504926357029513e-05, 'reg_lambda': 0.0001445994629863374}. Best is trial 6 with value: 1.7641160305616455.
[I 2026-06-29 15:34:29,146] Trial 11 pruned.
[I 2026-06-29 15:34:38,629] Trial 12 pruned.
[I 2026-06-29 15:34:39,448] Trial 13 pruned.
[I 2026-06-29 15:34:43,306] Trial 14 finished with value: 1.6755133808811942 and parameters: {'n_estimators': 2872, 'learning_rate': 0.11587248002108354, 'max_depth': 1, 'min_child_weight': 1.1040511903162256, 'gamma': 6.261165047231685, 'subsample': 0.49437007680597467, 'colsample_bytree': 0.4279124887668938, 'reg_alpha': 1.125594744942969e-06, 'reg_lambda': 87.35792858155622}. Best is trial 14 with value: 1.6755133808811942.
[I 2026-06-29 15:34:55,130] Trial 15 finished with value: 1.6798010179799991 and parameters: {'n_estimators': 3311, 'learning_rate': 0.04016687409111762, 'max_depth': 3, 'min_child_weight': 0.012905294825774771, 'gamma': 0.18586716971939637, 'subsample': 0.5599207159834859, 'colsample_bytree': 0.5396163811224401, 'reg_alpha': 0.0016913438352762248, 'reg_lambda': 131.8838700608262}. Best is trial 14 with value: 1.6755133808811942.
[I 2026-06-29 15:35:05,206] Trial 16 finished with value: 1.7168157902563008 and parameters: {'n_estimators': 3332, 'learning_rate': 0.031184182180475774, 'max_depth': 4, 'min_child_weight': 0.016581267455563507, 'gamma': 7.515853622869325, 'subsample': 0.7245159430745359, 'colsample_bytree': 0.5157551306129865, 'reg_alpha': 0.0014033169134723444, 'reg_lambda': 196.90312078844747}. Best is trial 14 with value: 1.6755133808811942.
[I 2026-06-29 15:35:05,949] Trial 17 pruned.
[I 2026-06-29 15:35:10,432] Trial 18 finished with value: 1.7774970377581911 and parameters: {'n_estimators': 2997, 'learning_rate': 0.06814715014496904, 'max_depth': 3, 'min_child_weight': 0.010327326155251955, 'gamma': 0.0581612490241426, 'subsample': 0.6436595254227655, 'colsample_bytree': 0.4835616552159919, 'reg_alpha': 0.0006283660835071119, 'reg_lambda': 1.771610430301136}. Best is trial 14 with value: 1.6755133808811942.
[I 2026-06-29 15:35:26,447] Trial 19 finished with value: 1.759816714827176 and parameters: {'n_estimators': 2824, 'learning_rate': 0.013346525112419762, 'max_depth': 5, 'min_child_weight': 0.31119554628630514, 'gamma': 9.466265153084475, 'subsample': 0.7732981551774945, 'colsample_bytree': 0.41532599251824875, 'reg_alpha': 1.7788279338939752e-05, 'reg_lambda': 81.31666476185187}. Best is trial 14 with value: 1.6755133808811942.
[I 2026-06-29 15:35:27,497] Trial 20 pruned.
[I 2026-06-29 15:35:39,420] Trial 21 finished with value: 1.7149958481506986 and parameters: {'n_estimators': 3447, 'learning_rate': 0.03916140896952858, 'max_depth': 5, 'min_child_weight': 0.010449145943170366, 'gamma': 8.550793137940051, 'subsample': 0.7250169630282906, 'colsample_bytree': 0.5513055068158655, 'reg_alpha': 0.0025683362367070607, 'reg_lambda': 141.8277587151405}. Best is trial 14 with value: 1.6755133808811942.
[I 2026-06-29 15:35:46,941] Trial 22 finished with value: 1.735155744867665 and parameters: {'n_estimators': 3084, 'learning_rate': 0.04273494762230192, 'max_depth': 5, 'min_child_weight': 0.02362527914856348, 'gamma': 9.397183703274244, 'subsample': 0.6334648918219821, 'colsample_bytree': 0.4449727896122752, 'reg_alpha': 0.021146220343302196, 'reg_lambda': 65.72603515229355}. Best is trial 14 with value: 1.6755133808811942.
[I 2026-06-29 15:35:53,004] Trial 23 finished with value: 1.7386939919918447 and parameters: {'n_estimators': 3497, 'learning_rate': 0.09441657839713452, 'max_depth': 2, 'min_child_weight': 0.09450223318179701, 'gamma': 9.062378242517987, 'subsample': 0.7344864861472217, 'colsample_bytree': 0.5658125392140065, 'reg_alpha': 0.00012958566064298402, 'reg_lambda': 168.5934589640333}. Best is trial 14 with value: 1.6755133808811942.
[I 2026-06-29 15:36:08,123] Trial 24 finished with value: 1.716807942428759 and parameters: {'n_estimators': 3138, 'learning_rate': 0.0163932562429943, 'max_depth': 5, 'min_child_weight': 0.01488687007769982, 'gamma': 6.153306338839648, 'subsample': 0.5157285374561327, 'colsample_bytree': 0.6709215419940603, 'reg_alpha': 0.01907313766080597, 'reg_lambda': 38.296228974946416}. Best is trial 14 with value: 1.6755133808811942.
[I 2026-06-29 15:36:11,258] Trial 25 finished with value: 1.781880312028822 and parameters: {'n_estimators': 2748, 'learning_rate': 0.10216843928512775, 'max_depth': 3, 'min_child_weight': 0.09815489128375238, 'gamma': 8.836838954472661, 'subsample': 0.608472910494863, 'colsample_bytree': 0.5468799786515672, 'reg_alpha': 2.2383438095477743e-06, 'reg_lambda': 4.995437841186387}. Best is trial 14 with value: 1.6755133808811942.
[I 2026-06-29 15:36:12,110] Trial 26 pruned.
[I 2026-06-29 15:36:13,085] Trial 27 pruned.
[I 2026-06-29 15:36:16,463] Trial 28 finished with value: 1.67294956413419 and parameters: {'n_estimators': 3240, 'learning_rate': 0.06186873618352931, 'max_depth': 1, 'min_child_weight': 0.6885538684802076, 'gamma': 6.1559548006996545, 'subsample': 0.711990514904785, 'colsample_bytree': 0.6208601456469387, 'reg_alpha': 0.012157229243070711, 'reg_lambda': 26.034708508305215}. Best is trial 28 with value: 1.67294956413419.
[I 2026-06-29 15:36:26,750] Trial 29 finished with value: 1.70560969247845 and parameters: {'n_estimators': 3226, 'learning_rate': 0.009833635177558935, 'max_depth': 1, 'min_child_weight': 0.5916935711353914, 'gamma': 6.330238034428585, 'subsample': 0.5189245066032977, 'colsample_bytree': 0.7445690911290416, 'reg_alpha': 0.1538289338474157, 'reg_lambda': 0.7080580847714997}. Best is trial 28 with value: 1.67294956413419.
[I 2026-06-29 15:36:26,987] A new study created in RDB with name: KATL_v15_base_remaining_warmup_base_lightgbm_mae_f
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:36:30,101] Trial 0 finished with value: 1.7660353889990161 and parameters: {'n_estimators': 447, 'learning_rate': 0.028873871707375695, 'num_leaves': 71, 'max_depth': 5, 'min_child_samples': 83, 'min_split_gain': 4.295687454742988, 'bagging_fraction': 0.7829586385137167, 'bagging_freq': 4, 'feature_fraction': 0.3688589858758342, 'lambda_l1': 0.06382334403151436, 'lambda_l2': 0.03080292177315921, 'huber_alpha': 0.95}. Best is trial 0 with value: 1.7660353889990161.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:36:36,049] Trial 1 finished with value: 1.9938144717463873 and parameters: {'n_estimators': 812, 'learning_rate': 0.009357081249483435, 'num_leaves': 164, 'max_depth': 2, 'min_child_samples': 211, 'min_split_gain': 4.244695738724308, 'bagging_fraction': 0.9814523094330022, 'bagging_freq': 3, 'feature_fraction': 0.9704172813206324, 'lambda_l1': 2.234088279028776e-05, 'lambda_l2': 1.6594154120142632, 'huber_alpha': 0.85}. Best is trial 0 with value: 1.7660353889990161.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:36:37,619] Trial 2 finished with value: 2.700952963201425 and parameters: {'n_estimators': 67, 'learning_rate': 0.02007090910723469, 'num_leaves': 246, 'max_depth': 10, 'min_child_samples': 245, 'min_split_gain': 4.543313789155439, 'bagging_fraction': 0.9415994992571017, 'bagging_freq': 4, 'feature_fraction': 0.41761231740559585, 'lambda_l1': 1.4824332354449863e-08, 'lambda_l2': 101.18939970488272, 'huber_alpha': 0.85}. Best is trial 0 with value: 1.7660353889990161.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:36:42,653] Trial 3 finished with value: 1.900132971764737 and parameters: {'n_estimators': 1000, 'learning_rate': 0.1413663860910666, 'num_leaves': 109, 'max_depth': 7, 'min_child_samples': 249, 'min_split_gain': 3.678635407535604, 'bagging_fraction': 0.6392899181182937, 'bagging_freq': 4, 'feature_fraction': 0.6173160679063129, 'lambda_l1': 0.052948773379180566, 'lambda_l2': 0.032760577756785814, 'huber_alpha': 0.85}. Best is trial 0 with value: 1.7660353889990161.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:36:47,155] Trial 4 finished with value: 2.497525231412947 and parameters: {'n_estimators': 761, 'learning_rate': 0.003003151716938294, 'num_leaves': 409, 'max_depth': 5, 'min_child_samples': 165, 'min_split_gain': 1.498083879035124, 'bagging_fraction': 0.44391094597483866, 'bagging_freq': 3, 'feature_fraction': 0.5516751924489833, 'lambda_l1': 8.332516750396116e-08, 'lambda_l2': 0.5077631895453656, 'huber_alpha': 0.85}. Best is trial 0 with value: 1.7660353889990161.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:36:49,354] Trial 5 finished with value: 1.7161647704444198 and parameters: {'n_estimators': 404, 'learning_rate': 0.18314620854695027, 'num_leaves': 260, 'max_depth': 13, 'min_child_samples': 51, 'min_split_gain': 2.972245934092154, 'bagging_fraction': 0.9775155780902212, 'bagging_freq': 7, 'feature_fraction': 0.365709606237354, 'lambda_l1': 5.9654059281874116e-05, 'lambda_l2': 0.006859036422781172, 'huber_alpha': 0.95}. Best is trial 5 with value: 1.7161647704444198.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:36:52,704] Trial 6 finished with value: 1.7194729136942013 and parameters: {'n_estimators': 3052, 'learning_rate': 0.13146898336096702, 'num_leaves': 489, 'max_depth': 11, 'min_child_samples': 47, 'min_split_gain': 2.173391605434026, 'bagging_fraction': 0.9258346721061177, 'bagging_freq': 2, 'feature_fraction': 0.6381532515738396, 'lambda_l1': 0.002530717742378322, 'lambda_l2': 0.0004479476588817844, 'huber_alpha': 0.95}. Best is trial 5 with value: 1.7161647704444198.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:36:54,937] Trial 7 finished with value: 1.8009128195506259 and parameters: {'n_estimators': 2519, 'learning_rate': 0.18104669093362824, 'num_leaves': 399, 'max_depth': 4, 'min_child_samples': 227, 'min_split_gain': 2.761320735057018, 'bagging_fraction': 0.8991836269249566, 'bagging_freq': 7, 'feature_fraction': 0.8888248313104422, 'lambda_l1': 5.374969144858311e-06, 'lambda_l2': 0.5877618471031133, 'huber_alpha': 0.85}. Best is trial 5 with value: 1.7161647704444198.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:37:20,890] Trial 8 finished with value: 1.9278565759077713 and parameters: {'n_estimators': 2273, 'learning_rate': 0.0030965152683643635, 'num_leaves': 383, 'max_depth': 3, 'min_child_samples': 3, 'min_split_gain': 1.6724449577646616, 'bagging_fraction': 0.9800160774901863, 'bagging_freq': 5, 'feature_fraction': 0.6188955975766686, 'lambda_l1': 2.8120694751804143e-09, 'lambda_l2': 0.00024007807690373727, 'huber_alpha': 0.85}. Best is trial 5 with value: 1.7161647704444198.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:37:24,101] Trial 9 pruned.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:37:37,486] Trial 10 finished with value: 1.8118373981572962 and parameters: {'n_estimators': 2941, 'learning_rate': 0.007104579859769969, 'num_leaves': 424, 'max_depth': 2, 'min_child_samples': 2, 'min_split_gain': 4.6220887565718325, 'bagging_fraction': 0.7880566131549542, 'bagging_freq': 7, 'feature_fraction': 0.661678263936434, 'lambda_l1': 8.121756387194875e-09, 'lambda_l2': 100.08386764870838, 'huber_alpha': 0.9}. Best is trial 5 with value: 1.7161647704444198.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-06-29 15:37:38,968] Trial 11 pruned.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

,period,method,count,mae_f,rmse_f,arm,feature_version
0,validation_2024_2025,xgboost,728,1.671761,2.384807,base,v15_base
1,validation_2024_2025,lightgbm,728,1.672786,2.417305,base,v15_base
2,validation_2024_2025,catboost,728,1.682298,2.423920,base,v15_base
3,validation_2024_2025,provider_mean,728,2.832206,4.006255,base,v15_base
4,validation_2024_2025,provider_median,728,2.782240,3.911262,base,v15_base
5,validation_2024_2025,nbm_raw,728,2.792647,3.816647,base,v15_base
6,validation_2024_2025,hrrr_raw,728,3.556181,4.953880,base,v15_base
7,validation_2024_2025,gfs_raw,728,3.254687,4.459385,base,v15_base
8,test_2026,xgboost,170,1.631589,2.319565,base,v15_base
9,test_2026,lightgbm,170,1.558784,2.223175,base,v15_base
10,test_2026,catboost,170,1.582195,2.211646,base,v15_base
11,test_2026,ridge_stack,170,1.565049,2.212661,base,v15_base
12,test_2026,provider_mean,170,2.786086,4.048184,base,v15_base
13,test_2026,provider_median,170,2.723802,3.926838,base,v15_base
14,test_2026,nbm_raw,170,2.614555,3.750025,base,v15_base
15,test_2026,hrrr_raw,170,3.216669,4.676677,base,v15_base
16,test_2026,gfs_raw,170,3.328938,4.532080,base,v15_base

Exported base: D:\dev\weather-research\data\calibration\station_stacking_v15\base\model_weights\KATL_station_high_regressor_v15_base_v11_current_stack.joblib
Running KATL forecast_temp_at_as_of: sqlite:///D:/dev/weather-research/data/calibration/station_stacking_v15/forecast_temp_at_as_of/KATL_optuna.sqlite3

D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
[I 2026-06-29 16:46:50,284] A new study created in RDB with name: KATL_v15_forecast_temp_at_as_of_remaining_warmup_base_xgboost_mae_f
[I 2026-06-29 16:46:51,015] Trial 0 finished with value: 11.672274447074303 and parameters: {'n_estimators': 1342, 'learning_rate': 0.19043899115982607, 'max_depth': 9, 'min_child_weight': 2.481040974867813, 'gamma': 2.340279606636548, 'subsample': 0.4513964382185317, 'colsample_bytree': 0.3877543479093296, 'reg_alpha': 2.478071022662141, 'reg_lambda': 0.6132587025321562}. Best is trial 0 with value: 11.672274447074303.
[I 2026-06-29 16:46:51,673] Trial 1 finished with value: 11.672274447074303 and parameters: {'n_estimators': 2493, 'learning_rate': 0.001120367191095075, 'max_depth': 12, 'min_child_weight': 21.368329072358772, 'gamma': 3.185086660174142, 'subsample': 0.4681862286846154, 'colsample_bytree': 0.46921293140473197, 'reg_alpha': 4.476173538513514e-07, 'reg_lambda': 0.20253776634919213}. Best is trial 0 with value: 11.672274447074303.
[I 2026-06-29 16:46:59,581] Trial 2 finished with value: 2.310849867882171 and parameters: {'n_estimators': 1540, 'learning_rate': 0.004992867109217114, 'max_depth': 8, 'min_child_weight': 0.03613894271216528, 'gamma': 4.3821697280282725, 'subsample': 0.5881351981408995, 'colsample_bytree': 0.6464454897410734, 'reg_alpha': 0.26430874752361627, 'reg_lambda': 0.0018119678627933364}. Best is trial 2 with value: 2.310849867882171.
[I 2026-06-29 16:47:02,455] Trial 3 finished with value: 5.085208122295337 and parameters: {'n_estimators': 1824, 'learning_rate': 0.026337502897485255, 'max_depth': 1, 'min_child_weight': 2.69264691008618, 'gamma': 2.557861855309373, 'subsample': 0.39228353544043165, 'colsample_bytree': 0.9667755992146666, 'reg_alpha': 38.6887231523051, 'reg_lambda': 12.408975837016275}. Best is trial 2 with value: 2.310849867882171.
[I 2026-06-29 16:47:18,260] Trial 4 finished with value: 1.904651807938631 and parameters: {'n_estimators': 1101, 'learning_rate': 0.0017147936629846843, 'max_depth': 9, 'min_child_weight': 0.5762487216478605, 'gamma': 1.8305735226716824, 'subsample': 0.6718649915723256, 'colsample_bytree': 0.37235253872489193, 'reg_alpha': 8.162906555194692, 'reg_lambda': 0.004271500153828077}. Best is trial 4 with value: 1.904651807938631.
[I 2026-06-29 16:47:40,536] Trial 5 finished with value: 2.0154403114718393 and parameters: {'n_estimators': 2336, 'learning_rate': 0.00559067775661512, 'max_depth': 7, 'min_child_weight': 1.5375920235481764, 'gamma': 2.7728168328829055, 'subsample': 0.980230008046963, 'colsample_bytree': 0.8538363351847245, 'reg_alpha': 18.792618557420877, 'reg_lambda': 43.484449457612314}. Best is trial 4 with value: 1.904651807938631.
[I 2026-06-29 16:47:42,086] Trial 6 finished with value: 1.7882367668557133 and parameters: {'n_estimators': 2113, 'learning_rate': 0.16240489353272883, 'max_depth': 2, 'min_child_weight': 0.06080390190296603, 'gamma': 0.678409333658071, 'subsample': 0.5614647149961218, 'colsample_bytree': 0.6026402382981633, 'reg_alpha': 1.8037999945880162e-07, 'reg_lambda': 16.668629892722056}. Best is trial 6 with value: 1.7882367668557133.
[I 2026-06-29 16:47:48,528] Trial 7 finished with value: 1.9926143724469692 and parameters: {'n_estimators': 1281, 'learning_rate': 0.0047169807141865345, 'max_depth': 7, 'min_child_weight': 0.0366181922039243, 'gamma': 12.032954711310595, 'subsample': 0.398457918391851, 'colsample_bytree': 0.9914765087903362, 'reg_alpha': 0.18490013641000916, 'reg_lambda': 0.0017869543989965139}. Best is trial 6 with value: 1.7882367668557133.
[I 2026-06-29 16:47:48,935] Trial 8 pruned.
[I 2026-06-29 16:47:57,374] Trial 9 finished with value: 1.7674052295813767 and parameters: {'n_estimators': 2201, 'learning_rate': 0.006215464818952927, 'max_depth': 1, 'min_child_weight': 0.17535949529764422, 'gamma': 4.877749830401205, 'subsample': 0.8242440159197416, 'colsample_bytree': 0.7644123563808884, 'reg_alpha': 4.4315220126915325, 'reg_lambda': 0.09450187118503514}. Best is trial 9 with value: 1.7674052295813767.
[I 2026-06-29 16:47:59,497] Trial 10 finished with value: 1.7268994427118654 and parameters: {'n_estimators': 462, 'learning_rate': 0.051323729958866915, 'max_depth': 10, 'min_child_weight': 1.7583640270008525, 'gamma': 11.564507699318415, 'subsample': 0.670967137636854, 'colsample_bytree': 0.689776339098296, 'reg_alpha': 1.3504926357029513e-05, 'reg_lambda': 0.0001445994629863374}. Best is trial 10 with value: 1.7268994427118654.
[I 2026-06-29 16:48:03,662] Trial 11 pruned.
[I 2026-06-29 16:48:08,254] Trial 12 pruned.
[I 2026-06-29 16:48:08,708] Trial 13 pruned.
[I 2026-06-29 16:48:10,786] Trial 14 finished with value: 1.6497750143271226 and parameters: {'n_estimators': 2872, 'learning_rate': 0.11587248002108354, 'max_depth': 1, 'min_child_weight': 1.1040511903162256, 'gamma': 6.261165047231685, 'subsample': 0.49437007680597467, 'colsample_bytree': 0.4279124887668938, 'reg_alpha': 1.125594744942969e-06, 'reg_lambda': 87.35792858155622}. Best is trial 14 with value: 1.6497750143271226.
[I 2026-06-29 16:48:11,253] Trial 15 pruned.
[I 2026-06-29 16:48:19,909] Trial 16 finished with value: 1.7119846046468714 and parameters: {'n_estimators': 3479, 'learning_rate': 0.028016885502806663, 'max_depth': 4, 'min_child_weight': 0.706933147248181, 'gamma': 8.034363960532348, 'subsample': 0.6852013564142475, 'colsample_bytree': 0.8609486010609017, 'reg_alpha': 0.0007576903076688526, 'reg_lambda': 192.3597475874131}. Best is trial 14 with value: 1.6497750143271226.
[I 2026-06-29 16:48:32,504] Trial 17 finished with value: 1.7273979639456822 and parameters: {'n_estimators': 3386, 'learning_rate': 0.017478919982976338, 'max_depth': 4, 'min_child_weight': 0.3214881455566735, 'gamma': 7.806461488018035, 'subsample': 0.7742427801462375, 'colsample_bytree': 0.8661546133566599, 'reg_alpha': 0.001687062589158873, 'reg_lambda': 185.86435125807805}. Best is trial 14 with value: 1.6497750143271226.
[I 2026-06-29 16:48:45,179] Trial 18 finished with value: 1.7034684529186603 and parameters: {'n_estimators': 2997, 'learning_rate': 0.015791722592673082, 'max_depth': 4, 'min_child_weight': 0.011780433865938213, 'gamma': 6.161201127152203, 'subsample': 0.6346834519624751, 'colsample_bytree': 0.5070107064372208, 'reg_alpha': 0.0013743717543530719, 'reg_lambda': 196.99396706244949}. Best is trial 14 with value: 1.6497750143271226.
[I 2026-06-29 16:48:48,419] Trial 19 finished with value: 1.7868892249184976 and parameters: {'n_estimators': 2669, 'learning_rate': 0.018497034721529807, 'max_depth': 3, 'min_child_weight': 0.010296849889118127, 'gamma': 5.852464919151721, 'subsample': 0.5028989980253645, 'colsample_bytree': 0.5280533431996949, 'reg_alpha': 0.0035849619178030135, 'reg_lambda': 1.7833927853251788}. Best is trial 14 with value: 1.6497750143271226.
[I 2026-06-29 16:48:51,232] Trial 20 finished with value: 1.7271101592012812 and parameters: {'n_estimators': 2933, 'learning_rate': 0.07696378995171024, 'max_depth': 5, 'min_child_weight': 0.011065136021091005, 'gamma': 9.606417877149363, 'subsample': 0.5957363687872026, 'colsample_bytree': 0.4576177435670168, 'reg_alpha': 1.3860957336777205e-10, 'reg_lambda': 69.33716494315624}. Best is trial 14 with value: 1.6497750143271226.
[I 2026-06-29 16:49:04,762] Trial 21 finished with value: 1.67690975019303 and parameters: {'n_estimators': 3003, 'learning_rate': 0.011290144738310288, 'max_depth': 3, 'min_child_weight': 0.6177562735490055, 'gamma': 6.22223527583044, 'subsample': 0.664267704662667, 'colsample_bytree': 0.35213458982427814, 'reg_alpha': 0.002778975589806964, 'reg_lambda': 141.8335228775532}. Best is trial 14 with value: 1.6497750143271226.
[I 2026-06-29 16:49:05,219] Trial 22 pruned.
[I 2026-06-29 16:49:19,190] Trial 23 finished with value: 1.7350049074213583 and parameters: {'n_estimators': 2941, 'learning_rate': 0.009732378559304361, 'max_depth': 5, 'min_child_weight': 0.10572029504346026, 'gamma': 6.506291661374973, 'subsample': 0.517674882691492, 'colsample_bytree': 0.5151041567684629, 'reg_alpha': 0.00011928578986866198, 'reg_lambda': 68.11464905377743}. Best is trial 14 with value: 1.6497750143271226.
[I 2026-06-29 16:49:27,575] Trial 24 pruned.
[I 2026-06-29 16:49:40,551] Trial 25 finished with value: 1.7580172163614862 and parameters: {'n_estimators': 2586, 'learning_rate': 0.0027242782713190637, 'max_depth': 2, 'min_child_weight': 1.041553291173818, 'gamma': 4.653298432747779, 'subsample': 0.6222745196846924, 'colsample_bytree': 0.5576455305268746, 'reg_alpha': 0.021487848111851553, 'reg_lambda': 47.48623956660302}. Best is trial 14 with value: 1.6497750143271226.
[I 2026-06-29 16:49:41,050] Trial 26 pruned.
[I 2026-06-29 16:49:41,520] Trial 27 pruned.
[I 2026-06-29 16:49:47,087] Trial 28 finished with value: 1.6803844866359625 and parameters: {'n_estimators': 2016, 'learning_rate': 0.014846093213696144, 'max_depth': 1, 'min_child_weight': 0.019785836862237994, 'gamma': 9.31171592598625, 'subsample': 0.44416164747113757, 'colsample_bytree': 0.41309097992952454, 'reg_alpha': 0.014824332383661536, 'reg_lambda': 26.034708508305215}. Best is trial 14 with value: 1.6497750143271226.
[I 2026-06-29 16:49:48,576] Trial 29 pruned.
[I 2026-06-29 16:49:48,628] A new study created in RDB with name: KATL_v15_forecast_temp_at_as_of_remaining_warmup_base_lightgbm_mae_f
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names

,period,method,count,mae_f,rmse_f,arm,feature_version
0,validation_2024_2025,xgboost,728,1.660337,2.379674,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
1,validation_2024_2025,lightgbm,728,1.648960,2.375126,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
2,validation_2024_2025,catboost,728,1.664598,2.394125,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
3,validation_2024_2025,provider_mean,728,2.832206,4.006255,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
4,validation_2024_2025,provider_median,728,2.782240,3.911262,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
5,validation_2024_2025,nbm_raw,728,2.792647,3.816647,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
6,validation_2024_2025,hrrr_raw,728,3.556181,4.953880,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
7,validation_2024_2025,gfs_raw,728,3.254687,4.459385,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
8,test_2026,xgboost,170,1.577466,2.197311,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
9,test_2026,lightgbm,170,1.569194,2.208089,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
10,test_2026,catboost,170,1.487267,2.134523,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
11,test_2026,ridge_stack,170,1.483075,2.125702,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
12,test_2026,provider_mean,170,2.786086,4.048184,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
13,test_2026,provider_median,170,2.723802,3.926838,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
14,test_2026,nbm_raw,170,2.614555,3.750025,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
15,test_2026,hrrr_raw,170,3.216669,4.676677,forecast_temp_at_as_of,v15_forecast_temp_at_as_of
16,test_2026,gfs_raw,170,3.328938,4.532080,forecast_temp_at_as_of,v15_forecast_temp_at_as_of

Exported forecast_temp_at_as_of: D:\dev\weather-research\data\calibration\station_stacking_v15\forecast_temp_at_as_of\model_weights\KATL_station_high_regressor_v15_forecast_temp_at_as_of_stack.joblib
Running KATL precip_cloud: sqlite:///D:/dev/weather-research/data/calibration/station_stacking_v15/precip_cloud/KATL_optuna.sqlite3

D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:2621: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:2622: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
[I 2026-06-29 17:37:31,038] A new study created in RDB with name: KATL_v15_precip_cloud_remaining_warmup_base_xgboost_mae_f
[I 2026-06-29 17:37:32,072] Trial 0 finished with value: 11.672274447074303 and parameters: {'n_estimators': 1342, 'learning_rate': 0.19043899115982607, 'max_depth': 9, 'min_child_weight': 2.481040974867813, 'gamma': 2.340279606636548, 'subsample': 0.4513964382185317, 'colsample_bytree': 0.3877543479093296, 'reg_alpha': 2.478071022662141, 'reg_lambda': 0.6132587025321562}. Best is trial 0 with value: 11.672274447074303.
[I 2026-06-29 17:37:33,222] Trial 1 finished with value: 11.672274447074303 and parameters: {'n_estimators': 2493, 'learning_rate': 0.001120367191095075, 'max_depth': 12, 'min_child_weight': 21.368329072358772, 'gamma': 3.185086660174142, 'subsample': 0.4681862286846154, 'colsample_bytree': 0.46921293140473197, 'reg_alpha': 4.476173538513514e-07, 'reg_lambda': 0.20253776634919213}. Best is trial 0 with value: 11.672274447074303.
[I 2026-06-29 17:37:44,014] Trial 2 finished with value: 2.343227896330264 and parameters: {'n_estimators': 1540, 'learning_rate': 0.004992867109217114, 'max_depth': 8, 'min_child_weight': 0.03613894271216528, 'gamma': 4.3821697280282725, 'subsample': 0.5881351981408995, 'colsample_bytree': 0.6464454897410734, 'reg_alpha': 0.26430874752361627, 'reg_lambda': 0.0018119678627933364}. Best is trial 2 with value: 2.343227896330264.
[I 2026-06-29 17:37:46,726] Trial 3 finished with value: 5.094021786186721 and parameters: {'n_estimators': 1824, 'learning_rate': 0.026337502897485255, 'max_depth': 1, 'min_child_weight': 2.69264691008618, 'gamma': 2.557861855309373, 'subsample': 0.39228353544043165, 'colsample_bytree': 0.9667755992146666, 'reg_alpha': 38.6887231523051, 'reg_lambda': 12.408975837016275}. Best is trial 2 with value: 2.343227896330264.
[I 2026-06-29 17:38:03,898] Trial 4 finished with value: 1.9070428022257575 and parameters: {'n_estimators': 1101, 'learning_rate': 0.0017147936629846843, 'max_depth': 9, 'min_child_weight': 0.5762487216478605, 'gamma': 1.8305735226716824, 'subsample': 0.6718649915723256, 'colsample_bytree': 0.37235253872489193, 'reg_alpha': 8.162906555194692, 'reg_lambda': 0.004271500153828077}. Best is trial 4 with value: 1.9070428022257575.
[I 2026-06-29 17:38:26,326] Trial 5 finished with value: 2.022692757632706 and parameters: {'n_estimators': 2336, 'learning_rate': 0.00559067775661512, 'max_depth': 7, 'min_child_weight': 1.5375920235481764, 'gamma': 2.7728168328829055, 'subsample': 0.980230008046963, 'colsample_bytree': 0.8538363351847245, 'reg_alpha': 18.792618557420877, 'reg_lambda': 43.484449457612314}. Best is trial 4 with value: 1.9070428022257575.
[I 2026-06-29 17:38:27,919] Trial 6 finished with value: 1.7838653188815319 and parameters: {'n_estimators': 2113, 'learning_rate': 0.16240489353272883, 'max_depth': 2, 'min_child_weight': 0.06080390190296603, 'gamma': 0.678409333658071, 'subsample': 0.5614647149961218, 'colsample_bytree': 0.6026402382981633, 'reg_alpha': 1.8037999945880162e-07, 'reg_lambda': 16.668629892722056}. Best is trial 6 with value: 1.7838653188815319.
[I 2026-06-29 17:38:34,631] Trial 7 finished with value: 2.0249223282464914 and parameters: {'n_estimators': 1281, 'learning_rate': 0.0047169807141865345, 'max_depth': 7, 'min_child_weight': 0.0366181922039243, 'gamma': 12.032954711310595, 'subsample': 0.398457918391851, 'colsample_bytree': 0.9914765087903362, 'reg_alpha': 0.18490013641000916, 'reg_lambda': 0.0017869543989965139}. Best is trial 6 with value: 1.7838653188815319.
[I 2026-06-29 17:38:35,519] Trial 8 pruned.
[I 2026-06-29 17:38:44,428] Trial 9 finished with value: 1.7783740773389094 and parameters: {'n_estimators': 2201, 'learning_rate': 0.006215464818952927, 'max_depth': 1, 'min_child_weight': 0.17535949529764422, 'gamma': 4.877749830401205, 'subsample': 0.8242440159197416, 'colsample_bytree': 0.7644123563808884, 'reg_alpha': 4.4315220126915325, 'reg_lambda': 0.09450187118503514}. Best is trial 9 with value: 1.7783740773389094.
[I 2026-06-29 17:38:46,851] Trial 10 finished with value: 1.7737229792632898 and parameters: {'n_estimators': 462, 'learning_rate': 0.051323729958866915, 'max_depth': 10, 'min_child_weight': 1.7583640270008525, 'gamma': 11.564507699318415, 'subsample': 0.670967137636854, 'colsample_bytree': 0.689776339098296, 'reg_alpha': 1.3504926357029513e-05, 'reg_lambda': 0.0001445994629863374}. Best is trial 10 with value: 1.7737229792632898.
[I 2026-06-29 17:38:52,537] Trial 11 pruned.
[I 2026-06-29 17:38:58,395] Trial 12 pruned.
[I 2026-06-29 17:38:59,096] Trial 13 pruned.
[I 2026-06-29 17:39:03,004] Trial 14 finished with value: 1.6629401348046549 and parameters: {'n_estimators': 2872, 'learning_rate': 0.11587248002108354, 'max_depth': 1, 'min_child_weight': 1.1040511903162256, 'gamma': 6.261165047231685, 'subsample': 0.49437007680597467, 'colsample_bytree': 0.4279124887668938, 'reg_alpha': 1.125594744942969e-06, 'reg_lambda': 87.35792858155622}. Best is trial 14 with value: 1.6629401348046549.
[I 2026-06-29 17:39:03,607] Trial 15 pruned.
[I 2026-06-29 17:39:14,566] Trial 16 finished with value: 1.7244487310346666 and parameters: {'n_estimators': 3479, 'learning_rate': 0.028016885502806663, 'max_depth': 4, 'min_child_weight': 0.706933147248181, 'gamma': 8.034363960532348, 'subsample': 0.6852013564142475, 'colsample_bytree': 0.8609486010609017, 'reg_alpha': 0.0007576903076688526, 'reg_lambda': 192.3597475874131}. Best is trial 14 with value: 1.6629401348046549.
[I 2026-06-29 17:39:28,340] Trial 17 finished with value: 1.7368856988116934 and parameters: {'n_estimators': 3386, 'learning_rate': 0.017478919982976338, 'max_depth': 4, 'min_child_weight': 0.3214881455566735, 'gamma': 7.806461488018035, 'subsample': 0.7742427801462375, 'colsample_bytree': 0.8661546133566599, 'reg_alpha': 0.001687062589158873, 'reg_lambda': 185.86435125807805}. Best is trial 14 with value: 1.6629401348046549.
[I 2026-06-29 17:39:42,569] Trial 18 finished with value: 1.7135124916074038 and parameters: {'n_estimators': 2997, 'learning_rate': 0.015791722592673082, 'max_depth': 4, 'min_child_weight': 0.011780433865938213, 'gamma': 6.161201127152203, 'subsample': 0.6346834519624751, 'colsample_bytree': 0.5070107064372208, 'reg_alpha': 0.0013743717543530719, 'reg_lambda': 196.99396706244949}. Best is trial 14 with value: 1.6629401348046549.
[I 2026-06-29 17:39:46,148] Trial 19 finished with value: 1.795773988633488 and parameters: {'n_estimators': 2669, 'learning_rate': 0.018497034721529807, 'max_depth': 3, 'min_child_weight': 0.010296849889118127, 'gamma': 5.852464919151721, 'subsample': 0.5028989980253645, 'colsample_bytree': 0.5280533431996949, 'reg_alpha': 0.0035849619178030135, 'reg_lambda': 1.7833927853251788}. Best is trial 14 with value: 1.6629401348046549.
[I 2026-06-29 17:39:49,621] Trial 20 finished with value: 1.7375889154259976 and parameters: {'n_estimators': 2933, 'learning_rate': 0.07696378995171024, 'max_depth': 5, 'min_child_weight': 0.011065136021091005, 'gamma': 9.606417877149363, 'subsample': 0.5957363687872026, 'colsample_bytree': 0.4576177435670168, 'reg_alpha': 1.3860957336777205e-10, 'reg_lambda': 69.33716494315624}. Best is trial 14 with value: 1.6629401348046549.
[I 2026-06-29 17:40:05,700] Trial 21 finished with value: 1.6856152889663045 and parameters: {'n_estimators': 3003, 'learning_rate': 0.011290144738310288, 'max_depth': 3, 'min_child_weight': 0.6177562735490055, 'gamma': 6.22223527583044, 'subsample': 0.664267704662667, 'colsample_bytree': 0.35213458982427814, 'reg_alpha': 0.002778975589806964, 'reg_lambda': 141.8335228775532}. Best is trial 14 with value: 1.6629401348046549.
[I 2026-06-29 17:40:06,164] Trial 22 pruned.
[I 2026-06-29 17:40:21,038] Trial 23 finished with value: 1.7459074711740672 and parameters: {'n_estimators': 2941, 'learning_rate': 0.009732378559304361, 'max_depth': 5, 'min_child_weight': 0.10572029504346026, 'gamma': 6.506291661374973, 'subsample': 0.517674882691492, 'colsample_bytree': 0.5151041567684629, 'reg_alpha': 0.00011928578986866198, 'reg_lambda': 68.11464905377743}. Best is trial 14 with value: 1.6629401348046549.
[I 2026-06-29 17:40:30,360] Trial 24 pruned.
[I 2026-06-29 17:40:44,094] Trial 25 finished with value: 1.7642714678428986 and parameters: {'n_estimators': 2586, 'learning_rate': 0.0027242782713190637, 'max_depth': 2, 'min_child_weight': 1.041553291173818, 'gamma': 4.653298432747779, 'subsample': 0.6222745196846924, 'colsample_bytree': 0.5576455305268746, 'reg_alpha': 0.021487848111851553, 'reg_lambda': 47.48623956660302}. Best is trial 14 with value: 1.6629401348046549.
[I 2026-06-29 17:40:44,542] Trial 26 pruned.
[I 2026-06-29 17:40:45,013] Trial 27 pruned.
[I 2026-06-29 17:40:52,083] Trial 28 finished with value: 1.6923356412374055 and parameters: {'n_estimators': 2016, 'learning_rate': 0.014846093213696144, 'max_depth': 1, 'min_child_weight': 0.019785836862237994, 'gamma': 9.31171592598625, 'subsample': 0.44416164747113757, 'colsample_bytree': 0.41309097992952454, 'reg_alpha': 0.014824332383661536, 'reg_lambda': 26.034708508305215}. Best is trial 14 with value: 1.6629401348046549.
[I 2026-06-29 17:40:52,649] Trial 29 pruned.
[I 2026-06-29 17:40:52,709] A new study created in RDB with name: KATL_v15_precip_cloud_remaining_warmup_base_lightgbm_mae_f
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

,period,method,count,mae_f,rmse_f,arm,feature_version
0,validation_2024_2025,xgboost,728,1.671957,2.391998,precip_cloud,v15_precip_cloud
1,validation_2024_2025,lightgbm,728,1.663390,2.383674,precip_cloud,v15_precip_cloud
2,validation_2024_2025,catboost,728,1.700972,2.420937,precip_cloud,v15_precip_cloud
3,validation_2024_2025,provider_mean,728,2.832206,4.006255,precip_cloud,v15_precip_cloud
4,validation_2024_2025,provider_median,728,2.782240,3.911262,precip_cloud,v15_precip_cloud
5,validation_2024_2025,nbm_raw,728,2.792647,3.816647,precip_cloud,v15_precip_cloud
6,validation_2024_2025,hrrr_raw,728,3.556181,4.953880,precip_cloud,v15_precip_cloud
7,validation_2024_2025,gfs_raw,728,3.254687,4.459385,precip_cloud,v15_precip_cloud
8,test_2026,xgboost,170,1.570912,2.202376,precip_cloud,v15_precip_cloud
9,test_2026,lightgbm,170,1.542322,2.188441,precip_cloud,v15_precip_cloud
10,test_2026,catboost,170,1.623187,2.292603,precip_cloud,v15_precip_cloud
11,test_2026,ridge_stack,170,1.526176,2.154990,precip_cloud,v15_precip_cloud
12,test_2026,provider_mean,170,2.786086,4.048184,precip_cloud,v15_precip_cloud
13,test_2026,provider_median,170,2.723802,3.926838,precip_cloud,v15_precip_cloud
14,test_2026,nbm_raw,170,2.614555,3.750025,precip_cloud,v15_precip_cloud
15,test_2026,hrrr_raw,170,3.216669,4.676677,precip_cloud,v15_precip_cloud
16,test_2026,gfs_raw,170,3.328938,4.532080,precip_cloud,v15_precip_cloud

Exported precip_cloud: D:\dev\weather-research\data\calibration\station_stacking_v15\precip_cloud\model_weights\KATL_station_high_regressor_v15_precip_cloud_stack.joblib
Wrote KATL v15 comparisons: D:\dev\weather-research\data\calibration\station_stacking_v15\KATL_v15_arm_test_metrics.csv and D:\dev\weather-research\data\calibration\station_stacking_v15\KATL_v15_arm_common_date_comparison.csv

## Arm Scoreboards

In [7]:
scoreboards = pd.concat(
    [result.scoreboard.assign(arm=arm) for arm, result in results.items()],
    ignore_index=True,
) if results else pd.DataFrame()

scoreboards.sort_values(["period", "mae_f", "arm", "method"])

,period,method,count,mae_f,rmse_f,arm
28,test_2026,ridge_stack,170,1.483075,2.125702,forecast_temp_at_as_of
27,test_2026,catboost,170,1.487267,2.134523,forecast_temp_at_as_of
45,test_2026,ridge_stack,170,1.526176,2.154990,precip_cloud
43,test_2026,lightgbm,170,1.542322,2.188441,precip_cloud
9,test_2026,lightgbm,170,1.558784,2.223175,base
11,test_2026,ridge_stack,170,1.565049,2.212661,base
26,test_2026,lightgbm,170,1.569194,2.208089,forecast_temp_at_as_of
42,test_2026,xgboost,170,1.570912,2.202376,precip_cloud
25,test_2026,xgboost,170,1.577466,2.197311,forecast_temp_at_as_of
10,test_2026,catboost,170,1.582195,2.211646,base
44,test_2026,catboost,170,1.623187,2.292603,precip_cloud
8,test_2026,xgboost,170,1.631589,2.319565,base
14,test_2026,nbm_raw,170,2.614555,3.750025,base
31,test_2026,nbm_raw,170,2.614555,3.750025,forecast_temp_at_as_of
48,test_2026,nbm_raw,170,2.614555,3.750025,precip_cloud
13,test_2026,provider_median,170,2.723802,3.926838,base
30,test_2026,provider_median,170,2.723802,3.926838,forecast_temp_at_as_of
47,test_2026,provider_median,170,2.723802,3.926838,precip_cloud
12,test_2026,provider_mean,170,2.786086,4.048184,base
29,test_2026,provider_mean,170,2.786086,4.048184,forecast_temp_at_as_of
46,test_2026,provider_mean,170,2.786086,4.048184,precip_cloud
15,test_2026,hrrr_raw,170,3.216669,4.676677,base
32,test_2026,hrrr_raw,170,3.216669,4.676677,forecast_temp_at_as_of
49,test_2026,hrrr_raw,170,3.216669,4.676677,precip_cloud
16,test_2026,gfs_raw,170,3.328938,4.532080,base
33,test_2026,gfs_raw,170,3.328938,4.532080,forecast_temp_at_as_of
50,test_2026,gfs_raw,170,3.328938,4.532080,precip_cloud
18,validation_2024_2025,lightgbm,728,1.648960,2.375126,forecast_temp_at_as_of
17,validation_2024_2025,xgboost,728,1.660337,2.379674,forecast_temp_at_as_of
35,validation_2024_2025,lightgbm,728,1.663390,2.383674,precip_cloud
19,validation_2024_2025,catboost,728,1.664598,2.394125,forecast_temp_at_as_of
0,validation_2024_2025,xgboost,728,1.671761,2.384807,base
34,validation_2024_2025,xgboost,728,1.671957,2.391998,precip_cloud
1,validation_2024_2025,lightgbm,728,1.672786,2.417305,base
2,validation_2024_2025,catboost,728,1.682298,2.423920,base
36,validation_2024_2025,catboost,728,1.700972,2.420937,precip_cloud
4,validation_2024_2025,provider_median,728,2.782240,3.911262,base
21,validation_2024_2025,provider_median,728,2.782240,3.911262,forecast_temp_at_as_of
38,validation_2024_2025,provider_median,728,2.782240,3.911262,precip_cloud
5,validation_2024_2025,nbm_raw,728,2.792647,3.816647,base
22,validation_2024_2025,nbm_raw,728,2.792647,3.816647,forecast_temp_at_as_of
39,validation_2024_2025,nbm_raw,728,2.792647,3.816647,precip_cloud
3,validation_2024_2025,provider_mean,728,2.832206,4.006255,base
20,validation_2024_2025,provider_mean,728,2.832206,4.006255,forecast_temp_at_as_of
37,validation_2024_2025,provider_mean,728,2.832206,4.006255,precip_cloud
7,validation_2024_2025,gfs_raw,728,3.254687,4.459385,base
24,validation_2024_2025,gfs_raw,728,3.254687,4.459385,forecast_temp_at_as_of
41,validation_2024_2025,gfs_raw,728,3.254687,4.459385,precip_cloud
6,validation_2024_2025,hrrr_raw,728,3.556181,4.953880,base
23,validation_2024_2025,hrrr_raw,728,3.556181,4.953880,forecast_temp_at_as_of
40,validation_2024_2025,hrrr_raw,728,3.556181,4.953880,precip_cloud

## Common-Date Comparison Versus Base

In [8]:
metrics_path = OUTPUT_DIR / f"{STATION_ID}_v15_arm_test_metrics.csv"
comparison_path = OUTPUT_DIR / f"{STATION_ID}_v15_arm_common_date_comparison.csv"

arm_test_metrics = pd.read_csv(metrics_path) if metrics_path.exists() else pd.DataFrame()
common_date_comparison = pd.read_csv(comparison_path) if comparison_path.exists() else pd.DataFrame()

common_date_comparison.sort_values(["method", "delta_mae_f", "comparison_arm"]) if not common_date_comparison.empty else common_date_comparison

,station_id,baseline_arm,comparison_arm,feature_version,model_version,method,common_date_count,base_mae_f,arm_mae_f,delta_mae_f,base_rmse_f,arm_rmse_f,delta_rmse_f,arm_better_days,base_better_days,tied_days,actual_mismatch_count,first_common_date,last_common_date
0,KATL,base,forecast_temp_at_as_of,v15_forecast_temp_at_as_of,station_high_regressor_v15_forecast_temp_at_as...,catboost,170,1.582195,1.487267,-0.094928,2.211646,2.134523,-0.077124,95,75,0,0,2026-01-01,2026-06-21
9,KATL,base,precip_cloud,v15_precip_cloud,station_high_regressor_v15_precip_cloud_stack,catboost,170,1.582195,1.623187,0.040992,2.211646,2.292603,0.080957,87,83,0,0,2026-01-01,2026-06-21
1,KATL,base,forecast_temp_at_as_of,v15_forecast_temp_at_as_of,station_high_regressor_v15_forecast_temp_at_as...,gfs_raw,170,3.328938,3.328938,0.000000,4.532080,4.532080,0.000000,0,0,170,0,2026-01-01,2026-06-21
10,KATL,base,precip_cloud,v15_precip_cloud,station_high_regressor_v15_precip_cloud_stack,gfs_raw,170,3.328938,3.328938,0.000000,4.532080,4.532080,0.000000,0,0,170,0,2026-01-01,2026-06-21
2,KATL,base,forecast_temp_at_as_of,v15_forecast_temp_at_as_of,station_high_regressor_v15_forecast_temp_at_as...,hrrr_raw,170,3.216669,3.216669,0.000000,4.676677,4.676677,0.000000,0,0,170,0,2026-01-01,2026-06-21
11,KATL,base,precip_cloud,v15_precip_cloud,station_high_regressor_v15_precip_cloud_stack,hrrr_raw,170,3.216669,3.216669,0.000000,4.676677,4.676677,0.000000,0,0,170,0,2026-01-01,2026-06-21
12,KATL,base,precip_cloud,v15_precip_cloud,station_high_regressor_v15_precip_cloud_stack,lightgbm,170,1.558784,1.542322,-0.016462,2.223175,2.188441,-0.034734,92,78,0,0,2026-01-01,2026-06-21
3,KATL,base,forecast_temp_at_as_of,v15_forecast_temp_at_as_of,station_high_regressor_v15_forecast_temp_at_as...,lightgbm,170,1.558784,1.569194,0.010410,2.223175,2.208089,-0.015086,85,85,0,0,2026-01-01,2026-06-21
4,KATL,base,forecast_temp_at_as_of,v15_forecast_temp_at_as_of,station_high_regressor_v15_forecast_temp_at_as...,nbm_raw,170,2.614555,2.614555,0.000000,3.750025,3.750025,0.000000,0,0,170,0,2026-01-01,2026-06-21
13,KATL,base,precip_cloud,v15_precip_cloud,station_high_regressor_v15_precip_cloud_stack,nbm_raw,170,2.614555,2.614555,0.000000,3.750025,3.750025,0.000000,0,0,170,0,2026-01-01,2026-06-21
5,KATL,base,forecast_temp_at_as_of,v15_forecast_temp_at_as_of,station_high_regressor_v15_forecast_temp_at_as...,provider_mean,170,2.786086,2.786086,0.000000,4.048184,4.048184,0.000000,0,0,170,0,2026-01-01,2026-06-21
14,KATL,base,precip_cloud,v15_precip_cloud,station_high_regressor_v15_precip_cloud_stack,provider_mean,170,2.786086,2.786086,0.000000,4.048184,4.048184,0.000000,0,0,170,0,2026-01-01,2026-06-21
6,KATL,base,forecast_temp_at_as_of,v15_forecast_temp_at_as_of,station_high_regressor_v15_forecast_temp_at_as...,provider_median,170,2.723802,2.723802,0.000000,3.926838,3.926838,0.000000,0,0,170,0,2026-01-01,2026-06-21
15,KATL,base,precip_cloud,v15_precip_cloud,station_high_regressor_v15_precip_cloud_stack,provider_median,170,2.723802,2.723802,0.000000,3.926838,3.926838,0.000000,0,0,170,0,2026-01-01,2026-06-21
7,KATL,base,forecast_temp_at_as_of,v15_forecast_temp_at_as_of,station_high_regressor_v15_forecast_temp_at_as...,ridge_stack,170,1.565049,1.483075,-0.081974,2.212661,2.125702,-0.086959,98,72,0,0,2026-01-01,2026-06-21
16,KATL,base,precip_cloud,v15_precip_cloud,station_high_regressor_v15_precip_cloud_stack,ridge_stack,170,1.565049,1.526176,-0.038873,2.212661,2.154990,-0.057671,88,82,0,0,2026-01-01,2026-06-21
17,KATL,base,precip_cloud,v15_precip_cloud,station_high_regressor_v15_precip_cloud_stack,xgboost,170,1.631589,1.570912,-0.060677,2.319565,2.202376,-0.117189,78,92,0,0,2026-01-01,2026-06-21
8,KATL,base,forecast_temp_at_as_of,v15_forecast_temp_at_as_of,station_high_regressor_v15_forecast_temp_at_as...,xgboost,170,1.631589,1.577466,-0.054123,2.319565,2.197311,-0.122254,85,85,0,0,2026-01-01,2026-06-21

## Added Feature Selection Audit

In [9]:
selected_rows = []
for arm, result in results.items():
    selected = set(result.feature_columns["feature"])
    selected_rows.append(
        {
            "arm": arm,
            "selected_feature_count": len(selected),
            "v15_added_features_selected": sorted(selected & set(V15_ADDITIONAL_FEATURE_COLUMNS)),
            "forecast_temp_features_selected": sorted(selected & set(V15_FORECAST_TEMP_AT_AS_OF_FEATURE_COLUMNS)),
            "precip_cloud_features_selected": sorted(selected & set(V15_PRECIP_CLOUD_FEATURE_COLUMNS)),
        }
    )

pd.DataFrame(selected_rows)

,arm,selected_feature_count,v15_added_features_selected,forecast_temp_features_selected,precip_cloud_features_selected
0,base,273,[],[],[]
1,forecast_temp_at_as_of,221,"[v13_forecast_temp_at_as_of_mean_f, v13_foreca...","[v13_forecast_temp_at_as_of_mean_f, v13_foreca...",[]
2,precip_cloud,221,"[v13_cloud_cover_max_pct, v13_cloud_cover_mean...",[],"[v13_cloud_cover_max_pct, v13_cloud_cover_mean..."

## Added Feature Coverage

In [10]:
coverage_frames = []
for arm, result in results.items():
    available = [column for column in V15_ADDITIONAL_FEATURE_COLUMNS if column in result.features]
    if not available:
        continue
    coverage = (
        result.features[available]
        .notna()
        .mean()
        .mul(100)
        .rename("coverage_pct")
        .reset_index()
        .rename(columns={"index": "feature"})
    )
    coverage["arm"] = arm
    coverage_frames.append(coverage)

added_feature_coverage = pd.concat(coverage_frames, ignore_index=True) if coverage_frames else pd.DataFrame()
added_feature_coverage.sort_values(["arm", "coverage_pct"], ascending=[True, False])

,feature,coverage_pct,arm
0,v13_forecast_temp_at_as_of_mean_f,100.000000,forecast_temp_at_as_of
1,v13_forecast_temp_at_as_of_minus_observed_mean_f,100.000000,forecast_temp_at_as_of
2,v13_forecast_temp_at_as_of_spread_f,100.000000,forecast_temp_at_as_of
3,v13_forecast_temp_bias_remaining_warmup_intera...,100.000000,forecast_temp_at_as_of
4,v13_cloud_cover_mean_pct,66.016016,forecast_temp_at_as_of
5,v13_cloud_cover_max_pct,66.016016,forecast_temp_at_as_of
6,v13_cloud_cover_remaining_warmup_interaction,66.016016,forecast_temp_at_as_of
7,v13_precip_cloud_remaining_warmup_interaction,65.915916,forecast_temp_at_as_of
8,v13_forecast_temp_at_as_of_mean_f,100.000000,precip_cloud
9,v13_forecast_temp_at_as_of_minus_observed_mean_f,100.000000,precip_cloud
10,v13_forecast_temp_at_as_of_spread_f,100.000000,precip_cloud
11,v13_forecast_temp_bias_remaining_warmup_intera...,100.000000,precip_cloud
12,v13_cloud_cover_mean_pct,66.016016,precip_cloud
13,v13_cloud_cover_max_pct,66.016016,precip_cloud
14,v13_cloud_cover_remaining_warmup_interaction,66.016016,precip_cloud
15,v13_precip_cloud_remaining_warmup_interaction,65.915916,precip_cloud

## Raw Weather Sprawl Check

In [11]:
raw_weather_tokens = (
    "cloud",
    "ceiling",
    "dewpoint",
    "forecast_temp_at_as_of",
    "humidity",
    "precip",
    "pressure",
    "shortwave",
    "visibility",
    "wind_",
)
raw_weather_selected = []
for arm, result in results.items():
    selected = result.feature_columns["feature"].astype(str)
    raw_weather_selected.extend(
        {
            "arm": arm,
            "feature": feature,
        }
        for feature in selected
        if feature.startswith(("gfs_", "hrrr_", "nbm_"))
        and any(token in feature for token in raw_weather_tokens)
    )

pd.DataFrame(raw_weather_selected)

     arm                                            feature
0   base                                  gfs_precip_amount
1   base                       gfs_forecast_precip_total_mm
2   base                      gfs_forecast_precip_max_1h_mm
3   base                    gfs_forecast_precip_hours_count
4   base                            gfs_forecast_has_precip
5   base                 gfs_forecast_precip_intensity_code
6   base                                gfs_wind_speed_mean
7   base                                 gfs_wind_speed_max
8   base                            gfs_wind_direction_mean
9   base                                  gfs_wind_gust_max
10  base                                gfs_dewpoint_mean_f
11  base                                  gfs_humidity_mean
12  base                                 hrrr_precip_amount
13  base                      hrrr_forecast_precip_total_mm
14  base                     hrrr_forecast_precip_max_1h_mm
15  base                   hrrr_forecast_precip_hours_count
16  base                           hrrr_forecast_has_precip
17  base                hrrr_forecast_precip_intensity_code
18  base                               hrrr_wind_speed_mean
19  base                                hrrr_wind_speed_max
20  base                           hrrr_wind_direction_mean
21  base                                 hrrr_wind_gust_max
22  base                               hrrr_dewpoint_mean_f
23  base                                 hrrr_humidity_mean
24  base                                 gfs_wind_gustiness
25  base                          gfs_dewpoint_depression_f
26  base                                   gfs_wind_dir_sin
27  base                                   gfs_wind_dir_cos
28  base                                hrrr_wind_gustiness
29  base                         hrrr_dewpoint_depression_f
30  base                                  hrrr_wind_dir_sin
31  base                                  hrrr_wind_dir_cos
32  base                    gfs_hrrr_dewpoint_mean_f_diff_f
33  base                gfs_hrrr_dewpoint_mean_f_abs_diff_f
34  base                      gfs_hrrr_humidity_mean_diff_f
35  base                  gfs_hrrr_humidity_mean_abs_diff_f
36  base                    gfs_hrrr_wind_speed_mean_diff_f
37  base                gfs_hrrr_wind_speed_mean_abs_diff_f
38  base                     gfs_hrrr_wind_speed_max_diff_f
39  base                 gfs_hrrr_wind_speed_max_abs_diff_f
40  base                      gfs_hrrr_wind_gust_max_diff_f
41  base                  gfs_hrrr_wind_gust_max_abs_diff_f
42  base                      gfs_hrrr_precip_amount_diff_f
43  base                  gfs_hrrr_precip_amount_abs_diff_f
44  base           gfs_hrrr_forecast_precip_total_mm_diff_f
45  base       gfs_hrrr_forecast_precip_total_mm_abs_diff_f
46  base          gfs_hrrr_forecast_precip_max_1h_mm_diff_f
47  base      gfs_hrrr_forecast_precip_max_1h_mm_abs_diff_f
48  base        gfs_hrrr_forecast_precip_hours_count_diff_f
49  base    gfs_hrrr_forecast_precip_hours_count_abs_diff_f
50  base     gfs_hrrr_forecast_precip_intensity_code_diff_f
51  base  gfs_hrrr_forecast_precip_intensity_code_abs_di...
52  base             gfs_dewpoint_minus_observed_dewpoint_f
53  base               gfs_humidity_minus_observed_humidity
54  base           gfs_wind_speed_minus_observed_wind_speed
55  base            hrrr_dewpoint_minus_observed_dewpoint_f
56  base              hrrr_humidity_minus_observed_humidity
57  base          hrrr_wind_speed_minus_observed_wind_speed

## Rounded Within 1F Accuracy

In [12]:
rounded_frames = []
for arm, result in results.items():
    preds = pd.concat(
        [
            result.validation_predictions.assign(period="validation_2024_2025"),
            result.test_predictions.assign(period="oof_2026"),
        ],
        ignore_index=True,
    )
    predicted_high = pd.to_numeric(preds["predicted_high_f"], errors="coerce")
    preds["predicted_high_rounded_f"] = np.floor(predicted_high + 0.5)
    preds["within_1f_after_round"] = (
        pd.to_numeric(preds["actual_high_f"], errors="coerce") - preds["predicted_high_rounded_f"]
    ).abs().le(1)
    rounded = (
        preds
        .dropna(subset=["actual_high_f", "predicted_high_rounded_f"])
        .groupby(["period", "method"], as_index=False)
        .agg(
            count=("within_1f_after_round", "size"),
            within_1f_count=("within_1f_after_round", "sum"),
            within_1f_accuracy_pct=("within_1f_after_round", lambda x: x.mean() * 100),
        )
    )
    rounded["arm"] = arm
    rounded_frames.append(rounded)

within_1f_accuracy_by_period = pd.concat(rounded_frames, ignore_index=True) if rounded_frames else pd.DataFrame()
within_1f_accuracy_by_period.sort_values(["period", "method", "within_1f_accuracy_pct"], ascending=[True, True, False])

,period,method,count,within_1f_count,within_1f_accuracy_pct,arm
17,oof_2026,catboost,170,111,65.294118,forecast_temp_at_as_of
34,oof_2026,catboost,170,102,60.000000,precip_cloud
0,oof_2026,catboost,170,100,58.823529,base
1,oof_2026,gfs_raw,170,47,27.647059,base
18,oof_2026,gfs_raw,170,47,27.647059,forecast_temp_at_as_of
35,oof_2026,gfs_raw,170,47,27.647059,precip_cloud
2,oof_2026,hrrr_raw,170,56,32.941176,base
19,oof_2026,hrrr_raw,170,56,32.941176,forecast_temp_at_as_of
36,oof_2026,hrrr_raw,170,56,32.941176,precip_cloud
37,oof_2026,lightgbm,170,102,60.000000,precip_cloud
3,oof_2026,lightgbm,170,99,58.235294,base
20,oof_2026,lightgbm,170,98,57.647059,forecast_temp_at_as_of
4,oof_2026,nbm_raw,170,68,40.000000,base
21,oof_2026,nbm_raw,170,68,40.000000,forecast_temp_at_as_of
38,oof_2026,nbm_raw,170,68,40.000000,precip_cloud
5,oof_2026,provider_mean,170,63,37.058824,base
22,oof_2026,provider_mean,170,63,37.058824,forecast_temp_at_as_of
39,oof_2026,provider_mean,170,63,37.058824,precip_cloud
6,oof_2026,provider_median,170,63,37.058824,base
23,oof_2026,provider_median,170,63,37.058824,forecast_temp_at_as_of
40,oof_2026,provider_median,170,63,37.058824,precip_cloud
24,oof_2026,ridge_stack,170,107,62.941176,forecast_temp_at_as_of
41,oof_2026,ridge_stack,170,104,61.176471,precip_cloud
7,oof_2026,ridge_stack,170,102,60.000000,base
42,oof_2026,xgboost,170,105,61.764706,precip_cloud
8,oof_2026,xgboost,170,103,60.588235,base
25,oof_2026,xgboost,170,101,59.411765,forecast_temp_at_as_of
43,validation_2024_2025,catboost,728,433,59.478022,precip_cloud
9,validation_2024_2025,catboost,728,425,58.379121,base
26,validation_2024_2025,catboost,728,423,58.104396,forecast_temp_at_as_of
10,validation_2024_2025,gfs_raw,728,204,28.021978,base
27,validation_2024_2025,gfs_raw,728,204,28.021978,forecast_temp_at_as_of
44,validation_2024_2025,gfs_raw,728,204,28.021978,precip_cloud
11,validation_2024_2025,hrrr_raw,728,223,30.631868,base
28,validation_2024_2025,hrrr_raw,728,223,30.631868,forecast_temp_at_as_of
45,validation_2024_2025,hrrr_raw,728,223,30.631868,precip_cloud
29,validation_2024_2025,lightgbm,728,451,61.950549,forecast_temp_at_as_of
46,validation_2024_2025,lightgbm,728,431,59.203297,precip_cloud
12,validation_2024_2025,lightgbm,728,430,59.065934,base
13,validation_2024_2025,nbm_raw,728,239,32.829670,base
30,validation_2024_2025,nbm_raw,728,239,32.829670,forecast_temp_at_as_of
47,validation_2024_2025,nbm_raw,728,239,32.829670,precip_cloud
14,validation_2024_2025,provider_mean,728,263,36.126374,base
31,validation_2024_2025,provider_mean,728,263,36.126374,forecast_temp_at_as_of
48,validation_2024_2025,provider_mean,728,263,36.126374,precip_cloud
15,validation_2024_2025,provider_median,728,250,34.340659,base
32,validation_2024_2025,provider_median,728,250,34.340659,forecast_temp_at_as_of
49,validation_2024_2025,provider_median,728,250,34.340659,precip_cloud
33,validation_2024_2025,xgboost,728,432,59.340659,forecast_temp_at_as_of
50,validation_2024_2025,xgboost,728,428,58.791209,precip_cloud
16,validation_2024_2025,xgboost,728,426,58.516484,base

## Bracket Metrics

In [13]:
bracket_frames = []
for arm, result in results.items():
    bracket = result.bracket_metrics.copy()
    bracket["arm"] = arm
    bracket_frames.append(bracket)

pd.concat(bracket_frames, ignore_index=True) if bracket_frames else pd.DataFrame()

,method,count,mae_f,rmse_f,bracket_accuracy_pct,arm
0,xgboost,170,1.631589,2.319565,40.588235,base
1,lightgbm,170,1.558784,2.223175,41.764706,base
2,catboost,170,1.582195,2.211646,42.941176,base
3,ridge_stack,170,1.565049,2.212661,40.588235,base
4,provider_mean,170,2.786086,4.048184,25.294118,base
5,provider_median,170,2.723802,3.926838,27.647059,base
6,nbm_raw,170,2.614555,3.750025,28.823529,base
7,hrrr_raw,170,3.216669,4.676677,24.705882,base
8,gfs_raw,170,3.328938,4.532080,20.588235,base
9,xgboost,170,1.577466,2.197311,37.647059,forecast_temp_at_as_of
10,lightgbm,170,1.569194,2.208089,44.117647,forecast_temp_at_as_of
11,catboost,170,1.487267,2.134523,47.647059,forecast_temp_at_as_of
12,ridge_stack,170,1.483075,2.125702,42.941176,forecast_temp_at_as_of
13,provider_mean,170,2.786086,4.048184,25.294118,forecast_temp_at_as_of
14,provider_median,170,2.723802,3.926838,27.647059,forecast_temp_at_as_of
15,nbm_raw,170,2.614555,3.750025,28.823529,forecast_temp_at_as_of
16,hrrr_raw,170,3.216669,4.676677,24.705882,forecast_temp_at_as_of
17,gfs_raw,170,3.328938,4.532080,20.588235,forecast_temp_at_as_of
18,xgboost,170,1.570912,2.202376,43.529412,precip_cloud
19,lightgbm,170,1.542322,2.188441,42.941176,precip_cloud
20,catboost,170,1.623187,2.292603,45.294118,precip_cloud
21,ridge_stack,170,1.526176,2.154990,40.0,precip_cloud
22,provider_mean,170,2.786086,4.048184,25.294118,precip_cloud
23,provider_median,170,2.723802,3.926838,27.647059,precip_cloud
24,nbm_raw,170,2.614555,3.750025,28.823529,precip_cloud
25,hrrr_raw,170,3.216669,4.676677,24.705882,precip_cloud
26,gfs_raw,170,3.328938,4.532080,20.588235,precip_cloud