# KATL Station Stacking V20 Peak Timing

Single-arm Wunderground-only experiment using V11 Settlement Fix temperature alignment, curated live-safe HRRR/NBM peak-timing features, a 3% train-fold missingness gate, and expanding 2021–2025 validation folds. The readiness section can run while shards are still being pulled and blocks model tuning until coverage is sufficient.

In [1]:
from pathlib import Path
import os
import sys
import warnings

warnings.filterwarnings("ignore", message="IProgress not found.*")
warnings.filterwarnings("ignore", message="Skipping features without any observed values.*")

PROJECT_ROOT = Path.cwd().resolve()
while not (PROJECT_ROOT / "src" / "calibration" / "station_stacking.py").exists():
    if PROJECT_ROOT.parent == PROJECT_ROOT:
        raise RuntimeError("Could not find project root containing src/calibration/station_stacking.py")
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

os.environ["WEATHER_RESEARCH_INCLUDE_DIRECT_NBM"] = "1"

STATION_ID = "KATL"
PROVIDERS = ("gfs", "hrrr", "nbm")
TREND_COLUMNS = [
    "observed_temp_change_last_1h_f",
    "observed_temp_change_last_3h_f",
    "observed_morning_warmup_rate_f_per_hour",
    "observed_high_so_far_change_since_9am_f",
]
TIMING_MODE = "same_day_11am_live_safe"
FAST_MODE = False
OPTUNA_TRIALS = 30
STACK_OPTUNA_TRIALS = 30
OPTUNA_STARTUP_TRIALS = 15
STACK_OPTUNA_STARTUP_TRIALS = 15
OPTUNA_METRIC = "mae_f"
OPTUNA_VERBOSE = True
MODEL_VERSION = "station_high_regressor_v20_peak_timing_stack"
EXPORT_MODEL_WEIGHTS = False
PROJECT_ROOT

WindowsPath('D:/dev/weather-research')

In [2]:
import numpy as np
import pandas as pd

from src.export_station_stacking_v2_models import export_station_model_weights
from src.calibration.station_stacking import (
    StationStackingConfig,
    V20_ENGINEERED_FEATURE_COLUMNS,
    V20_PEAK_TIMING_RAW_FEATURE_COLUMNS,
    build_station_wide_dataset,
    v20_peak_timing_readiness,
    V11_SETTLEMENT_FIX_TEMP_FEATURE_COLUMNS,
    _fit_feature_columns,
    _modeling_frame,
    V11_DROPPED_FEATURE_COLUMNS,
    V11_FEATURE_COLUMNS,
    V20_EXPANDING_FOLDS,
    missing_model_dependencies,
    provider_availability,
    run_station_year_split_experiment,
)

## V11 Contract

`feature_version="v20_peak_timing"` keeps the v9 feature contract and remaining-warmup target, but trains base learners with Huber-style objectives while retaining the ridge stack selected by validation MAE.

In [3]:
fold_spec = pd.DataFrame(
    [
        {
            "fold": fold.name,
            "train_start_year": fold.train_start_year,
            "train_end_year": fold.train_end_year,
            "validation_year": fold.validation_year,
        }
        for fold in V20_EXPANDING_FOLDS
    ]
)

fold_spec

                     fold  train_start_year  train_end_year  validation_year
0       fold_2021_to_2022              2021            2021             2022
1  fold_2021_2022_to_2023              2021            2022             2023
2  fold_2021_2023_to_2024              2021            2023             2024
3  fold_2021_2024_to_2025              2021            2024             2025

In [4]:
V11_FEATURE_COLUMNS, sorted(V11_DROPPED_FEATURE_COLUMNS)

(['v2_recent_heat_anomaly_f',
  'v2_recent_heat_momentum_f',
  'v2_morning_warmup_to_consensus_f',
  'v2_consensus_minus_7d_actual_f',
  'v2_spread_per_warmup_f',
  'v2_humidity_warmup_interaction',
  'v3_high_so_far_above_current_f',
  'v3_remaining_warmup_from_high_so_far_f',
  'v3_high_so_far_minus_lag_1d_f',
  'v3_high_so_far_minus_7d_actual_f',
  'v3_remaining_warmup_per_spread_f',
  'v3_humidity_remaining_warmup_interaction',
  'v4_forecast_precip_total_mean_mm',
  'v4_forecast_precip_total_max_mm',
  'v4_forecast_precip_total_spread_mm',
  'v4_forecast_precip_max_1h_mean_mm',
  'v4_forecast_precip_hours_mean',
  'v4_forecast_precip_intensity_mean',
  'v4_forecast_precip_intensity_max',
  'v4_any_forecast_precip',
  'v4_all_forecast_precip',
  'v4_observed_precip_any',
  'v4_observed_precip_recent_mm_est',
  'v4_forecast_total_minus_observed_recent_mm',
  'v4_forecast_observed_precip_match',
  'v4_forecast_wet_observed_dry',
  'v4_observed_wet_forecast_dry',
  'v4_precip_humidity_interaction',
  'v4_precip_remaining_warmup_interaction',
  'observed_temp_change_last_1h_f',
  'observed_temp_change_last_3h_f',
  'observed_morning_warmup_rate_f_per_hour',
  'observed_high_so_far_change_since_9am_f',
  'v8_provider_max_remaining_from_high_so_far_f',
  'v8_provider_min_remaining_from_high_so_far_f',
  'v8_provider_median_remaining_from_high_so_far_f',
  'v8_provider_spread_per_remaining_warmup_f',
  'v8_month_remaining_warmup_mean_f',
  'v8_month_remaining_warmup_count',
  'v8_recent_remaining_warmup_7d_mean_f',
  'v8_recent_remaining_warmup_30d_mean_f',
  'v8_provider_mean_remaining_vs_month_normal_f',
  'v8_cloud_cover_mean_remaining_warmup_interaction',
  'v8_cloud_cover_max_remaining_warmup_interaction',
  'v8_precip_total_remaining_warmup_interaction',
  'v8_precip_max_1h_remaining_warmup_interaction',
  'v8_wind_speed_mean_remaining_warmup_interaction',
  'v8_wind_gust_max_remaining_warmup_interaction',
  'v8_forecast_dewpoint_mean_f',
  'v8_forecast_dewpoint_depression_mean_f',
  'v8_dewpoint_mean_remaining_warmup_interaction',
  'v8_dewpoint_depression_remaining_warmup_interaction',
  'climatology_high_10y_f',
  'climatology_high_10y_std_f',
  'climatology_high_10y_count',
  'provider_mean_minus_climatology_10y_f',
  'observed_temp_minus_climatology_10y_f',
  'observed_high_so_far_minus_climatology_10y_f'],
 ['actual_minus_climatology_10y_f_DIAGNOSTIC_ONLY',
  'climatology_source_end_year',
  'climatology_source_start_year',
  'gfs_as_of_hour_local',
  'gfs_available',
  'gfs_forecast_window_hours',
  'gfs_grid_dist_km_mean',
  'gfs_horizon_hours',
  'gfs_hrrr_grid_dist_km_mean_abs_diff_f',
  'gfs_hrrr_grid_dist_km_mean_diff_f',
  'gfs_issue_hour_utc',
  'gfs_missing',
  'hrrr_as_of_hour_local',
  'hrrr_available',
  'hrrr_forecast_hour_max',
  'hrrr_forecast_hour_min',
  'hrrr_forecast_lead_hours',
  'hrrr_forecast_window_hours',
  'hrrr_grid_dist_km_mean',
  'hrrr_horizon_hours',
  'hrrr_issue_hour_local',
  'hrrr_issue_hour_utc',
  'hrrr_missing',
  'is_active_polymarket_station',
  'lat',
  'lon',
  'nbm_as_of_hour_local',
  'nbm_available',
  'nbm_forecast_window_hours',
  'nbm_horizon_hours',
  'nbm_issue_hour_local',
  'nbm_issue_hour_utc',
  'nbm_missing',
  'observed_fetch_status',
  'observed_observation_type',
  'observed_pressure_source',
  'provider_count_available',
  'year'])

## Data Availability

In [5]:
availability = provider_availability(
    PROJECT_ROOT,
    timing_mode=TIMING_MODE,
    providers=PROVIDERS,
)

availability.loc[availability["station_id"].eq(STATION_ID)]

  station_id provider  row_count first_contract_date last_contract_date
0       KATL      gfs       1999          2021-01-01         2026-07-12
1       KATL     hrrr       1998          2021-01-01         2026-06-21
2       KATL      nbm       1998          2021-01-01         2026-07-12

## Model Scores

## Peak-Timing and Wunderground Readiness Gate

In [6]:
readiness_features = build_station_wide_dataset(
    PROJECT_ROOT,
    station_id=STATION_ID,
    timing_mode=TIMING_MODE,
    providers=PROVIDERS,
    feature_version="v20_peak_timing",
    target_source="wunderground_only",
)
EVALUATION_END_DATE = "2026-07-01"  # provisional; official V20 cutoff remains 2026-07-14
v20_ready, readiness_summary, readiness_missing_dates, readiness_fold_missingness = v20_peak_timing_readiness(
    readiness_features,
    station_id=STATION_ID,
    folds=V20_EXPANDING_FOLDS,
    max_missing_fraction=0.03,
    end_date=EVALUATION_END_DATE,
)
readiness_dir = PROJECT_ROOT / "data" / "calibration" / "station_stacking_v20_peak_timing"
readiness_dir.mkdir(parents=True, exist_ok=True)
readiness_summary.to_csv(readiness_dir / f"{STATION_ID}_readiness_summary.csv", index=False)
readiness_missing_dates.to_csv(readiness_dir / f"{STATION_ID}_readiness_missing_dates.csv", index=False)
readiness_fold_missingness.to_csv(readiness_dir / f"{STATION_ID}_readiness_fold_feature_missingness.csv", index=False)
display(readiness_summary)
display(readiness_fold_missingness.groupby(["fold", "retained"], as_index=False).agg(feature_count=("feature", "nunique")))
if not v20_ready:
    raise RuntimeError(
        "V20 readiness failed. Audit artifacts were written; rerun this notebook after peak-timing and "
        "Wunderground pulls reduce each station-year missing fraction to 3% or less."
    )

D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()

,station_id,year,expected_days,peak_ready_days,wunderground_target_days,peak_missing_fraction,target_missing_fraction,peak_ready,target_ready
0,KATL,2021,365,364,365,0.00274,0.000000,True,True
1,KATL,2022,365,365,364,0.00000,0.002740,True,True
2,KATL,2023,365,365,364,0.00000,0.002740,True,True
3,KATL,2024,366,366,365,0.00000,0.002732,True,True
4,KATL,2025,365,365,364,0.00000,0.002740,True,True
5,KATL,2026,182,182,181,0.00000,0.005495,True,True

                     fold  retained  feature_count
0  fold_2021_2022_to_2023     False              1
1  fold_2021_2022_to_2023      True             54
2  fold_2021_2023_to_2024     False              1
3  fold_2021_2023_to_2024      True             54
4  fold_2021_2024_to_2025     False              1
5  fold_2021_2024_to_2025      True             54
6       fold_2021_to_2022     False              1
7       fold_2021_to_2022      True             54
8    test_refit_2021_2025     False              1
9    test_refit_2021_2025      True             54

In [7]:
missing_packages = missing_model_dependencies()
if missing_packages:
    raise ImportError(
        "Missing station-stacking ML packages: "
        + ", ".join(missing_packages)
        + ". Install them with: python -m pip install -r requirements.txt"
    )

config = StationStackingConfig(
    station_id=STATION_ID,
    project_root=PROJECT_ROOT,
    timing_mode=TIMING_MODE,
    providers=PROVIDERS,
    fast_mode=FAST_MODE,
    optuna_trials=OPTUNA_TRIALS,
    stack_optuna_trials=STACK_OPTUNA_TRIALS,
    optuna_startup_trials=OPTUNA_STARTUP_TRIALS,
    stack_optuna_startup_trials=STACK_OPTUNA_STARTUP_TRIALS,
    optuna_metric=OPTUNA_METRIC,
    optuna_verbose=OPTUNA_VERBOSE,
    feature_version="v20_peak_timing",
    training_profile="v20_aligned",
    target_mode="remaining_warmup",
    target_source="wunderground_only",
    max_feature_missing_fraction=0.03,
    base_model_methods=("xgboost", "lightgbm", "catboost"),
    stack_enabled=True,
    hyperparameter_space="wide",
    year_split_folds=V20_EXPANDING_FOLDS,
    year_split_validation_weights={2022: 1.0, 2023: 1.0, 2024: 1.0, 2025: 1.0},
    year_split_test_train_years=(2021, 2025),
    year_split_test_year=2026,
    output_dir=PROJECT_ROOT / "data" / "calibration" / "station_stacking_v20_peak_timing",
)

config.resolved_optuna_storage_path()

WindowsPath('D:/dev/weather-research/data/calibration/station_stacking_v20_peak_timing/KATL_optuna.sqlite3')

In [8]:
result = run_station_year_split_experiment(config)
result.scoreboard

D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3398: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3399: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
[I 2026-07-16 06:50:41,765] A new study created in RDB with name: KATL_v20_peak_timing_remaining_warmup_base_xgboost_mae_f_wide
[I 2026-07-16 06:50:56,088] Trial 0 finished with value: 1.8342955672319705 and parameters: {'n_estimators': 1342, 'learning_rate': 0.19043899115982607, 'max_depth': 9, 'min_child_weight': 2.481040974867813, 'gamma': 2.340279606636548, 'subsample': 0.4513964382185317, 'colsample_bytree': 0.3877543479093296, 'reg_alpha': 2.478071022662141, 'reg_lambda': 0.6132587025321562}. Best is trial 0 with value: 1.8342955672319705.
[I 2026-07-16 06:51:19,833] Trial 1 finished with value: 2.570399982721578 and parameters: {'n_estimators': 2493, 'learning_rate': 0.001120367191095075, 'max_depth': 12, 'min_child_weight': 21.368329072358772, 'gamma': 3.185086660174142, 'subsample': 0.4681862286846154, 'colsample_bytree': 0.46921293140473197, 'reg_alpha': 4.476173538513514e-07, 'reg_lambda': 0.20253776634919213}. Best is trial 0 with value: 1.8342955672319705.
[I 2026-07-16 06:51:25,198] Trial 2 finished with value: 1.486111550273742 and parameters: {'n_estimators': 1540, 'learning_rate': 0.004992867109217114, 'max_depth': 8, 'min_child_weight': 0.03613894271216528, 'gamma': 4.3821697280282725, 'subsample': 0.5881351981408995, 'colsample_bytree': 0.6464454897410734, 'reg_alpha': 0.26430874752361627, 'reg_lambda': 0.0018119678627933364}. Best is trial 2 with value: 1.486111550273742.
[I 2026-07-16 06:51:29,145] Trial 3 finished with value: 1.740504746558161 and parameters: {'n_estimators': 1824, 'learning_rate': 0.026337502897485255, 'max_depth': 1, 'min_child_weight': 2.69264691008618, 'gamma': 2.557861855309373, 'subsample': 0.39228353544043165, 'colsample_bytree': 0.9667755992146666, 'reg_alpha': 38.6887231523051, 'reg_lambda': 12.408975837016275}. Best is trial 2 with value: 1.486111550273742.
[I 2026-07-16 06:51:53,951] Trial 4 finished with value: 1.4790548366444338 and parameters: {'n_estimators': 1101, 'learning_rate': 0.0017147936629846843, 'max_depth': 9, 'min_child_weight': 0.5762487216478605, 'gamma': 1.8305735226716824, 'subsample': 0.6718649915723256, 'colsample_bytree': 0.37235253872489193, 'reg_alpha': 8.162906555194692, 'reg_lambda': 0.004271500153828077}. Best is trial 4 with value: 1.4790548366444338.
[I 2026-07-16 06:52:28,243] Trial 5 finished with value: 1.5595967372241124 and parameters: {'n_estimators': 2336, 'learning_rate': 0.00559067775661512, 'max_depth': 7, 'min_child_weight': 1.5375920235481764, 'gamma': 2.7728168328829055, 'subsample': 0.980230008046963, 'colsample_bytree': 0.8538363351847245, 'reg_alpha': 18.792618557420877, 'reg_lambda': 43.484449457612314}. Best is trial 4 with value: 1.4790548366444338.
[I 2026-07-16 06:52:34,869] Trial 6 finished with value: 1.372235623733672 and parameters: {'n_estimators': 2113, 'learning_rate': 0.16240489353272883, 'max_depth': 2, 'min_child_weight': 0.06080390190296603, 'gamma': 0.678409333658071, 'subsample': 0.5614647149961218, 'colsample_bytree': 0.6026402382981633, 'reg_alpha': 1.8037999945880162e-07, 'reg_lambda': 16.668629892722056}. Best is trial 6 with value: 1.372235623733672.
[I 2026-07-16 06:52:52,433] Trial 7 finished with value: 1.4501354749650235 and parameters: {'n_estimators': 1281, 'learning_rate': 0.0047169807141865345, 'max_depth': 7, 'min_child_weight': 0.0366181922039243, 'gamma': 12.032954711310595, 'subsample': 0.398457918391851, 'colsample_bytree': 0.9914765087903362, 'reg_alpha': 0.18490013641000916, 'reg_lambda': 0.0017869543989965139}. Best is trial 6 with value: 1.372235623733672.
[I 2026-07-16 06:52:53,224] Trial 8 pruned.
[I 2026-07-16 06:53:05,645] Trial 9 finished with value: 1.3922005214171285 and parameters: {'n_estimators': 2201, 'learning_rate': 0.006215464818952927, 'max_depth': 1, 'min_child_weight': 0.17535949529764422, 'gamma': 4.877749830401205, 'subsample': 0.8242440159197416, 'colsample_bytree': 0.7644123563808884, 'reg_alpha': 4.4315220126915325, 'reg_lambda': 0.09450187118503514}. Best is trial 6 with value: 1.372235623733672.
[I 2026-07-16 06:53:06,759] Trial 10 pruned.
[I 2026-07-16 06:53:08,950] Trial 11 pruned.
[I 2026-07-16 06:53:11,478] Trial 12 pruned.
[I 2026-07-16 06:53:12,022] Trial 13 pruned.
[I 2026-07-16 06:53:12,892] Trial 14 pruned.
[I 2026-07-16 06:53:16,100] Trial 15 finished with value: 1.3818020915707743 and parameters: {'n_estimators': 3311, 'learning_rate': 0.021882197214300323, 'max_depth': 3, 'min_child_weight': 0.011927859366875052, 'gamma': 0.14583408410588616, 'subsample': 0.7986605978199443, 'colsample_bytree': 0.7925816793363801, 'reg_alpha': 0.000682381751719726, 'reg_lambda': 0.8912768993161009}. Best is trial 6 with value: 1.372235623733672.
[I 2026-07-16 06:53:20,152] Trial 16 finished with value: 1.3540025679309502 and parameters: {'n_estimators': 3489, 'learning_rate': 0.016923377887394654, 'max_depth': 4, 'min_child_weight': 0.012617266144018207, 'gamma': 0.4214460473461219, 'subsample': 0.785824078413485, 'colsample_bytree': 0.8628314771242156, 'reg_alpha': 0.0007576903076688566, 'reg_lambda': 1.1625216460944126}. Best is trial 16 with value: 1.3540025679309502.
[I 2026-07-16 06:53:23,793] Trial 17 finished with value: 1.3794702082709662 and parameters: {'n_estimators': 3322, 'learning_rate': 0.017478919982976338, 'max_depth': 4, 'min_child_weight': 0.010688271471270726, 'gamma': 0.29701791685388135, 'subsample': 0.7064097159787122, 'colsample_bytree': 0.888489887047579, 'reg_alpha': 0.0019137392018860786, 'reg_lambda': 1.465423547146301}. Best is trial 16 with value: 1.3540025679309502.
[I 2026-07-16 06:53:24,331] Trial 18 pruned.
[I 2026-07-16 06:53:25,027] Trial 19 pruned.
[I 2026-07-16 06:53:25,667] Trial 20 pruned.
[I 2026-07-16 06:53:29,849] Trial 21 finished with value: 1.3378812557910895 and parameters: {'n_estimators': 3457, 'learning_rate': 0.011675061477108947, 'max_depth': 3, 'min_child_weight': 0.010188094120211159, 'gamma': 0.932833550224981, 'subsample': 0.7250169630282906, 'colsample_bytree': 0.8670875635133621, 'reg_alpha': 0.003765706663136253, 'reg_lambda': 1.5843862197445957}. Best is trial 21 with value: 1.3378812557910895.
[I 2026-07-16 06:53:32,648] Trial 22 finished with value: 1.3618046685535945 and parameters: {'n_estimators': 3473, 'learning_rate': 0.011165768124789038, 'max_depth': 2, 'min_child_weight': 0.01796933469777027, 'gamma': 0.9202341540138144, 'subsample': 0.7731557411827529, 'colsample_bytree': 0.8203987260907537, 'reg_alpha': 0.014502948066413439, 'reg_lambda': 0.3225801343480424}. Best is trial 21 with value: 1.3378812557910895.
[I 2026-07-16 06:53:35,611] Trial 23 finished with value: 1.3550877091840698 and parameters: {'n_estimators': 3498, 'learning_rate': 0.010846836612757921, 'max_depth': 3, 'min_child_weight': 0.01893010985364837, 'gamma': 4.095151794646876, 'subsample': 0.7575381616726636, 'colsample_bytree': 0.8266990066575907, 'reg_alpha': 0.007378452134199125, 'reg_lambda': 0.3563011041466923}. Best is trial 21 with value: 1.3378812557910895.
[I 2026-07-16 06:53:40,030] Trial 24 pruned.
[I 2026-07-16 06:53:40,907] Trial 25 pruned.
[I 2026-07-16 06:53:41,614] Trial 26 pruned.
[I 2026-07-16 06:53:42,534] Trial 27 pruned.
[I 2026-07-16 06:53:43,240] Trial 28 pruned.
[I 2026-07-16 06:53:47,372] Trial 29 finished with value: 1.3563510193283612 and parameters: {'n_estimators': 2626, 'learning_rate': 0.007579323369918836, 'max_depth': 3, 'min_child_weight': 0.024982321872509133, 'gamma': 3.4147647178310025, 'subsample': 0.795215232760302, 'colsample_bytree': 0.8874502508679829, 'reg_alpha': 0.003234584280135283, 'reg_lambda': 0.44780682566954066}. Best is trial 21 with value: 1.3378812557910895.
[I 2026-07-16 06:53:47,459] A new study created in RDB with name: KATL_v20_peak_timing_remaining_warmup_base_lightgbm_mae_f_wide
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 06:53:50,360] Trial 0 finished with value: 1.49501954060343 and parameters: {'n_estimators': 447, 'learning_rate': 0.028873871707375695, 'num_leaves': 71, 'max_depth': 5, 'min_child_samples': 83, 'min_split_gain': 4.295687454742988, 'bagging_fraction': 0.7829586385137167, 'bagging_freq': 4, 'feature_fraction': 0.3688589858758342, 'lambda_l1': 0.06382334403151436, 'lambda_l2': 0.03080292177315921, 'huber_alpha': 0.95}. Best is trial 0 with value: 1.49501954060343.
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
d:\dev\weather-research\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

                  period           method  count     mae_f    rmse_f
0   validation_2024_2025          xgboost   1456  1.409440  1.889919
1   validation_2024_2025         lightgbm   1456  1.324776  1.766115
2   validation_2024_2025         catboost   1456  1.355495  1.808609
3   validation_2024_2025    provider_mean   1456  2.301108  3.339441
4   validation_2024_2025  provider_median   1456  2.143877  3.140707
5   validation_2024_2025          nbm_raw   1456  2.071742  2.972272
6   validation_2024_2025         hrrr_raw   1456  3.100582  4.604907
7   validation_2024_2025          gfs_raw   1456  3.079775  4.204256
8              test_2026          xgboost    171  1.255431  1.721004
9              test_2026         lightgbm    171  1.234041  1.716806
10             test_2026         catboost    171  1.257884  1.715835
11             test_2026      ridge_stack    171  1.227391  1.699855
12             test_2026    provider_mean    171  2.145562  3.337353
13             test_2026  provider_median    171  2.126776  3.276249
14             test_2026          nbm_raw    171  2.088445  3.229287
15             test_2026         hrrr_raw    171  2.539610  3.830303
16             test_2026          gfs_raw    171  2.838918  3.971651

In [9]:
if EXPORT_MODEL_WEIGHTS:
    exported_weights = export_station_model_weights(
        project_root=PROJECT_ROOT,
        station_id=STATION_ID,
        artifact_dir=config.resolved_output_dir(),
        model_version=MODEL_VERSION,
        timing_mode=config.timing_mode,
        providers=tuple(config.providers),
        feature_version=config.effective_feature_version,
        training_profile=config.effective_training_profile,
        optuna_metric=config.effective_optuna_metric,
        target_mode=config.effective_target_mode,
        target_source=config.effective_target_source,
        base_model_methods=tuple(config.effective_base_model_methods),
        stack_enabled=config.stack_enabled,
        source_pipeline="notebooks/station_stacking_v20_peak_timing",
    )

    exported_weights.bundle_path, exported_weights.manifest_path
else:
    print("Model export disabled for this experimental notebook.")

Model export disabled for this experimental notebook.

## V11 Feature Coverage

In [10]:
v11_feature_coverage = (
    result.features[V11_FEATURE_COLUMNS]
    .notna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .rename("coverage_pct")
    .reset_index()
    .rename(columns={"index": "feature"})
)

v11_feature_coverage

                                              feature  coverage_pct
0                              v4_observed_precip_any    100.000000
1                        v4_forecast_wet_observed_dry    100.000000
2                   v4_forecast_observed_precip_match    100.000000
3                              v4_all_forecast_precip    100.000000
4                              v4_any_forecast_precip    100.000000
5                          climatology_high_10y_std_f    100.000000
6                              climatology_high_10y_f    100.000000
7                          climatology_high_10y_count    100.000000
8                     v8_month_remaining_warmup_count    100.000000
9                        v4_observed_wet_forecast_dry    100.000000
10              v8_recent_remaining_warmup_30d_mean_f     99.752598
11                          v2_recent_heat_momentum_f     99.653637
12                           v2_recent_heat_anomaly_f     99.109352
13               v8_recent_remaining_warmup_7d_mean_f     99.059871
14                     v3_high_so_far_above_current_f     98.911430
15              observed_temp_minus_climatology_10y_f     98.911430
16       v8_provider_max_remaining_from_high_so_far_f     98.911430
17              provider_mean_minus_climatology_10y_f     98.911430
18       v8_provider_min_remaining_from_high_so_far_f     98.911430
19                   v3_remaining_warmup_per_spread_f     98.911430
20           v3_humidity_remaining_warmup_interaction     98.911430
21             v3_remaining_warmup_from_high_so_far_f     98.911430
22       observed_high_so_far_minus_climatology_10y_f     98.911430
23                   v2_morning_warmup_to_consensus_f     98.911430
24                     v2_humidity_warmup_interaction     98.911430
25                             v2_spread_per_warmup_f     98.911430
26          v8_provider_spread_per_remaining_warmup_f     98.911430
27    v8_provider_median_remaining_from_high_so_far_f     98.911430
28                   v4_observed_precip_recent_mm_est     98.861950
29                   v8_month_remaining_warmup_mean_f     98.812469
30            observed_morning_warmup_rate_f_per_hour     98.812469
31            observed_high_so_far_change_since_9am_f     98.812469
32                     observed_temp_change_last_1h_f     98.812469
33                     observed_temp_change_last_3h_f     98.812469
34                     v2_consensus_minus_7d_actual_f     98.812469
35                   v3_high_so_far_minus_7d_actual_f     98.812469
36                      v3_high_so_far_minus_lag_1d_f     98.565067
37       v8_provider_mean_remaining_vs_month_normal_f     97.723899
38      v8_dewpoint_mean_remaining_warmup_interaction     77.981197
39  v8_dewpoint_depression_remaining_warmup_intera...     77.981197
40                        v8_forecast_dewpoint_mean_f     77.981197
41             v8_forecast_dewpoint_depression_mean_f     77.981197
42             v4_precip_remaining_warmup_interaction     77.634834
43                   v4_forecast_precip_intensity_max     77.634834
44                   v4_forecast_precip_total_mean_mm     77.634834
45                    v4_forecast_precip_total_max_mm     77.634834
46                 v4_forecast_precip_total_spread_mm     77.634834
47                  v4_forecast_precip_max_1h_mean_mm     77.634834
48                      v4_forecast_precip_hours_mean     77.634834
49                  v4_forecast_precip_intensity_mean     77.634834
50       v8_precip_total_remaining_warmup_interaction     77.634834
51                     v4_precip_humidity_interaction     77.634834
52      v8_precip_max_1h_remaining_warmup_interaction     77.634834
53         v4_forecast_total_minus_observed_recent_mm     77.585354
54    v8_cloud_cover_max_remaining_warmup_interaction     65.314201
55   v8_cloud_cover_mean_remaining_warmup_interaction     65.314201
56    v8_wind_speed_mean_remaining_warmup_interaction     30.677882
57      v8_wind_gust_max_remaining_warmup_interaction     30.677882

In [11]:
result.feature_columns.loc[result.feature_columns["feature"].isin(V11_FEATURE_COLUMNS)]

                                               feature     kind
3                       observed_temp_change_last_1h_f  numeric
4                       observed_temp_change_last_3h_f  numeric
5              observed_morning_warmup_rate_f_per_hour  numeric
6              observed_high_so_far_change_since_9am_f  numeric
32                            v2_recent_heat_anomaly_f  numeric
33                           v2_recent_heat_momentum_f  numeric
34                    v2_morning_warmup_to_consensus_f  numeric
35                      v2_consensus_minus_7d_actual_f  numeric
36                              v2_spread_per_warmup_f  numeric
37                      v2_humidity_warmup_interaction  numeric
38                      v3_high_so_far_above_current_f  numeric
39              v3_remaining_warmup_from_high_so_far_f  numeric
40                       v3_high_so_far_minus_lag_1d_f  numeric
41                    v3_high_so_far_minus_7d_actual_f  numeric
42                    v3_remaining_warmup_per_spread_f  numeric
43            v3_humidity_remaining_warmup_interaction  numeric
44                    v4_forecast_precip_total_mean_mm  numeric
45                     v4_forecast_precip_total_max_mm  numeric
46                  v4_forecast_precip_total_spread_mm  numeric
47                   v4_forecast_precip_max_1h_mean_mm  numeric
48                       v4_forecast_precip_hours_mean  numeric
49                   v4_forecast_precip_intensity_mean  numeric
50                    v4_forecast_precip_intensity_max  numeric
51                              v4_any_forecast_precip  numeric
52                              v4_all_forecast_precip  numeric
53                              v4_observed_precip_any  numeric
54                    v4_observed_precip_recent_mm_est  numeric
55          v4_forecast_total_minus_observed_recent_mm  numeric
56                   v4_forecast_observed_precip_match  numeric
57                        v4_forecast_wet_observed_dry  numeric
58                        v4_observed_wet_forecast_dry  numeric
59                      v4_precip_humidity_interaction  numeric
60              v4_precip_remaining_warmup_interaction  numeric
61        v8_provider_max_remaining_from_high_so_far_f  numeric
62        v8_provider_min_remaining_from_high_so_far_f  numeric
63     v8_provider_median_remaining_from_high_so_far_f  numeric
64           v8_provider_spread_per_remaining_warmup_f  numeric
65                    v8_month_remaining_warmup_mean_f  numeric
66                     v8_month_remaining_warmup_count  numeric
67                v8_recent_remaining_warmup_7d_mean_f  numeric
68               v8_recent_remaining_warmup_30d_mean_f  numeric
69        v8_provider_mean_remaining_vs_month_normal_f  numeric
70    v8_cloud_cover_mean_remaining_warmup_interaction  numeric
71     v8_cloud_cover_max_remaining_warmup_interaction  numeric
72        v8_precip_total_remaining_warmup_interaction  numeric
73       v8_precip_max_1h_remaining_warmup_interaction  numeric
74     v8_wind_speed_mean_remaining_warmup_interaction  numeric
75       v8_wind_gust_max_remaining_warmup_interaction  numeric
76                         v8_forecast_dewpoint_mean_f  numeric
77              v8_forecast_dewpoint_depression_mean_f  numeric
78       v8_dewpoint_mean_remaining_warmup_interaction  numeric
79   v8_dewpoint_depression_remaining_warmup_intera...  numeric
110                             climatology_high_10y_f  numeric
111                         climatology_high_10y_std_f  numeric
112                         climatology_high_10y_count  numeric
113              provider_mean_minus_climatology_10y_f  numeric
114              observed_temp_minus_climatology_10y_f  numeric
115       observed_high_so_far_minus_climatology_10y_f  numeric

## Dropped Feature Check

In [12]:
dropped_present = result.feature_columns.loc[
    result.feature_columns["feature"].isin(V11_DROPPED_FEATURE_COLUMNS)
]

dropped_present

Empty DataFrame
Columns: [feature, kind]
Index: []

## Morning Trend Coverage

In [13]:
trend_coverage = (
    result.features[TREND_COLUMNS]
    .notna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .rename("coverage_pct")
    .reset_index()
    .rename(columns={"index": "feature"})
)

trend_coverage

                                   feature  coverage_pct
0           observed_temp_change_last_1h_f     98.812469
1           observed_temp_change_last_3h_f     98.812469
2  observed_morning_warmup_rate_f_per_hour     98.812469
3  observed_high_so_far_change_since_9am_f     98.812469

## Rounded Within 1F Accuracy

In [14]:
preds = pd.concat(
    [
        result.validation_predictions.assign(period="validation_2024_2025"),
        result.test_predictions.assign(period="oof_2026"),
    ],
    ignore_index=True,
)

predicted_high = pd.to_numeric(preds["predicted_high_f"], errors="coerce")
preds["predicted_high_rounded_f"] = np.floor(predicted_high + 0.5)
preds["within_1f_after_round"] = (
    pd.to_numeric(preds["actual_high_f"], errors="coerce") - preds["predicted_high_rounded_f"]
).abs().le(1)

within_1f_accuracy_by_period = (
    preds
    .dropna(subset=["actual_high_f", "predicted_high_rounded_f"])
    .groupby(["period", "method"], as_index=False)
    .agg(
        count=("within_1f_after_round", "size"),
        within_1f_count=("within_1f_after_round", "sum"),
        within_1f_accuracy_pct=("within_1f_after_round", lambda x: x.mean() * 100),
    )
    .sort_values(["period", "within_1f_accuracy_pct"], ascending=[True, False])
)

within_1f_accuracy_by_period

,period,method,count,within_1f_count,within_1f_accuracy_pct
7,oof_2026,ridge_stack,171,121,70.760234
8,oof_2026,xgboost,171,120,70.175439
3,oof_2026,lightgbm,171,117,68.421053
0,oof_2026,catboost,171,115,67.251462
4,oof_2026,nbm_raw,171,91,53.216374
6,oof_2026,provider_median,171,84,49.122807
5,oof_2026,provider_mean,171,78,45.614035
2,oof_2026,hrrr_raw,171,71,41.520468
1,oof_2026,gfs_raw,171,59,34.502924
12,validation_2024_2025,lightgbm,1456,962,66.071429
9,validation_2024_2025,catboost,1456,947,65.041209
16,validation_2024_2025,xgboost,1456,914,62.774725
13,validation_2024_2025,nbm_raw,1456,678,46.565934
15,validation_2024_2025,provider_median,1456,667,45.810440
14,validation_2024_2025,provider_mean,1456,645,44.299451
11,validation_2024_2025,hrrr_raw,1456,531,36.469780
10,validation_2024_2025,gfs_raw,1456,452,31.043956

## Version Comparison

In [15]:
comparison_frames = []
for version, folder in [
    ("v1", PROJECT_ROOT / "data" / "calibration" / "station_stacking"),
    ("v2", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v2"),
    ("v3", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v3"),
    ("v4", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v4"),
    ("v5", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v5"),
    ("v6", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v6"),
    ("v7", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v7"),
    ("v8", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v8"),
    ("v9", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v9"),
    ("v10", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v10"),
    ("v11", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v11"),
]:
    path = folder / f"{STATION_ID}_year_split_scoreboard.csv"
    if path.exists():
        frame = pd.read_csv(path)
        frame["version"] = version
        comparison_frames.append(frame)

version_comparison = pd.concat(comparison_frames, ignore_index=True) if comparison_frames else pd.DataFrame()
if not version_comparison.empty:
    version_comparison = version_comparison.sort_values(["period", "mae_f", "version", "method"]).reset_index(drop=True)
version_comparison

                   period       method  count     mae_f    rmse_f version
0               test_2026     lightgbm    137  1.529121  2.224566     v11
1               test_2026  ridge_stack    137  1.531900  2.209782     v11
2               test_2026     lightgbm    125  1.547989  2.093915      v5
3               test_2026  ridge_stack    125  1.566708  2.118374      v5
4               test_2026      xgboost    125  1.569277  2.117086      v5
..                    ...          ...    ...       ...       ...     ...
111  validation_2024_2025      gfs_raw    541  3.557627  5.060559      v1
112  validation_2024_2025     hrrr_raw    664  3.630969  5.083107      v2
113  validation_2024_2025     hrrr_raw    664  3.630969  5.083107      v3
114  validation_2024_2025     hrrr_raw    664  3.630969  5.083107      v4
115  validation_2024_2025     hrrr_raw    541  4.010898  5.487445      v1

[116 rows x 6 columns]

## 2026 OOF Weather Brackets

In [16]:
result.bracket_metrics

,method,count,mae_f,rmse_f,bucket_log_loss,bracket_accuracy_pct,p95_absolute_error_f,large_miss_5f_pct
0,xgboost,171,1.255431,1.721004,1.326794,45.02924,3.428870,1.754386
1,lightgbm,171,1.234041,1.716806,1.324102,44.444444,3.421899,1.754386
2,catboost,171,1.257884,1.715835,1.340251,43.274854,3.363072,1.754386
3,ridge_stack,171,1.227391,1.699855,1.318320,46.783626,3.282840,1.754386
4,provider_mean,171,2.145562,3.337353,1.877072,34.502924,5.357125,6.432749
5,provider_median,171,2.126776,3.276249,1.874809,33.918129,5.905997,7.017544
6,nbm_raw,171,2.088445,3.229287,1.869976,35.672515,5.905997,7.602339
7,hrrr_raw,171,2.539610,3.830303,1.975896,29.824561,7.038774,12.280702
8,gfs_raw,171,2.838918,3.971651,2.083263,21.637427,7.412432,12.865497

## Train-Fold 3% Missingness Audit

In [17]:
modeling_frame, candidate_categorical, candidate_numeric = _modeling_frame(result.features, config)
candidate_features = [*candidate_categorical, *candidate_numeric]
audit_specs = [
    (fold.name, fold.train_start_year, fold.train_end_year)
    for fold in V20_EXPANDING_FOLDS
] + [("test_refit_2021_2025", 2021, 2025)]

missingness_rows = []
years = pd.to_numeric(modeling_frame["year"], errors="coerce")
for fold_name, train_start, train_end in audit_specs:
    train = modeling_frame.loc[years.between(train_start, train_end)].copy()
    retained_categorical, retained_numeric = _fit_feature_columns(
        train,
        candidate_categorical,
        candidate_numeric,
        max_missing_fraction=config.effective_max_feature_missing_fraction,
    )
    retained = set(retained_categorical) | set(retained_numeric)
    for feature in candidate_features:
        numeric_feature = feature in candidate_numeric
        values = pd.to_numeric(train[feature], errors="coerce") if numeric_feature else train[feature]
        missingness_rows.append(
            {
                "fold": fold_name,
                "train_start_year": train_start,
                "train_end_year": train_end,
                "feature": feature,
                "kind": "numeric" if numeric_feature else "categorical",
                "missing_fraction": float(values.isna().mean()),
                "retained": feature in retained,
            }
        )

fold_feature_missingness = pd.DataFrame(missingness_rows)
retained_dropped_summary = (
    fold_feature_missingness.groupby(["fold", "retained"], as_index=False)
    .agg(feature_count=("feature", "nunique"), maximum_missing_fraction=("missing_fraction", "max"))
)
fold_feature_missingness.to_csv(config.resolved_output_dir() / f"{STATION_ID}_fold_feature_missingness.csv", index=False)
retained_dropped_summary, fold_feature_missingness.loc[~fold_feature_missingness["retained"]].sort_values(
    ["fold", "missing_fraction"], ascending=[True, False]
)

(                     fold  retained  feature_count  maximum_missing_fraction
 0  fold_2021_2022_to_2023     False             24                  0.898352
 1  fold_2021_2022_to_2023      True             92                  0.006868
 2  fold_2021_2023_to_2024     False             22                  0.890009
 3  fold_2021_2023_to_2024      True             94                  0.021998
 4  fold_2021_2024_to_2025     False             22                  0.892857
 5  fold_2021_2024_to_2025      True             94                  0.016484
 6       fold_2021_to_2022     False             24                  0.898352
 7       fold_2021_to_2022      True             92                  0.013736
 8    test_refit_2021_2025     False             22                  0.895604
 9    test_refit_2021_2025      True             94                  0.013187,
                        fold  train_start_year  train_end_year  \
 117  fold_2021_2022_to_2023              2021            2022
 190  fold_2021_2022_to_2023              2021            2022
 191  fold_2021_2022_to_2023              2021            2022
 186  fold_2021_2022_to_2023              2021            2022
 187  fold_2021_2022_to_2023              2021            2022
 ..                      ...               ...             ...
 540    test_refit_2021_2025              2021            2025
 541    test_refit_2021_2025              2021            2025
 542    test_refit_2021_2025              2021            2025
 543    test_refit_2021_2025              2021            2025
 476    test_refit_2021_2025              2021            2025

                                                feature         kind  \
 117                     observed_weather_code_at_as_of  categorical
 190    v8_wind_speed_mean_remaining_warmup_interaction      numeric
 191      v8_wind_gust_max_remaining_warmup_interaction      numeric
 186   v8_cloud_cover_mean_remaining_warmup_interaction      numeric
 187    v8_cloud_cover_max_remaining_warmup_interaction      numeric
 ..                                                 ...          ...
 540                        v8_forecast_dewpoint_mean_f      numeric
 541             v8_forecast_dewpoint_depression_mean_f      numeric
 542      v8_dewpoint_mean_remaining_warmup_interaction      numeric
 543  v8_dewpoint_depression_remaining_warmup_intera...      numeric
 476                       nbm_cooling_onset_hour_local      numeric

      missing_fraction  retained
 117          0.898352     False
 190          0.462912     False
 191          0.462912     False
 186          0.285714     False
 187          0.285714     False
 ..                ...       ...
 540          0.137912     False
 541          0.137912     False
 542          0.137912     False
 543          0.137912     False
 476          0.101648     False

 [114 rows x 7 columns])

## Expanded 11 AM Feature Coverage and Provider Count

In [18]:
new_feature_coverage = (
    result.features[V11_SETTLEMENT_FIX_TEMP_FEATURE_COLUMNS]
    .notna()
    .mean()
    .mul(100)
    .rename("coverage_pct")
    .reset_index()
    .rename(columns={"index": "feature"})
)
provider_count_coverage = (
    result.features["v11sf_forecast_temp_11am_provider_count"]
    .value_counts(dropna=False)
    .sort_index()
    .rename_axis("available_provider_count")
    .reset_index(name="row_count")
)
provider_count_coverage["row_pct"] = provider_count_coverage["row_count"] / len(result.features) * 100
new_feature_coverage.to_csv(config.resolved_output_dir() / f"{STATION_ID}_11am_feature_coverage.csv", index=False)
new_feature_coverage, provider_count_coverage

(                                              feature  coverage_pct
 0                     v11sf_forecast_temp_11am_mean_f      98.91143
 1                   v11sf_forecast_temp_11am_median_f      98.91143
 2           v11sf_forecast_temp_11am_minus_observed_f      98.91143
 3                v11sf_forecast_temp_11am_abs_error_f      98.91143
 4               v11sf_forecast_temp_11am_warm_error_f      98.91143
 5               v11sf_forecast_temp_11am_cool_error_f      98.91143
 6                   v11sf_forecast_temp_11am_spread_f      98.91143
 7             v11sf_forecast_temp_11am_provider_count     100.00000
 8   v11sf_forecast_temp_bias_remaining_warmup_inte...      98.91143
 9          v11sf_observation_adjusted_provider_high_f      98.91143
 10                 v11sf_forecast_warmup_after_11am_f      98.91143,
    available_provider_count  row_count    row_pct
 0                         0         22   1.088570
 1                         1         70   3.463632
 2                         2        481  23.800099
 3                         3       1448  71.647699)

## New-Feature Importance

In [19]:
new_feature_importance = result.feature_importance.loc[
    result.feature_importance["feature"].isin(V11_SETTLEMENT_FIX_TEMP_FEATURE_COLUMNS)
].sort_values(["method", "importance_mean_mae_f"], ascending=[True, False])
new_feature_importance

,method,param_key,feature,importance_mean_mae_f,importance_std_mae_f,n_repeats,train_start_year,train_end_year,test_year,train_rows,test_rows
78,catboost,trial_27,v11sf_forecast_temp_bias_remaining_warmup_inte...,0.006658,0.002734,10,2021,2025,2026,1820,171
97,catboost,trial_27,v11sf_forecast_warmup_after_11am_f,0.004572,0.011833,10,2021,2025,2026,1820,171
106,catboost,trial_27,v11sf_forecast_temp_11am_warm_error_f,0.003948,0.001109,10,2021,2025,2026,1820,171
108,catboost,trial_27,v11sf_forecast_temp_11am_minus_observed_f,0.003886,0.002122,10,2021,2025,2026,1820,171
119,catboost,trial_27,v11sf_forecast_temp_11am_abs_error_f,0.002994,0.001548,10,2021,2025,2026,1820,171
121,catboost,trial_27,v11sf_forecast_temp_11am_mean_f,0.002811,0.002732,10,2021,2025,2026,1820,171
133,catboost,trial_27,v11sf_observation_adjusted_provider_high_f,0.002120,0.001812,10,2021,2025,2026,1820,171
158,catboost,trial_27,v11sf_forecast_temp_11am_cool_error_f,0.000760,0.001538,10,2021,2025,2026,1820,171
161,catboost,trial_27,v11sf_forecast_temp_11am_spread_f,0.000702,0.002069,10,2021,2025,2026,1820,171
192,catboost,trial_27,v11sf_forecast_temp_11am_provider_count,0.000000,0.000000,10,2021,2025,2026,1820,171
219,catboost,trial_27,v11sf_forecast_temp_11am_median_f,-0.000223,0.002882,10,2021,2025,2026,1820,171
76,lightgbm,trial_26,v11sf_observation_adjusted_provider_high_f,0.007176,0.006041,10,2021,2025,2026,1820,171
131,lightgbm,trial_26,v11sf_forecast_temp_11am_spread_f,0.002318,0.001790,10,2021,2025,2026,1820,171
180,lightgbm,trial_26,v11sf_forecast_temp_11am_warm_error_f,0.000110,0.001386,10,2021,2025,2026,1820,171
182,lightgbm,trial_26,v11sf_forecast_temp_11am_abs_error_f,0.000082,0.000771,10,2021,2025,2026,1820,171
199,lightgbm,trial_26,v11sf_forecast_temp_11am_provider_count,0.000000,0.000000,10,2021,2025,2026,1820,171
239,lightgbm,trial_26,v11sf_forecast_warmup_after_11am_f,-0.000859,0.003229,10,2021,2025,2026,1820,171
242,lightgbm,trial_26,v11sf_forecast_temp_bias_remaining_warmup_inte...,-0.000961,0.001962,10,2021,2025,2026,1820,171
247,lightgbm,trial_26,v11sf_forecast_temp_11am_median_f,-0.001123,0.001663,10,2021,2025,2026,1820,171
264,lightgbm,trial_26,v11sf_forecast_temp_11am_mean_f,-0.002959,0.004702,10,2021,2025,2026,1820,171
269,lightgbm,trial_26,v11sf_forecast_temp_11am_cool_error_f,-0.003946,0.001654,10,2021,2025,2026,1820,171
270,lightgbm,trial_26,v11sf_forecast_temp_11am_minus_observed_f,-0.004067,0.001258,10,2021,2025,2026,1820,171
40,xgboost,trial_21,v11sf_forecast_warmup_after_11am_f,0.021279,0.009558,10,2021,2025,2026,1820,171
50,xgboost,trial_21,v11sf_forecast_temp_11am_mean_f,0.014673,0.009698,10,2021,2025,2026,1820,171
81,xgboost,trial_21,v11sf_observation_adjusted_provider_high_f,0.006308,0.004253,10,2021,2025,2026,1820,171
98,xgboost,trial_21,v11sf_forecast_temp_bias_remaining_warmup_inte...,0.004571,0.005542,10,2021,2025,2026,1820,171
102,xgboost,trial_21,v11sf_forecast_temp_11am_spread_f,0.004401,0.005854,10,2021,2025,2026,1820,171
140,xgboost,trial_21,v11sf_forecast_temp_11am_abs_error_f,0.001878,0.004357,10,2021,2025,2026,1820,171
145,xgboost,trial_21,v11sf_forecast_temp_11am_warm_error_f,0.001693,0.001540,10,2021,2025,2026,1820,171
206,xgboost,trial_21,v11sf_forecast_temp_11am_provider_count,0.000000,0.000000,10,2021,2025,2026,1820,171
256,xgboost,trial_21,v11sf_forecast_temp_11am_median_f,-0.001938,0.002647,10,2021,2025,2026,1820,171
263,xgboost,trial_21,v11sf_forecast_temp_11am_cool_error_f,-0.002823,0.001494,10,2021,2025,2026,1820,171
272,xgboost,trial_21,v11sf_forecast_temp_11am_minus_observed_f,-0.004182,0.003911,10,2021,2025,2026,1820,171

## 2026 Monthly Metrics

In [20]:
monthly_predictions = result.test_predictions.copy()
monthly_predictions["month"] = pd.to_datetime(monthly_predictions["contract_date"], errors="coerce").dt.month
monthly_metrics = (
    monthly_predictions.dropna(subset=["month", "error_f"])
    .groupby(["method", "month"], as_index=False)
    .agg(
        count=("error_f", "size"),
        mae_f=("absolute_error_f", "mean"),
        rmse_f=("error_f", lambda values: float(np.sqrt(np.mean(np.square(values))))),
        bias_f=("error_f", "mean"),
    )
)
monthly_metrics.to_csv(config.resolved_output_dir() / f"{STATION_ID}_2026_monthly_metrics.csv", index=False)
monthly_metrics

             method  month  count     mae_f    rmse_f    bias_f
0          catboost      1     31  1.203912  1.483021  0.017164
1          catboost      2     28  1.210628  1.482858  0.154812
2          catboost      3     30  1.056130  1.365085 -0.080902
3          catboost      4     30  1.502376  2.108195 -0.810535
4          catboost      5     31  1.611793  2.269823  0.254005
5          catboost      6     21  0.817071  1.085356 -0.263995
6           gfs_raw      1     31  2.802349  3.395373  2.287120
7           gfs_raw      2     28  3.106535  3.827184  2.926251
8           gfs_raw      3     30  3.179913  5.493333  1.720638
9           gfs_raw      4     30  2.083964  2.684767 -0.458210
10          gfs_raw      5     31  2.972875  4.284748  0.125921
11          gfs_raw      6     21  2.929702  3.374792 -0.787895
12         hrrr_raw      1     31  3.494071  4.362862  3.156491
13         hrrr_raw      2     28  2.948483  3.720507  2.591982
14         hrrr_raw      3     30  3.513291  6.221451  3.298985
15         hrrr_raw      4     30  1.596531  2.033190  0.426312
16         hrrr_raw      5     31  1.940415  2.386026  0.416380
17         hrrr_raw      6     21  1.426284  1.818308 -0.293204
18         lightgbm      1     31  1.093592  1.341838 -0.073640
19         lightgbm      2     28  1.306141  1.588907 -0.160232
20         lightgbm      3     30  0.971312  1.404264 -0.400493
21         lightgbm      4     30  1.486256  2.199131 -0.779086
22         lightgbm      5     31  1.495594  2.111542  0.039492
23         lightgbm      6     21  0.974157  1.291775 -0.444588
24          nbm_raw      1     31  2.180515  3.038042  1.081297
25          nbm_raw      2     28  1.715151  2.109162  0.788153
26          nbm_raw      3     30  2.487398  4.903424  1.435276
27          nbm_raw      4     30  1.644996  2.622550 -0.298198
28          nbm_raw      5     31  2.566518  3.251292  1.716066
29          nbm_raw      6     21  1.808095  2.362604  1.351907
30    provider_mean      1     31  2.589233  3.355926  2.174969
31    provider_mean      2     28  2.232730  2.731077  2.102128
32    provider_mean      3     30  2.783030  5.367904  2.151633
33    provider_mean      4     30  1.500126  2.213323 -0.110032
34    provider_mean      5     31  2.078011  2.884897  0.752789
35    provider_mean      6     21  1.485500  1.917500  0.090269
36  provider_median      1     31  2.574784  3.259286  2.078252
37  provider_median      2     28  2.048983  2.547111  1.627967
38  provider_median      3     30  2.600439  5.229928  1.798290
39  provider_median      4     30  1.599218  2.325429 -0.147469
40  provider_median      5     31  2.053530  2.753749  0.843780
41  provider_median      6     21  1.754273  2.253481  0.110384
42      ridge_stack      1     31  1.114983  1.364786  0.001084
43      ridge_stack      2     28  1.247213  1.521091 -0.048583
44      ridge_stack      3     30  0.967094  1.361190 -0.346261
45      ridge_stack      4     30  1.486231  2.168993 -0.860959
46      ridge_stack      5     31  1.520788  2.142755  0.031905
47      ridge_stack      6     21  0.935868  1.244513 -0.486146
48          xgboost      1     31  1.147438  1.457379 -0.105674
49          xgboost      2     28  1.253249  1.531401 -0.185710
50          xgboost      3     30  1.036700  1.377894 -0.349564
51          xgboost      4     30  1.550506  2.216710 -0.870951
52          xgboost      5     31  1.474959  2.075807  0.175996
53          xgboost      6     21  0.984633  1.327711 -0.379195

## Performance by Warm/Cool 11 AM Forecast Delta

In [21]:
delta_by_date = result.features[[
    "contract_date",
    "v11sf_forecast_temp_11am_minus_observed_f",
]].copy()
delta_predictions = result.test_predictions.merge(delta_by_date, on="contract_date", how="left")
delta_predictions["forecast_temp_delta_bucket"] = pd.cut(
    delta_predictions["v11sf_forecast_temp_11am_minus_observed_f"],
    bins=[-np.inf, -2.0, -0.5, 0.5, 2.0, np.inf],
    labels=["cool_gt_2f", "cool_0.5_to_2f", "near_match", "warm_0.5_to_2f", "warm_gt_2f"],
)
warm_cool_metrics = (
    delta_predictions.dropna(subset=["forecast_temp_delta_bucket", "error_f"])
    .groupby(["method", "forecast_temp_delta_bucket"], observed=True, as_index=False)
    .agg(count=("error_f", "size"), mae_f=("absolute_error_f", "mean"), bias_f=("error_f", "mean"))
)
warm_cool_metrics.to_csv(config.resolved_output_dir() / f"{STATION_ID}_warm_cool_delta_metrics.csv", index=False)
warm_cool_metrics

             method forecast_temp_delta_bucket  count     mae_f    bias_f
0          catboost                 cool_gt_2f     34  1.369930  0.211657
1          catboost             cool_0.5_to_2f     54  1.018878  0.013303
2          catboost                 near_match     39  1.233332 -0.516788
3          catboost             warm_0.5_to_2f     29  1.270417 -0.320360
4          catboost                 warm_gt_2f     15  1.903932  0.132296
5           gfs_raw                 cool_gt_2f     34  3.787576  3.739109
6           gfs_raw             cool_0.5_to_2f     54  2.832964  1.668038
7           gfs_raw                 near_match     39  2.583485 -0.293216
8           gfs_raw             warm_0.5_to_2f     29  2.390429 -0.388416
9           gfs_raw                 warm_gt_2f     15  2.241267 -1.095862
10         hrrr_raw                 cool_gt_2f     34  2.432849  2.111714
11         hrrr_raw             cool_0.5_to_2f     54  3.154325  2.716139
12         hrrr_raw                 near_match     39  2.125083  0.558169
13         hrrr_raw             warm_0.5_to_2f     29  1.968215  0.709184
14         hrrr_raw                 warm_gt_2f     15  2.751090  1.875427
15         lightgbm                 cool_gt_2f     34  1.454665  0.055383
16         lightgbm             cool_0.5_to_2f     54  0.879011 -0.111075
17         lightgbm                 near_match     39  1.312522 -0.735316
18         lightgbm             warm_0.5_to_2f     29  1.251044 -0.454719
19         lightgbm                 warm_gt_2f     15  1.775149 -0.285970
20          nbm_raw                 cool_gt_2f     34  2.626064  2.153714
21          nbm_raw             cool_0.5_to_2f     54  2.131965  1.855004
22          nbm_raw                 near_match     39  2.080922  0.426260
23          nbm_raw             warm_0.5_to_2f     29  1.399856 -0.119170
24          nbm_raw                 warm_gt_2f     15  2.064000 -1.018386
25    provider_mean                 cool_gt_2f     34  2.739123  2.668179
26    provider_mean             cool_0.5_to_2f     54  2.399033  2.079727
27    provider_mean                 near_match     39  1.837780  0.230404
28    provider_mean             warm_0.5_to_2f     29  1.558212  0.067199
29    provider_mean                 warm_gt_2f     15  1.823445 -0.079607
30  provider_median                 cool_gt_2f     34  2.593956  2.385629
31  provider_median             cool_0.5_to_2f     54  2.369134  1.959013
32  provider_median                 near_match     39  1.953370  0.147251
33  provider_median             warm_0.5_to_2f     29  1.398045  0.068064
34  provider_median                 warm_gt_2f     15  2.055086 -0.440399
35      ridge_stack                 cool_gt_2f     34  1.388499  0.059819
36      ridge_stack             cool_0.5_to_2f     54  0.915901 -0.097385
37      ridge_stack                 near_match     39  1.295979 -0.708851
38      ridge_stack             warm_0.5_to_2f     29  1.236961 -0.451128
39      ridge_stack                 warm_gt_2f     15  1.786747 -0.187367
40          xgboost                 cool_gt_2f     34  1.461905  0.105969
41          xgboost             cool_0.5_to_2f     54  0.902796 -0.061594
42          xgboost                 near_match     39  1.358384 -0.694198
43          xgboost             warm_0.5_to_2f     29  1.339716 -0.530378
44          xgboost                 warm_gt_2f     15  1.626284 -0.361376

## Common-Date Comparison with Existing V11 Settlement Fix

In [22]:
baseline_path = (
    PROJECT_ROOT
    / "data"
    / "calibration"
    / "station_stacking_v11_settlement_fix"
    / f"{STATION_ID}_year_split_test_predictions.csv"
)
baseline_predictions = pd.read_csv(baseline_path)
baseline_predictions["contract_date"] = baseline_predictions["contract_date"].astype(str).str[:10]
v20_predictions = result.test_predictions.copy()
v20_predictions["contract_date"] = v20_predictions["contract_date"].astype(str).str[:10]
comparison = baseline_predictions.merge(
    v20_predictions,
    on=["contract_date", "method"],
    suffixes=("_baseline", "_v20"),
)
comparison["baseline_abs_error_f"] = (
    pd.to_numeric(comparison["actual_high_f_baseline"], errors="coerce")
    - pd.to_numeric(comparison["predicted_high_f_baseline"], errors="coerce")
).abs()
comparison["v20_abs_error_f"] = (
    pd.to_numeric(comparison["actual_high_f_v20"], errors="coerce")
    - pd.to_numeric(comparison["predicted_high_f_v20"], errors="coerce")
).abs()
common_date_comparison = (
    comparison.groupby("method", as_index=False)
    .agg(
        common_date_count=("contract_date", "size"),
        baseline_mae_f=("baseline_abs_error_f", "mean"),
        v20_mae_f=("v20_abs_error_f", "mean"),
        v20_better_days=("v20_abs_error_f", lambda values: int((values < comparison.loc[values.index, "baseline_abs_error_f"]).sum())),
        baseline_better_days=("v20_abs_error_f", lambda values: int((values > comparison.loc[values.index, "baseline_abs_error_f"]).sum())),
    )
)
common_date_comparison["v20_delta_mae_f"] = common_date_comparison["v20_mae_f"] - common_date_comparison["baseline_mae_f"]
common_date_comparison.to_csv(config.resolved_output_dir() / f"{STATION_ID}_v11_common_date_comparison.csv", index=False)
common_date_comparison.sort_values("v20_delta_mae_f")

,method,common_date_count,baseline_mae_f,v20_mae_f,v20_better_days,baseline_better_days,v20_delta_mae_f
3,lightgbm,171,1.359759,1.234041,99,70,-0.125717
7,ridge_stack,171,1.326830,1.227391,97,74,-0.099439
0,catboost,171,1.352620,1.257884,99,70,-0.094737
8,xgboost,171,1.326999,1.255431,90,78,-0.071567
2,hrrr_raw,171,2.539610,2.539610,0,0,0.000000
4,nbm_raw,171,2.088445,2.088445,0,0,0.000000
5,provider_mean,171,2.145562,2.145562,3,2,0.000000
1,gfs_raw,171,2.838918,2.838918,0,0,0.000000
6,provider_median,171,2.126776,2.126776,0,0,0.000000

## V20 Peak-Timing Feature Coverage

In [23]:
v20_feature_columns = [*V20_PEAK_TIMING_RAW_FEATURE_COLUMNS, *V20_ENGINEERED_FEATURE_COLUMNS]
v20_feature_coverage = (
    result.features[v20_feature_columns]
    .notna().mean().mul(100)
    .rename("coverage_pct").reset_index().rename(columns={"index": "feature"})
)
v20_feature_coverage.to_csv(
    config.resolved_output_dir() / f"{STATION_ID}_v20_peak_feature_coverage.csv", index=False
)
v20_feature_coverage.sort_values("coverage_pct")

                                              feature  coverage_pct
5                        nbm_cooling_onset_hour_local     89.460663
30                v20_nbm_observation_adjusted_high_f     98.861950
26                       v20_nbm_t11_minus_observed_f     98.861950
25                      v20_hrrr_t11_minus_observed_f     98.911430
29               v20_hrrr_observation_adjusted_high_f     98.911430
31                           v20_adjusted_high_mean_f     98.911430
32                         v20_adjusted_high_spread_f     98.911430
2                               nbm_hour_of_max_local     99.950520
17               hrrr_precip_wet_hours_11_to_nbm_peak     99.950520
22                    hrrr_tcc_11_to_nbm_peak_max_pct     99.950520
16                hrrr_precip_total_11_to_nbm_peak_mm     99.950520
1                                    nbm_max_post11_f     99.950520
3                                   nbm_slope_11_14_f     99.950520
4                                   nbm_slope_14_17_f     99.950520
13             hrrr_solar_energy_11_to_nbm_peak_wh_m2     99.950520
0                                          nbm_t11l_f     99.950520
28                           v20_nbm_remaining_rise_f     99.950520
24                   hrrr_lcc_11_to_nbm_peak_mean_pct     99.950520
23                  hrrr_blcc_11_to_nbm_peak_mean_pct     99.950520
21                   hrrr_tcc_11_to_nbm_peak_mean_pct     99.950520
40                           v20_rain_before_nbm_peak     99.950520
34                           v20_peak_hour_difference     99.950520
33                        v20_model_high_difference_f     99.950520
15              hrrr_precip_wet_hours_11_to_hrrr_peak    100.000000
6                                         hrrr_t11l_f    100.000000
14               hrrr_precip_total_11_to_hrrr_peak_mm    100.000000
12            hrrr_solar_energy_11_to_hrrr_peak_wh_m2    100.000000
11                            hrrr_slope_14_to_peak_f    100.000000
9                             hrrr_peak_at_window_end    100.000000
10                                 hrrr_slope_11_14_f    100.000000
8                              hrrr_hour_of_max_local    100.000000
7                                   hrrr_max_post11_f    100.000000
27                          v20_hrrr_remaining_rise_f    100.000000
18                               hrrr_no_precip_11_18    100.000000
19                  hrrr_tcc_11_to_hrrr_peak_mean_pct    100.000000
20                   hrrr_tcc_11_to_hrrr_peak_max_pct    100.000000
36                       v20_solar_energy_15_18_wh_m2    100.000000
37                 v20_tcc_change_11_to_hrrr_peak_pct    100.000000
38                  v20_tcc_change_11_to_nbm_peak_pct    100.000000
35                       v20_solar_energy_11_14_wh_m2    100.000000
39                          v20_rain_before_hrrr_peak    100.000000
41                             v20_rain_present_11_18    100.000000
42  v20_precip_onset_minus_hrrr_peak_hours_zero_fi...    100.000000
43  v20_precip_onset_minus_nbm_peak_hours_zero_filled    100.000000

## Fold Metrics and Peak-Feature Importance

In [24]:
fold_metrics = (
    result.validation_predictions.groupby(["fold", "method"], as_index=False)
    .agg(count=("absolute_error_f", "size"), mae_f=("absolute_error_f", "mean"), bias_f=("error_f", "mean"))
)
peak_feature_importance = result.feature_importance.loc[
    result.feature_importance["feature"].isin(v20_feature_columns)
].sort_values(["method", "importance_mean_mae_f"], ascending=[True, False])
fold_metrics.to_csv(config.resolved_output_dir() / f"{STATION_ID}_fold_metrics.csv", index=False)
fold_metrics, peak_feature_importance

(                      fold           method  count     mae_f    bias_f
 0   fold_2021_2022_to_2023         catboost    363  1.452003 -0.454867
 1   fold_2021_2022_to_2023          gfs_raw    363  2.906738 -0.398481
 2   fold_2021_2022_to_2023         hrrr_raw    363  3.158485  1.943606
 3   fold_2021_2022_to_2023         lightgbm    363  1.451739 -0.393612
 4   fold_2021_2022_to_2023          nbm_raw    363  1.926042  1.063129
 5   fold_2021_2022_to_2023    provider_mean    363  2.153135  0.869418
 6   fold_2021_2022_to_2023  provider_median    363  1.939755  0.699834
 7   fold_2021_2022_to_2023          xgboost    363  1.493802 -0.501828
 8   fold_2021_2023_to_2024         catboost    365  1.226957  0.221697
 9   fold_2021_2023_to_2024          gfs_raw    365  2.692234  0.106500
 10  fold_2021_2023_to_2024         hrrr_raw    365  2.866136  1.852979
 11  fold_2021_2023_to_2024         lightgbm    365  1.202714  0.165045
 12  fold_2021_2023_to_2024          nbm_raw    365  1.837451  1.013816
 13  fold_2021_2023_to_2024    provider_mean    365  2.001632  0.991098
 14  fold_2021_2023_to_2024  provider_median    365  1.952282  0.965915
 15  fold_2021_2023_to_2024          xgboost    365  1.258181 -0.198682
 16  fold_2021_2024_to_2025         catboost    364  1.226961  0.044251
 17  fold_2021_2024_to_2025          gfs_raw    364  3.027659  0.416924
 18  fold_2021_2024_to_2025         hrrr_raw    364  2.714442  1.971796
 19  fold_2021_2024_to_2025         lightgbm    364  1.223358  0.025784
 20  fold_2021_2024_to_2025          nbm_raw    364  2.138055  1.140839
 21  fold_2021_2024_to_2025    provider_mean    364  2.204180  1.176520
 22  fold_2021_2024_to_2025  provider_median    364  2.092414  1.187500
 23  fold_2021_2024_to_2025          xgboost    364  1.235040 -0.107613
 24       fold_2021_to_2022         catboost    364  1.516678  0.640999
 25       fold_2021_to_2022          gfs_raw    364  3.693057  1.469031
 26       fold_2021_to_2022         hrrr_raw    364  3.664067  2.606990
 27       fold_2021_to_2022         lightgbm    364  1.421976  0.274438
 28       fold_2021_to_2022          nbm_raw    364  2.385661  1.753696
 29       fold_2021_to_2022    provider_mean    364  2.845900  1.943239
 30       fold_2021_to_2022  provider_median    364  2.591025  1.742637
 31       fold_2021_to_2022          xgboost    364  1.651383  0.979001,
        method param_key                             feature  \
 12   catboost  trial_27                   nbm_slope_11_14_f
 22   catboost  trial_27           v20_hrrr_remaining_rise_f
 24   catboost  trial_27    hrrr_tcc_11_to_nbm_peak_mean_pct
 31   catboost  trial_27   hrrr_tcc_11_to_hrrr_peak_mean_pct
 41   catboost  trial_27            v20_nbm_remaining_rise_f
 ..        ...       ...                                 ...
 259   xgboost  trial_21                         hrrr_t11l_f
 261   xgboost  trial_21                  hrrr_slope_11_14_f
 268   xgboost  trial_21       v20_hrrr_t11_minus_observed_f
 276   xgboost  trial_21         v20_model_high_difference_f
 280   xgboost  trial_21  v20_tcc_change_11_to_hrrr_peak_pct

      importance_mean_mae_f  importance_std_mae_f  n_repeats  train_start_year  \
 12                0.055154              0.024645         10              2021
 22                0.036862              0.014913         10              2021
 24                0.035536              0.010365         10              2021
 31                0.027293              0.012167         10              2021
 41                0.021089              0.019092         10              2021
 ..                     ...                   ...        ...               ...
 259              -0.002338              0.003175         10              2021
 261              -0.002515              0.011684         10              2021
 268              -0.003822              0.006527         10              2021
 276              -0.004810              0.011125         10              2021
 280              -0.007119              0.005779         10              2021

      train_end_year  test_year  train_rows  test_rows
 12             2025       2026        1820        171
 22             2025       2026        1820        171
 24             2025       2026        1820        171
 31             2025       2026        1820        171
 41             2025       2026        1820        171
 ..              ...        ...         ...        ...
 259            2025       2026        1820        171
 261            2025       2026        1820        171
 268            2025       2026        1820        171
 276            2025       2026        1820        171
 280            2025       2026        1820        171

 [129 rows x 11 columns])