# KDAL Station Stacking V20 NBM-Physics Fix

KDAL-only patch retaining NBM temperature timing and HRRR solar/cloud/precipitation physics while excluding HRRR temperature-curve features. The final ridge prediction receives a capped monthly correction learned only from forward OOF stack residuals. This provisional run evaluates through July 1, 2026.

In [1]:
from pathlib import Path
import os
import sys
import warnings

warnings.filterwarnings("ignore", message="IProgress not found.*")
warnings.filterwarnings("ignore", message="Skipping features without any observed values.*")

PROJECT_ROOT = Path.cwd().resolve()
while not (PROJECT_ROOT / "src" / "calibration" / "station_stacking.py").exists():
    if PROJECT_ROOT.parent == PROJECT_ROOT:
        raise RuntimeError("Could not find project root containing src/calibration/station_stacking.py")
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

os.environ["WEATHER_RESEARCH_INCLUDE_DIRECT_NBM"] = "1"

STATION_ID = "KDAL"
PROVIDERS = ("gfs", "hrrr", "nbm")
TREND_COLUMNS = [
    "observed_temp_change_last_1h_f",
    "observed_temp_change_last_3h_f",
    "observed_morning_warmup_rate_f_per_hour",
    "observed_high_so_far_change_since_9am_f",
]
TIMING_MODE = "same_day_11am_live_safe"
FAST_MODE = False
OPTUNA_TRIALS = 30
STACK_OPTUNA_TRIALS = 30
OPTUNA_STARTUP_TRIALS = 15
STACK_OPTUNA_STARTUP_TRIALS = 15
OPTUNA_METRIC = "mae_f"
OPTUNA_VERBOSE = True
MODEL_VERSION = "station_high_regressor_v20_kdal_nbm_physics_stack"
EXPORT_MODEL_WEIGHTS = False
PROJECT_ROOT

WindowsPath('D:/dev/weather-research')

In [2]:
import numpy as np
import pandas as pd

from src.export_station_stacking_v2_models import export_station_model_weights
from src.calibration.station_stacking import (
    StationStackingConfig,
    V20_KDAL_NBM_PHYSICS_ENGINEERED_FEATURE_COLUMNS,
    V20_KDAL_NBM_PHYSICS_RAW_FEATURE_COLUMNS,
    kdal_oof_residual_calibrated_stack_predictions,
    V20_ENGINEERED_FEATURE_COLUMNS,
    V20_PEAK_TIMING_RAW_FEATURE_COLUMNS,
    build_station_wide_dataset,
    v20_peak_timing_readiness,
    V11_SETTLEMENT_FIX_TEMP_FEATURE_COLUMNS,
    _fit_feature_columns,
    _modeling_frame,
    V11_DROPPED_FEATURE_COLUMNS,
    V11_FEATURE_COLUMNS,
    V20_EXPANDING_FOLDS,
    missing_model_dependencies,
    provider_availability,
    run_station_year_split_experiment,
)

## V11 Contract

`feature_version="v20_kdal_nbm_physics"` keeps the v9 feature contract and remaining-warmup target, but trains base learners with Huber-style objectives while retaining the ridge stack selected by validation MAE.

In [3]:
fold_spec = pd.DataFrame(
    [
        {
            "fold": fold.name,
            "train_start_year": fold.train_start_year,
            "train_end_year": fold.train_end_year,
            "validation_year": fold.validation_year,
        }
        for fold in V20_EXPANDING_FOLDS
    ]
)

fold_spec

                     fold  train_start_year  train_end_year  validation_year
0       fold_2021_to_2022              2021            2021             2022
1  fold_2021_2022_to_2023              2021            2022             2023
2  fold_2021_2023_to_2024              2021            2023             2024
3  fold_2021_2024_to_2025              2021            2024             2025

In [4]:
V11_FEATURE_COLUMNS, sorted(V11_DROPPED_FEATURE_COLUMNS)

(['v2_recent_heat_anomaly_f',
  'v2_recent_heat_momentum_f',
  'v2_morning_warmup_to_consensus_f',
  'v2_consensus_minus_7d_actual_f',
  'v2_spread_per_warmup_f',
  'v2_humidity_warmup_interaction',
  'v3_high_so_far_above_current_f',
  'v3_remaining_warmup_from_high_so_far_f',
  'v3_high_so_far_minus_lag_1d_f',
  'v3_high_so_far_minus_7d_actual_f',
  'v3_remaining_warmup_per_spread_f',
  'v3_humidity_remaining_warmup_interaction',
  'v4_forecast_precip_total_mean_mm',
  'v4_forecast_precip_total_max_mm',
  'v4_forecast_precip_total_spread_mm',
  'v4_forecast_precip_max_1h_mean_mm',
  'v4_forecast_precip_hours_mean',
  'v4_forecast_precip_intensity_mean',
  'v4_forecast_precip_intensity_max',
  'v4_any_forecast_precip',
  'v4_all_forecast_precip',
  'v4_observed_precip_any',
  'v4_observed_precip_recent_mm_est',
  'v4_forecast_total_minus_observed_recent_mm',
  'v4_forecast_observed_precip_match',
  'v4_forecast_wet_observed_dry',
  'v4_observed_wet_forecast_dry',
  'v4_precip_humidity_interaction',
  'v4_precip_remaining_warmup_interaction',
  'observed_temp_change_last_1h_f',
  'observed_temp_change_last_3h_f',
  'observed_morning_warmup_rate_f_per_hour',
  'observed_high_so_far_change_since_9am_f',
  'v8_provider_max_remaining_from_high_so_far_f',
  'v8_provider_min_remaining_from_high_so_far_f',
  'v8_provider_median_remaining_from_high_so_far_f',
  'v8_provider_spread_per_remaining_warmup_f',
  'v8_month_remaining_warmup_mean_f',
  'v8_month_remaining_warmup_count',
  'v8_recent_remaining_warmup_7d_mean_f',
  'v8_recent_remaining_warmup_30d_mean_f',
  'v8_provider_mean_remaining_vs_month_normal_f',
  'v8_cloud_cover_mean_remaining_warmup_interaction',
  'v8_cloud_cover_max_remaining_warmup_interaction',
  'v8_precip_total_remaining_warmup_interaction',
  'v8_precip_max_1h_remaining_warmup_interaction',
  'v8_wind_speed_mean_remaining_warmup_interaction',
  'v8_wind_gust_max_remaining_warmup_interaction',
  'v8_forecast_dewpoint_mean_f',
  'v8_forecast_dewpoint_depression_mean_f',
  'v8_dewpoint_mean_remaining_warmup_interaction',
  'v8_dewpoint_depression_remaining_warmup_interaction',
  'climatology_high_10y_f',
  'climatology_high_10y_std_f',
  'climatology_high_10y_count',
  'provider_mean_minus_climatology_10y_f',
  'observed_temp_minus_climatology_10y_f',
  'observed_high_so_far_minus_climatology_10y_f'],
 ['actual_minus_climatology_10y_f_DIAGNOSTIC_ONLY',
  'climatology_source_end_year',
  'climatology_source_start_year',
  'gfs_as_of_hour_local',
  'gfs_available',
  'gfs_forecast_window_hours',
  'gfs_grid_dist_km_mean',
  'gfs_horizon_hours',
  'gfs_hrrr_grid_dist_km_mean_abs_diff_f',
  'gfs_hrrr_grid_dist_km_mean_diff_f',
  'gfs_issue_hour_utc',
  'gfs_missing',
  'hrrr_as_of_hour_local',
  'hrrr_available',
  'hrrr_forecast_hour_max',
  'hrrr_forecast_hour_min',
  'hrrr_forecast_lead_hours',
  'hrrr_forecast_window_hours',
  'hrrr_grid_dist_km_mean',
  'hrrr_horizon_hours',
  'hrrr_issue_hour_local',
  'hrrr_issue_hour_utc',
  'hrrr_missing',
  'is_active_polymarket_station',
  'lat',
  'lon',
  'nbm_as_of_hour_local',
  'nbm_available',
  'nbm_forecast_window_hours',
  'nbm_horizon_hours',
  'nbm_issue_hour_local',
  'nbm_issue_hour_utc',
  'nbm_missing',
  'observed_fetch_status',
  'observed_observation_type',
  'observed_pressure_source',
  'provider_count_available',
  'year'])

## Data Availability

In [5]:
availability = provider_availability(
    PROJECT_ROOT,
    timing_mode=TIMING_MODE,
    providers=PROVIDERS,
)

availability.loc[availability["station_id"].eq(STATION_ID)]

  station_id provider  row_count first_contract_date last_contract_date
6       KDAL      gfs       1993          2021-01-01         2026-07-12
7       KDAL     hrrr       1999          2021-01-01         2026-07-12
8       KDAL      nbm       1998          2021-01-01         2026-07-12

## Model Scores

## Peak-Timing and Wunderground Readiness Gate

In [6]:
readiness_features = build_station_wide_dataset(
    PROJECT_ROOT,
    station_id=STATION_ID,
    timing_mode=TIMING_MODE,
    providers=PROVIDERS,
    feature_version="v20_kdal_nbm_physics",
    target_source="wunderground_only",
)
EVALUATION_END_DATE = "2026-07-01"  # provisional; official V20 cutoff remains 2026-07-14
v20_ready, readiness_summary, readiness_missing_dates, readiness_fold_missingness = v20_peak_timing_readiness(
    readiness_features,
    station_id=STATION_ID,
    folds=V20_EXPANDING_FOLDS,
    max_missing_fraction=0.03,
    end_date=EVALUATION_END_DATE,
)
readiness_dir = PROJECT_ROOT / "data" / "calibration" / "station_stacking_v20_kdal_fix"
readiness_dir.mkdir(parents=True, exist_ok=True)
readiness_summary.to_csv(readiness_dir / f"{STATION_ID}_readiness_summary.csv", index=False)
readiness_missing_dates.to_csv(readiness_dir / f"{STATION_ID}_readiness_missing_dates.csv", index=False)
readiness_fold_missingness.to_csv(readiness_dir / f"{STATION_ID}_readiness_fold_feature_missingness.csv", index=False)
display(readiness_summary)
display(readiness_fold_missingness.groupby(["fold", "retained"], as_index=False).agg(feature_count=("feature", "nunique")))
if not v20_ready:
    raise RuntimeError(
        "V20 readiness failed. Audit artifacts were written; rerun this notebook after peak-timing and "
        "Wunderground pulls reduce each station-year missing fraction to 3% or less."
    )

D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()

,station_id,year,expected_days,peak_ready_days,wunderground_target_days,peak_missing_fraction,target_missing_fraction,peak_ready,target_ready
0,KDAL,2021,365,364,364,0.00274,0.002740,True,True
1,KDAL,2022,365,365,364,0.00000,0.002740,True,True
2,KDAL,2023,365,365,364,0.00000,0.002740,True,True
3,KDAL,2024,366,366,365,0.00000,0.002732,True,True
4,KDAL,2025,365,365,364,0.00000,0.002740,True,True
5,KDAL,2026,182,182,181,0.00000,0.005495,True,True

                     fold  retained  feature_count
0  fold_2021_2022_to_2023     False              1
1  fold_2021_2022_to_2023      True             54
2  fold_2021_2023_to_2024     False              1
3  fold_2021_2023_to_2024      True             54
4  fold_2021_2024_to_2025     False              1
5  fold_2021_2024_to_2025      True             54
6       fold_2021_to_2022     False              1
7       fold_2021_to_2022      True             54
8    test_refit_2021_2025     False              1
9    test_refit_2021_2025      True             54

In [7]:
missing_packages = missing_model_dependencies()
if missing_packages:
    raise ImportError(
        "Missing station-stacking ML packages: "
        + ", ".join(missing_packages)
        + ". Install them with: python -m pip install -r requirements.txt"
    )

config = StationStackingConfig(
    station_id=STATION_ID,
    project_root=PROJECT_ROOT,
    timing_mode=TIMING_MODE,
    providers=PROVIDERS,
    fast_mode=FAST_MODE,
    optuna_trials=OPTUNA_TRIALS,
    stack_optuna_trials=STACK_OPTUNA_TRIALS,
    optuna_startup_trials=OPTUNA_STARTUP_TRIALS,
    stack_optuna_startup_trials=STACK_OPTUNA_STARTUP_TRIALS,
    optuna_metric=OPTUNA_METRIC,
    optuna_verbose=OPTUNA_VERBOSE,
    feature_version="v20_kdal_nbm_physics",
    target_mode="remaining_warmup",
    target_source="wunderground_only",
    max_feature_missing_fraction=0.03,
    base_model_methods=("xgboost", "lightgbm", "catboost"),
    stack_enabled=True,
    hyperparameter_space="wide",
    year_split_folds=V20_EXPANDING_FOLDS,
    year_split_validation_weights={2022: 1.0, 2023: 1.0, 2024: 1.0, 2025: 1.0},
    year_split_test_train_years=(2021, 2025),
    year_split_test_year=2026,
    output_dir=PROJECT_ROOT / "data" / "calibration" / "station_stacking_v20_kdal_fix",
)

config.resolved_optuna_storage_path()

WindowsPath('D:/dev/weather-research/data/calibration/station_stacking_v20_kdal_fix/KDAL_optuna.sqlite3')

In [8]:
result = run_station_year_split_experiment(config)
result.scoreboard

D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()
D:\dev\weather-research\src\calibration\station_stacking.py:3539: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_diff_f"] = left_values - right_values
D:\dev\weather-research\src\calibration\station_stacking.py:3540: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out[f"{prefix}_{feature_name}_abs_diff_f"] = (left_values - right_values).abs()

[I 2026-07-16 10:54:10,792] A new study created in RDB with name: KDAL_v20_kdal_nbm_physics_remaining_warmup_base_xgboost_mae_f_wide

[I 2026-07-16 10:54:14,138] Trial 0 finished with value: 1.6440167185606287 and parameters: {'n_estimators': 1342, 'learning_rate': 0.19043899115982607, 'max_depth': 9, 'min_child_weight': 2.481040974867813, 'gamma': 2.340279606636548, 'subsample': 0.4513964382185317, 'colsample_bytree': 0.3877543479093296, 'reg_alpha': 2.478071022662141, 'reg_lambda': 0.6132587025321562}. Best is trial 0 with value: 1.6440167185606287.

[I 2026-07-16 10:54:20,748] Trial 1 finished with value: 2.2713010804927554 and parameters: {'n_estimators': 2493, 'learning_rate': 0.001120367191095075, 'max_depth': 12, 'min_child_weight': 21.368329072358772, 'gamma': 3.185086660174142, 'subsample': 0.4681862286846154, 'colsample_bytree': 0.46921293140473197, 'reg_alpha': 4.476173538513514e-07, 'reg_lambda': 0.20253776634919213}. Best is trial 0 with value: 1.6440167185606287.

[I 2026-07-16 10:54:24,815] Trial 2 finished with value: 1.454956015945798 and parameters: {'n_estimators': 1540, 'learning_rate': 0.004992867109217114, 'max_depth': 8, 'min_child_weight': 0.03613894271216528, 'gamma': 4.3821697280282725, 'subsample': 0.5881351981408995, 'colsample_bytree': 0.6464454897410734, 'reg_alpha': 0.26430874752361627, 'reg_lambda': 0.0018119678627933364}. Best is trial 2 with value: 1.454956015945798.

[I 2026-07-16 10:54:27,001] Trial 3 finished with value: 1.9648376702575776 and parameters: {'n_estimators': 1824, 'learning_rate': 0.026337502897485255, 'max_depth': 1, 'min_child_weight': 2.69264691008618, 'gamma': 2.557861855309373, 'subsample': 0.39228353544043165, 'colsample_bytree': 0.9667755992146666, 'reg_alpha': 38.6887231523051, 'reg_lambda': 12.408975837016275}. Best is trial 2 with value: 1.454956015945798.

[I 2026-07-16 10:54:33,396] Trial 4 finished with value: 1.617856013003367 and parameters: {'n_estimators': 1101, 'learning_rate': 0.0017147936629846843, 'max_depth': 9, 'min_child_weight': 0.5762487216478605, 'gamma': 1.8305735226716824, 'subsample': 0.6718649915723256, 'colsample_bytree': 0.37235253872489193, 'reg_alpha': 8.162906555194692, 'reg_lambda': 0.004271500153828077}. Best is trial 2 with value: 1.454956015945798.

[I 2026-07-16 10:54:34,772] Trial 5 pruned.

[I 2026-07-16 10:54:36,063] Trial 6 finished with value: 1.4547345472935405 and parameters: {'n_estimators': 2113, 'learning_rate': 0.16240489353272883, 'max_depth': 2, 'min_child_weight': 0.06080390190296603, 'gamma': 0.678409333658071, 'subsample': 0.5614647149961218, 'colsample_bytree': 0.6026402382981633, 'reg_alpha': 1.8037999945880162e-07, 'reg_lambda': 16.668629892722056}. Best is trial 6 with value: 1.4547345472935405.

[I 2026-07-16 10:54:39,057] Trial 7 finished with value: 1.5005024043709454 and parameters: {'n_estimators': 1281, 'learning_rate': 0.0047169807141865345, 'max_depth': 7, 'min_child_weight': 0.0366181922039243, 'gamma': 12.032954711310595, 'subsample': 0.398457918391851, 'colsample_bytree': 0.9914765087903362, 'reg_alpha': 0.18490013641000916, 'reg_lambda': 0.0017869543989965139}. Best is trial 6 with value: 1.4547345472935405.

[I 2026-07-16 10:54:39,443] Trial 8 pruned.

[I 2026-07-16 10:54:42,962] Trial 9 finished with value: 1.4793969353433996 and parameters: {'n_estimators': 2201, 'learning_rate': 0.006215464818952927, 'max_depth': 1, 'min_child_weight': 0.17535949529764422, 'gamma': 4.877749830401205, 'subsample': 0.8242440159197416, 'colsample_bytree': 0.7644123563808884, 'reg_alpha': 4.4315220126915325, 'reg_lambda': 0.09450187118503514}. Best is trial 6 with value: 1.4547345472935405.

[I 2026-07-16 10:54:44,344] Trial 10 finished with value: 1.479720682462289 and parameters: {'n_estimators': 462, 'learning_rate': 0.051323729958866915, 'max_depth': 10, 'min_child_weight': 1.7583640270008525, 'gamma': 11.564507699318415, 'subsample': 0.670967137636854, 'colsample_bytree': 0.689776339098296, 'reg_alpha': 1.3504926357029513e-05, 'reg_lambda': 0.0001445994629863374}. Best is trial 6 with value: 1.4547345472935405.

[I 2026-07-16 10:54:45,157] Trial 11 pruned.

[I 2026-07-16 10:54:45,996] Trial 12 pruned.

[I 2026-07-16 10:54:46,482] Trial 13 pruned.

[I 2026-07-16 10:54:47,033] Trial 14 pruned.

[I 2026-07-16 10:54:49,376] Trial 15 finished with value: 1.4305642852710474 and parameters: {'n_estimators': 3311, 'learning_rate': 0.021659849180609474, 'max_depth': 4, 'min_child_weight': 0.011054022093830057, 'gamma': 0.3744567555104146, 'subsample': 0.6098242026591096, 'colsample_bytree': 0.6181229892049431, 'reg_alpha': 0.003083204463756954, 'reg_lambda': 1.7165588122951194}. Best is trial 15 with value: 1.4305642852710474.

[I 2026-07-16 10:54:52,240] Trial 16 finished with value: 1.4087794195284769 and parameters: {'n_estimators': 3489, 'learning_rate': 0.016793077420452978, 'max_depth': 4, 'min_child_weight': 0.012617266144018207, 'gamma': 0.44159864965260953, 'subsample': 0.7142047858524985, 'colsample_bytree': 0.5568860625811252, 'reg_alpha': 0.001246682767594009, 'reg_lambda': 1.3847287014026617}. Best is trial 16 with value: 1.4087794195284769.

[I 2026-07-16 10:54:52,818] Trial 17 pruned.

[I 2026-07-16 10:54:53,587] Trial 18 pruned.

[I 2026-07-16 10:54:54,077] Trial 19 pruned.

[I 2026-07-16 10:54:54,594] Trial 20 pruned.

[I 2026-07-16 10:54:55,243] Trial 21 pruned.

[I 2026-07-16 10:54:56,377] Trial 22 pruned.

[I 2026-07-16 10:54:57,302] Trial 23 pruned.

[I 2026-07-16 10:54:59,374] Trial 24 pruned.

[I 2026-07-16 10:54:59,804] Trial 25 pruned.

[I 2026-07-16 10:55:01,467] Trial 26 finished with value: 1.4030643825970985 and parameters: {'n_estimators': 2725, 'learning_rate': 0.08754779916489241, 'max_depth': 2, 'min_child_weight': 0.0232372946020671, 'gamma': 1.0489473383705181, 'subsample': 0.7861139716906713, 'colsample_bytree': 0.5321938054229274, 'reg_alpha': 0.0055839245991266, 'reg_lambda': 15.07316229504204}. Best is trial 26 with value: 1.4030643825970985.

[I 2026-07-16 10:55:01,924] Trial 27 pruned.

[I 2026-07-16 10:55:04,171] Trial 28 finished with value: 1.4384783049767234 and parameters: {'n_estimators': 3270, 'learning_rate': 0.010014402960356389, 'max_depth': 2, 'min_child_weight': 0.019911756576182472, 'gamma': 8.875685172748998, 'subsample': 0.8783063966142731, 'colsample_bytree': 0.5355258159470603, 'reg_alpha': 0.002711485692138736, 'reg_lambda': 0.988404886583712}. Best is trial 26 with value: 1.4030643825970985.

[I 2026-07-16 10:55:05,079] Trial 29 pruned.

[I 2026-07-16 10:55:05,132] A new study created in RDB with name: KDAL_v20_kdal_nbm_physics_remaining_warmup_base_lightgbm_mae_f_wide

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:07,217] Trial 0 finished with value: 1.5880561420522084 and parameters: {'n_estimators': 447, 'learning_rate': 0.028873871707375695, 'num_leaves': 71, 'max_depth': 5, 'min_child_samples': 83, 'min_split_gain': 4.295687454742988, 'bagging_fraction': 0.7829586385137167, 'bagging_freq': 4, 'feature_fraction': 0.3688589858758342, 'lambda_l1': 0.06382334403151436, 'lambda_l2': 0.03080292177315921, 'huber_alpha': 0.95}. Best is trial 0 with value: 1.5880561420522084.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:08,619] Trial 1 finished with value: 2.2103188440965233 and parameters: {'n_estimators': 812, 'learning_rate': 0.009357081249483435, 'num_leaves': 164, 'max_depth': 2, 'min_child_samples': 211, 'min_split_gain': 4.244695738724308, 'bagging_fraction': 0.9814523094330022, 'bagging_freq': 3, 'feature_fraction': 0.9704172813206324, 'lambda_l1': 2.234088279028776e-05, 'lambda_l2': 1.6594154120142632, 'huber_alpha': 0.85}. Best is trial 0 with value: 1.5880561420522084.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[I 2026-07-16 10:55:09,546] Trial 2 finished with value: 2.8098970234681913 and parameters: {'n_estimators': 67, 'learning_rate': 0.02007090910723469, 'num_leaves': 246, 'max_depth': 10, 'min_child_samples': 245, 'min_split_gain': 4.543313789155439, 'bagging_fraction': 0.9415994992571017, 'bagging_freq': 4, 'feature_fraction': 0.41761231740559585, 'lambda_l1': 1.4824332354449863e-08, 'lambda_l2': 101.18939970488272, 'huber_alpha': 0.85}. Best is trial 0 with value: 1.5880561420522084.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:10,497] Trial 3 finished with value: 2.413745186954171 and parameters: {'n_estimators': 1000, 'learning_rate': 0.1413663860910666, 'num_leaves': 109, 'max_depth': 7, 'min_child_samples': 249, 'min_split_gain': 3.678635407535604, 'bagging_fraction': 0.6392899181182937, 'bagging_freq': 4, 'feature_fraction': 0.6173160679063129, 'lambda_l1': 0.052948773379180566, 'lambda_l2': 0.032760577756785814, 'huber_alpha': 0.85}. Best is trial 0 with value: 1.5880561420522084.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:11,857] Trial 4 finished with value: 2.7039392954150894 and parameters: {'n_estimators': 761, 'learning_rate': 0.003003151716938294, 'num_leaves': 409, 'max_depth': 5, 'min_child_samples': 165, 'min_split_gain': 1.498083879035124, 'bagging_fraction': 0.44391094597483866, 'bagging_freq': 3, 'feature_fraction': 0.5516751924489833, 'lambda_l1': 8.332516750396116e-08, 'lambda_l2': 0.5077631895453656, 'huber_alpha': 0.85}. Best is trial 0 with value: 1.5880561420522084.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[I 2026-07-16 10:55:12,899] Trial 5 finished with value: 1.4635229977020785 and parameters: {'n_estimators': 404, 'learning_rate': 0.18314620854695027, 'num_leaves': 260, 'max_depth': 13, 'min_child_samples': 51, 'min_split_gain': 2.972245934092154, 'bagging_fraction': 0.9775155780902212, 'bagging_freq': 7, 'feature_fraction': 0.365709606237354, 'lambda_l1': 5.9654059281874116e-05, 'lambda_l2': 0.006859036422781172, 'huber_alpha': 0.95}. Best is trial 5 with value: 1.4635229977020785.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:14,052] Trial 6 finished with value: 1.4513227522400138 and parameters: {'n_estimators': 3052, 'learning_rate': 0.13146898336096702, 'num_leaves': 489, 'max_depth': 11, 'min_child_samples': 47, 'min_split_gain': 2.173391605434026, 'bagging_fraction': 0.9258346721061177, 'bagging_freq': 2, 'feature_fraction': 0.6381532515738396, 'lambda_l1': 0.002530717742378322, 'lambda_l2': 0.0004479476588817844, 'huber_alpha': 0.95}. Best is trial 6 with value: 1.4513227522400138.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:15,052] Trial 7 finished with value: 2.0184523972866417 and parameters: {'n_estimators': 2519, 'learning_rate': 0.18104669093362824, 'num_leaves': 399, 'max_depth': 4, 'min_child_samples': 227, 'min_split_gain': 2.761320735057018, 'bagging_fraction': 0.8991836269249566, 'bagging_freq': 7, 'feature_fraction': 0.8888248313104422, 'lambda_l1': 5.374969144858311e-06, 'lambda_l2': 0.5877618471031133, 'huber_alpha': 0.85}. Best is trial 6 with value: 1.4513227522400138.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:19,201] Trial 8 finished with value: 1.6508313393132414 and parameters: {'n_estimators': 2273, 'learning_rate': 0.0030965152683643635, 'num_leaves': 383, 'max_depth': 3, 'min_child_samples': 3, 'min_split_gain': 1.6724449577646616, 'bagging_fraction': 0.9800160774901863, 'bagging_freq': 5, 'feature_fraction': 0.6188955975766686, 'lambda_l1': 2.8120694751804143e-09, 'lambda_l2': 0.00024007807690373727, 'huber_alpha': 0.85}. Best is trial 6 with value: 1.4513227522400138.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:20,012] Trial 9 pruned.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:23,488] Trial 10 finished with value: 1.642995418352248 and parameters: {'n_estimators': 2941, 'learning_rate': 0.007104579859769969, 'num_leaves': 424, 'max_depth': 2, 'min_child_samples': 2, 'min_split_gain': 4.6220887565718325, 'bagging_fraction': 0.7880566131549542, 'bagging_freq': 7, 'feature_fraction': 0.661678263936434, 'lambda_l1': 8.121756387194875e-09, 'lambda_l2': 100.08386764870838, 'huber_alpha': 0.9}. Best is trial 6 with value: 1.4513227522400138.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:23,900] Trial 11 pruned.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:25,152] Trial 12 finished with value: 1.5544821626687106 and parameters: {'n_estimators': 3404, 'learning_rate': 0.03866939016656176, 'num_leaves': 50, 'max_depth': 9, 'min_child_samples': 54, 'min_split_gain': 3.975378174997817, 'bagging_fraction': 0.5776988884481041, 'bagging_freq': 4, 'feature_fraction': 0.8073004449855348, 'lambda_l1': 1.1469173194560514e-08, 'lambda_l2': 0.6127644589218547, 'huber_alpha': 0.85}. Best is trial 6 with value: 1.4513227522400138.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:25,535] Trial 13 pruned.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:26,192] Trial 14 pruned.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:27,694] Trial 15 finished with value: 1.4175926246316934 and parameters: {'n_estimators': 1596, 'learning_rate': 0.07412684021464837, 'num_leaves': 490, 'max_depth': 14, 'min_child_samples': 54, 'min_split_gain': 0.3349947053308182, 'bagging_fraction': 0.8356054383416602, 'bagging_freq': 1, 'feature_fraction': 0.4928412115082472, 'lambda_l1': 5.944760726571435, 'lambda_l2': 0.004183303285898086, 'huber_alpha': 0.95}. Best is trial 15 with value: 1.4175926246316934.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:28,221] Trial 16 pruned.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:28,698] Trial 17 pruned.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:30,399] Trial 18 finished with value: 1.4665658412437836 and parameters: {'n_estimators': 3498, 'learning_rate': 0.059131536443425475, 'num_leaves': 342, 'max_depth': 8, 'min_child_samples': 95, 'min_split_gain': 0.9297846530290041, 'bagging_fraction': 0.8581088794716628, 'bagging_freq': 2, 'feature_fraction': 0.5067584209831179, 'lambda_l1': 0.009409403770416278, 'lambda_l2': 0.01950927643144989, 'huber_alpha': 0.75}. Best is trial 15 with value: 1.4175926246316934.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:33,358] Trial 19 finished with value: 1.4194942861194924 and parameters: {'n_estimators': 2048, 'learning_rate': 0.015467561997108534, 'num_leaves': 467, 'max_depth': 12, 'min_child_samples': 36, 'min_split_gain': 0.8867366054404582, 'bagging_fraction': 0.7386509877156308, 'bagging_freq': 2, 'feature_fraction': 0.7453029649885938, 'lambda_l1': 1.0612674116708008e-10, 'lambda_l2': 0.005680543170358973, 'huber_alpha': 0.95}. Best is trial 15 with value: 1.4175926246316934.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:33,912] Trial 20 pruned.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:34,621] Trial 21 pruned.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:36,310] Trial 22 finished with value: 1.4219484492615955 and parameters: {'n_estimators': 2055, 'learning_rate': 0.046128456183836604, 'num_leaves': 347, 'max_depth': 13, 'min_child_samples': 28, 'min_split_gain': 0.9671987726705117, 'bagging_fraction': 0.8665927277296104, 'bagging_freq': 1, 'feature_fraction': 0.5397623740000719, 'lambda_l1': 0.004320469653742817, 'lambda_l2': 0.0007363742010087261, 'huber_alpha': 0.95}. Best is trial 15 with value: 1.4175926246316934.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:38,059] Trial 23 finished with value: 1.4089176108711068 and parameters: {'n_estimators': 2109, 'learning_rate': 0.03641975695899514, 'num_leaves': 344, 'max_depth': 13, 'min_child_samples': 20, 'min_split_gain': 1.0413136756232446, 'bagging_fraction': 0.8554625959530964, 'bagging_freq': 1, 'feature_fraction': 0.5532123411314687, 'lambda_l1': 0.9100777646757591, 'lambda_l2': 0.004804534972712218, 'huber_alpha': 0.95}. Best is trial 23 with value: 1.4089176108711068.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:40,004] Trial 24 finished with value: 1.441440590655657 and parameters: {'n_estimators': 1408, 'learning_rate': 0.02334435335991663, 'num_leaves': 332, 'max_depth': 13, 'min_child_samples': 68, 'min_split_gain': 1.2517538075691048, 'bagging_fraction': 0.7836893981137134, 'bagging_freq': 1, 'feature_fraction': 0.4578765176092077, 'lambda_l1': 1.1284356770941455, 'lambda_l2': 0.008424816325523792, 'huber_alpha': 0.95}. Best is trial 23 with value: 1.4089176108711068.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:42,459] Trial 25 finished with value: 1.4081725262756877 and parameters: {'n_estimators': 1990, 'learning_rate': 0.014469931569957049, 'num_leaves': 5, 'max_depth': 14, 'min_child_samples': 21, 'min_split_gain': 0.4563742903618905, 'bagging_fraction': 0.700382735743568, 'bagging_freq': 3, 'feature_fraction': 0.834029424265224, 'lambda_l1': 1.6522517834478845, 'lambda_l2': 0.09891036537472203, 'huber_alpha': 0.9}. Best is trial 25 with value: 1.4081725262756877.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:44,482] Trial 26 finished with value: 1.4206961626696022 and parameters: {'n_estimators': 1878, 'learning_rate': 0.038014802004680784, 'num_leaves': 27, 'max_depth': 14, 'min_child_samples': 17, 'min_split_gain': 0.471001398229384, 'bagging_fraction': 0.8273882107025695, 'bagging_freq': 3, 'feature_fraction': 0.838029428599582, 'lambda_l1': 0.7749531739555471, 'lambda_l2': 0.1132745465015457, 'huber_alpha': 0.9}. Best is trial 25 with value: 1.4081725262756877.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:45,059] Trial 27 pruned.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:48,732] Trial 28 finished with value: 1.415831124436639 and parameters: {'n_estimators': 2218, 'learning_rate': 0.013910799074152169, 'num_leaves': 225, 'max_depth': 13, 'min_child_samples': 24, 'min_split_gain': 0.017570522474101624, 'bagging_fraction': 0.5812673264333954, 'bagging_freq': 3, 'feature_fraction': 0.8951794522419585, 'lambda_l1': 0.13384425629067234, 'lambda_l2': 0.09432225495046807, 'huber_alpha': 0.9}. Best is trial 25 with value: 1.4081725262756877.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-16 10:55:51,488] Trial 29 finished with value: 1.4148266011380306 and parameters: {'n_estimators': 2187, 'learning_rate': 0.013379059448589739, 'num_leaves': 214, 'max_depth': 10, 'min_child_samples': 19, 'min_split_gain': 1.3556535607055453, 'bagging_fraction': 0.4966959957355702, 'bagging_freq': 3, 'feature_fraction': 0.9093647557852016, 'lambda_l1': 0.10610516095455697, 'lambda_l2': 3.639714742316096, 'huber_alpha': 0.9}. Best is trial 25 with value: 1.4081725262756877.

[I 2026-07-16 10:55:51,535] A new study created in RDB with name: KDAL_v20_kdal_nbm_physics_remaining_warmup_base_catboost_mae_f_wide

[I 2026-07-16 10:59:39,640] Trial 0 finished with value: 1.7872498056409922 and parameters: {'iterations': 2931, 'learning_rate': 0.001783588943232587, 'depth': 10, 'l2_leaf_reg': 0.9942958882300413, 'random_strength': 7.186216756161439, 'bagging_temperature': 12.184767612363034, 'border_count': 110, 'rsm': 0.6158971964095841, 'huber_delta': 1.5}. Best is trial 0 with value: 1.7872498056409922.

[I 2026-07-16 11:04:40,667] Trial 1 finished with value: 2.0258522239082457 and parameters: {'iterations': 801, 'learning_rate': 0.19767902101650964, 'depth': 12, 'l2_leaf_reg': 75.05056513807031, 'random_strength': 12.92821124806787, 'bagging_temperature': 4.276496242612171, 'border_count': 168, 'rsm': 0.4404450637901872, 'huber_delta': 1.0}. Best is trial 0 with value: 1.7872498056409922.

[I 2026-07-16 11:04:47,624] Trial 2 finished with value: 1.7738109950991312 and parameters: {'iterations': 1992, 'learning_rate': 0.0024079350849750287, 'depth': 3, 'l2_leaf_reg': 0.118485976001343, 'random_strength': 4.058751860003342, 'bagging_temperature': 9.103785934457758, 'border_count': 206, 'rsm': 0.994034742637508, 'huber_delta': 0.5}. Best is trial 2 with value: 1.7738109950991312.

[I 2026-07-16 11:13:18,398] Trial 3 finished with value: 2.0015119158870784 and parameters: {'iterations': 3095, 'learning_rate': 0.05508623515899769, 'depth': 11, 'l2_leaf_reg': 18.082710740309665, 'random_strength': 13.948598364083836, 'bagging_temperature': 18.60205606816345, 'border_count': 227, 'rsm': 0.4117317891426977, 'huber_delta': 3.0}. Best is trial 2 with value: 1.7738109950991312.

[I 2026-07-16 11:13:29,764] Trial 4 finished with value: 1.5425278461234702 and parameters: {'iterations': 3146, 'learning_rate': 0.0024764229908984673, 'depth': 3, 'l2_leaf_reg': 0.6951779671472356, 'random_strength': 6.148451176512449, 'bagging_temperature': 8.441103735088014, 'border_count': 95, 'rsm': 0.7192489923988105, 'huber_delta': 2.0}. Best is trial 4 with value: 1.5425278461234702.

[I 2026-07-16 11:13:34,228] Trial 5 finished with value: 1.6502461623972868 and parameters: {'iterations': 2996, 'learning_rate': 0.04169299311145666, 'depth': 2, 'l2_leaf_reg': 0.6483636109972302, 'random_strength': 11.284989840243444, 'bagging_temperature': 11.881552589055849, 'border_count': 179, 'rsm': 0.7610806862514128, 'huber_delta': 0.5}. Best is trial 4 with value: 1.5425278461234702.

[I 2026-07-16 11:13:34,766] Trial 6 pruned.

[I 2026-07-16 11:13:38,115] Trial 7 finished with value: 1.998248514086534 and parameters: {'iterations': 2269, 'learning_rate': 0.05988786419186062, 'depth': 3, 'l2_leaf_reg': 0.8727148674658863, 'random_strength': 13.785080578883292, 'bagging_temperature': 3.643240241026453, 'border_count': 16, 'rsm': 0.5239102067389221, 'huber_delta': 0.5}. Best is trial 4 with value: 1.5425278461234702.

[I 2026-07-16 11:13:40,841] Trial 8 pruned.

[I 2026-07-16 11:14:43,800] Trial 9 finished with value: 1.5556120358925083 and parameters: {'iterations': 2176, 'learning_rate': 0.006973123504821021, 'depth': 7, 'l2_leaf_reg': 1.0111907140307084, 'random_strength': 19.613513312465464, 'bagging_temperature': 8.113717548278494, 'border_count': 208, 'rsm': 0.7899333278528806, 'huber_delta': 5.0}. Best is trial 4 with value: 1.5425278461234702.

[I 2026-07-16 11:14:48,899] Trial 10 pruned.

[I 2026-07-16 11:15:09,614] Trial 11 finished with value: 1.458833147212329 and parameters: {'iterations': 2772, 'learning_rate': 0.014522829031783214, 'depth': 5, 'l2_leaf_reg': 15.987388321276002, 'random_strength': 11.591109950971106, 'bagging_temperature': 7.790667047006705, 'border_count': 126, 'rsm': 0.7500006952294106, 'huber_delta': 5.0}. Best is trial 11 with value: 1.458833147212329.

[I 2026-07-16 11:15:19,532] Trial 12 pruned.

[I 2026-07-16 11:15:21,126] Trial 13 pruned.

[I 2026-07-16 11:15:25,571] Trial 14 finished with value: 1.5231202670341752 and parameters: {'iterations': 2033, 'learning_rate': 0.03406017942217813, 'depth': 3, 'l2_leaf_reg': 2.8273302406131626, 'random_strength': 2.5986858551767766, 'bagging_temperature': 5.630188860588947, 'border_count': 58, 'rsm': 0.9026140460549269, 'huber_delta': 1.0}. Best is trial 11 with value: 1.458833147212329.

[I 2026-07-16 11:15:33,132] Trial 15 finished with value: 1.4739558639239225 and parameters: {'iterations': 1315, 'learning_rate': 0.014385732536856719, 'depth': 5, 'l2_leaf_reg': 3.851734847884429, 'random_strength': 16.094365397211288, 'bagging_temperature': 5.889443951608335, 'border_count': 45, 'rsm': 0.9247512589809201, 'huber_delta': 5.0}. Best is trial 11 with value: 1.458833147212329.

[I 2026-07-16 11:15:34,864] Trial 16 pruned.

[I 2026-07-16 11:16:21,638] Trial 17 finished with value: 1.4286896544802785 and parameters: {'iterations': 3466, 'learning_rate': 0.006277057772508926, 'depth': 6, 'l2_leaf_reg': 8.15026783421867, 'random_strength': 16.574794818938415, 'bagging_temperature': 1.3263969896774768, 'border_count': 147, 'rsm': 0.9160969794177436, 'huber_delta': 5.0}. Best is trial 17 with value: 1.4286896544802785.

[I 2026-07-16 11:16:57,306] Trial 18 finished with value: 1.4687592310879 and parameters: {'iterations': 2613, 'learning_rate': 0.004994299712769344, 'depth': 6, 'l2_leaf_reg': 13.631090697889816, 'random_strength': 17.124972126147984, 'bagging_temperature': 0.31515488633751154, 'border_count': 125, 'rsm': 0.8260109735014788, 'huber_delta': 5.0}. Best is trial 17 with value: 1.4286896544802785.

[I 2026-07-16 11:17:27,750] Trial 19 pruned.

[I 2026-07-16 11:17:41,889] Trial 20 finished with value: 1.4196770240437955 and parameters: {'iterations': 3478, 'learning_rate': 0.019410928337830636, 'depth': 5, 'l2_leaf_reg': 7.7001667147105195, 'random_strength': 15.230008686860389, 'bagging_temperature': 2.521731951133892, 'border_count': 155, 'rsm': 0.8910683221416084, 'huber_delta': 2.0}. Best is trial 20 with value: 1.4196770240437955.

[I 2026-07-16 11:17:57,865] Trial 21 finished with value: 1.4501720950215036 and parameters: {'iterations': 3368, 'learning_rate': 0.016814137239349623, 'depth': 5, 'l2_leaf_reg': 6.192427308840934, 'random_strength': 15.774251347671672, 'bagging_temperature': 2.5230716910799504, 'border_count': 158, 'rsm': 0.9092126910829951, 'huber_delta': 2.0}. Best is trial 20 with value: 1.4196770240437955.

[I 2026-07-16 11:18:02,935] Trial 22 pruned.

[I 2026-07-16 11:18:03,910] Trial 23 pruned.

[I 2026-07-16 11:18:54,796] Trial 24 finished with value: 1.48044281846578 and parameters: {'iterations': 3483, 'learning_rate': 0.008873545020806313, 'depth': 6, 'l2_leaf_reg': 5.874201328139322, 'random_strength': 14.694904537965899, 'bagging_temperature': 5.099723018591697, 'border_count': 173, 'rsm': 0.9108370680777435, 'huber_delta': 2.0}. Best is trial 20 with value: 1.4196770240437955.

[I 2026-07-16 11:18:58,045] Trial 25 pruned.

[I 2026-07-16 11:19:11,782] Trial 26 finished with value: 1.4728484309126089 and parameters: {'iterations': 3208, 'learning_rate': 0.004599670382254031, 'depth': 4, 'l2_leaf_reg': 30.378560158338114, 'random_strength': 12.836445221902773, 'bagging_temperature': 1.2383978411222125, 'border_count': 75, 'rsm': 0.9604511993831554, 'huber_delta': 2.0}. Best is trial 20 with value: 1.4196770240437955.

[I 2026-07-16 11:19:32,896] Trial 27 pruned.

[I 2026-07-16 11:19:42,112] Trial 28 finished with value: 1.4365222533313613 and parameters: {'iterations': 3210, 'learning_rate': 0.021651484167140467, 'depth': 4, 'l2_leaf_reg': 8.107782086506363, 'random_strength': 17.817679618958838, 'bagging_temperature': 3.1545559651863626, 'border_count': 186, 'rsm': 0.8280409140069556, 'huber_delta': 2.0}. Best is trial 20 with value: 1.4196770240437955.

[I 2026-07-16 11:19:53,696] Trial 29 finished with value: 1.4669010570570382 and parameters: {'iterations': 2957, 'learning_rate': 0.024594881316506265, 'depth': 4, 'l2_leaf_reg': 9.375341312881307, 'random_strength': 18.136168077262035, 'bagging_temperature': 4.422372564565645, 'border_count': 196, 'rsm': 0.8105418949884511, 'huber_delta': 3.0}. Best is trial 20 with value: 1.4196770240437955.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[I 2026-07-16 11:20:49,680] A new study created in RDB with name: KDAL_v20_kdal_nbm_physics_remaining_warmup_stack_ridge_stack_mae_f_wide

[I 2026-07-16 11:20:50,170] Trial 0 finished with value: 1.311122425426765 and parameters: {'feature_set': 'models_only', 'alpha': 1061.6032395070417, 'fit_intercept': False}. Best is trial 0 with value: 1.311122425426765.

[I 2026-07-16 11:20:50,702] Trial 1 finished with value: 1.3102787730434147 and parameters: {'feature_set': 'models_only', 'alpha': 29.13552742298041, 'fit_intercept': False}. Best is trial 1 with value: 1.3102787730434147.

[I 2026-07-16 11:20:51,138] Trial 2 finished with value: 1.321320093787319 and parameters: {'feature_set': 'models_only', 'alpha': 0.0005260598165963439, 'fit_intercept': True}. Best is trial 1 with value: 1.3102787730434147.

[I 2026-07-16 11:20:51,650] Trial 3 finished with value: 1.3096769313294738 and parameters: {'feature_set': 'models_only', 'alpha': 2.2872748315304782e-05, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:52,203] Trial 4 finished with value: 1.3474560584303414 and parameters: {'feature_set': 'models_plus_raw', 'alpha': 1013.2424299869091, 'fit_intercept': True}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:52,620] Trial 5 finished with value: 1.347370824390586 and parameters: {'feature_set': 'models_plus_raw', 'alpha': 826.0185608286423, 'fit_intercept': True}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:53,077] Trial 6 finished with value: 1.357688532153736 and parameters: {'feature_set': 'models_plus_raw', 'alpha': 3.929417958656645e-06, 'fit_intercept': True}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:53,650] Trial 7 finished with value: 1.3576624873651282 and parameters: {'feature_set': 'models_plus_raw', 'alpha': 0.8901780240435773, 'fit_intercept': True}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:54,089] Trial 8 finished with value: 1.3115401059612992 and parameters: {'feature_set': 'models_only', 'alpha': 2828.538706546869, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:54,538] Trial 9 finished with value: 1.3103671513376955 and parameters: {'feature_set': 'models_only', 'alpha': 35.97860619804126, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:55,009] Trial 10 finished with value: 1.3213200884969503 and parameters: {'feature_set': 'models_only', 'alpha': 1.8087400416300714e-05, 'fit_intercept': True}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:55,443] Trial 11 finished with value: 1.3576885206253257 and parameters: {'feature_set': 'models_plus_raw', 'alpha': 0.00039823854294263674, 'fit_intercept': True}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:55,879] Trial 12 finished with value: 1.3488887676265275 and parameters: {'feature_set': 'models_plus_raw', 'alpha': 0.44507773547737556, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:56,422] Trial 13 finished with value: 1.3489064865120886 and parameters: {'feature_set': 'models_plus_raw', 'alpha': 7.810619739021528e-06, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:56,888] Trial 14 finished with value: 1.3110122781343296 and parameters: {'feature_set': 'models_only', 'alpha': 150.11205568245393, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:57,351] Trial 15 finished with value: 1.359459139163959 and parameters: {'feature_set': 'models_only', 'alpha': 47348.55970369959, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:57,861] Trial 16 finished with value: 1.3096773499598655 and parameters: {'feature_set': 'models_only', 'alpha': 0.015051267754134965, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:58,288] Trial 17 finished with value: 1.3096772424098146 and parameters: {'feature_set': 'models_only', 'alpha': 0.011189458586009535, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:58,785] Trial 18 finished with value: 1.309676942161019 and parameters: {'feature_set': 'models_only', 'alpha': 0.0004116028418844843, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:59,311] Trial 19 finished with value: 1.3096769461931428 and parameters: {'feature_set': 'models_only', 'alpha': 0.0005563112077399992, 'fit_intercept': False}. Best is trial 3 with value: 1.3096769313294738.

[I 2026-07-16 11:20:59,732] Trial 20 finished with value: 1.309676930727474 and parameters: {'feature_set': 'models_only', 'alpha': 1.2750039119563622e-06, 'fit_intercept': False}. Best is trial 20 with value: 1.309676930727474.

[I 2026-07-16 11:21:00,258] Trial 21 finished with value: 1.3096769307214322 and parameters: {'feature_set': 'models_only', 'alpha': 1.0621554554639067e-06, 'fit_intercept': False}. Best is trial 21 with value: 1.3096769307214322.

[I 2026-07-16 11:21:00,749] Trial 22 finished with value: 1.3096769307333547 and parameters: {'feature_set': 'models_only', 'alpha': 1.4799808997599394e-06, 'fit_intercept': False}. Best is trial 21 with value: 1.3096769307214322.

[I 2026-07-16 11:21:01,243] Trial 23 finished with value: 1.3096769307253127 and parameters: {'feature_set': 'models_only', 'alpha': 1.1954283189892882e-06, 'fit_intercept': False}. Best is trial 21 with value: 1.3096769307214322.

[I 2026-07-16 11:21:01,724] Trial 24 finished with value: 1.3096769307207365 and parameters: {'feature_set': 'models_only', 'alpha': 1.0269769586784979e-06, 'fit_intercept': False}. Best is trial 24 with value: 1.3096769307207365.

[I 2026-07-16 11:21:02,273] Trial 25 finished with value: 1.309676932149001 and parameters: {'feature_set': 'models_only', 'alpha': 5.227988225337124e-05, 'fit_intercept': False}. Best is trial 24 with value: 1.3096769307207365.

[I 2026-07-16 11:21:02,828] Trial 26 finished with value: 1.3096769321365214 and parameters: {'feature_set': 'models_only', 'alpha': 5.183634097885746e-05, 'fit_intercept': False}. Best is trial 24 with value: 1.3096769307207365.

[I 2026-07-16 11:21:03,289] Trial 27 finished with value: 1.3096769307204597 and parameters: {'feature_set': 'models_only', 'alpha': 1.020047520160654e-06, 'fit_intercept': False}. Best is trial 27 with value: 1.3096769307204597.

[I 2026-07-16 11:21:03,839] Trial 28 finished with value: 1.3096770259866455 and parameters: {'feature_set': 'models_only', 'alpha': 0.0034201785874661416, 'fit_intercept': False}. Best is trial 27 with value: 1.3096769307204597.

[I 2026-07-16 11:21:04,350] Trial 29 finished with value: 1.3096769328726323 and parameters: {'feature_set': 'models_only', 'alpha': 7.825510837265298e-05, 'fit_intercept': False}. Best is trial 27 with value: 1.3096769307204597.

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
C:\Users\Faris Fadil Arifin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

                  period           method  count     mae_f    rmse_f
0   validation_2024_2025          xgboost   1452  1.444570  1.937097
1   validation_2024_2025         lightgbm   1452  1.403822  1.902358
2   validation_2024_2025         catboost   1452  1.406624  1.904975
3   validation_2024_2025    provider_mean   1452  2.717663  3.648723
4   validation_2024_2025  provider_median   1452  2.344602  3.323749
5   validation_2024_2025          nbm_raw   1452  2.078083  2.977793
6   validation_2024_2025         hrrr_raw   1452  4.924938  6.153463
7   validation_2024_2025          gfs_raw   1452  3.041998  4.098564
8              test_2026          xgboost    170  1.393122  1.808521
9              test_2026         lightgbm    170  1.377104  1.806385
10             test_2026         catboost    170  1.417672  1.864892
11             test_2026      ridge_stack    170  1.371846  1.800089
12             test_2026    provider_mean    170  2.583543  3.303107
13             test_2026  provider_median    170  2.428105  3.214617
14             test_2026          nbm_raw    170  2.045105  2.795566
15             test_2026         hrrr_raw    170  4.927253  5.592931
16             test_2026          gfs_raw    170  2.550131  3.455843

## KDAL Forward-OOF Residual Calibration

In [9]:
calibrated_predictions, residual_calibration, calibration_oof_predictions = (
    kdal_oof_residual_calibrated_stack_predictions(
        result.validation_predictions,
        result.test_predictions,
        result.stack_tuning_results,
        config,
        min_month_rows=60,
        shrinkage_rows=60,
        correction_cap_f=0.75,
    )
)
if calibrated_predictions.empty:
    raise RuntimeError("KDAL OOF residual calibration produced no test predictions.")

calibrated_predictions.to_csv(
    config.resolved_output_dir() / f"{STATION_ID}_oof_calibrated_test_predictions.csv", index=False
)
residual_calibration.to_csv(
    config.resolved_output_dir() / f"{STATION_ID}_oof_residual_calibration.csv", index=False
)
calibration_oof_predictions.to_csv(
    config.resolved_output_dir() / f"{STATION_ID}_stack_calibration_oof_predictions.csv", index=False
)
residual_calibration

,month,month_rows,month_mean_residual_f,global_mean_residual_f,correction_f,selected_param_key,correction_cap_f,min_month_rows,shrinkage_rows
0,1,92,-0.011189,0.158317,0.055721,stack_trial_27,0.75,60,60
1,2,85,0.454676,0.158317,0.332045,stack_trial_27,0.75,60,60
2,3,90,-0.090934,0.158317,0.008767,stack_trial_27,0.75,60,60
3,4,90,-0.439850,0.158317,-0.200583,stack_trial_27,0.75,60,60
4,5,93,0.120205,0.158317,0.135151,stack_trial_27,0.75,60,60
5,6,90,0.038046,0.158317,0.086155,stack_trial_27,0.75,60,60
6,7,93,0.441614,0.158317,0.330517,stack_trial_27,0.75,60,60
7,8,93,0.608301,0.158317,0.431837,stack_trial_27,0.75,60,60
8,9,90,0.603168,0.158317,0.425228,stack_trial_27,0.75,60,60
9,10,93,-0.110704,0.158317,-0.005206,stack_trial_27,0.75,60,60
10,11,90,0.034312,0.158317,0.083914,stack_trial_27,0.75,60,60
11,12,92,0.256016,0.158317,0.217450,stack_trial_27,0.75,60,60

In [10]:
calibrated_error = pd.to_numeric(calibrated_predictions["error_f"], errors="coerce")
calibrated_absolute_error = pd.to_numeric(calibrated_predictions["absolute_error_f"], errors="coerce")
calibrated_metrics = pd.DataFrame([
    {
        "method": "ridge_stack_oof_calibrated",
        "count": int(calibrated_absolute_error.notna().sum()),
        "mae_f": float(calibrated_absolute_error.mean()),
        "rmse_f": float(np.sqrt(np.mean(np.square(calibrated_error.dropna())))),
        "bias_f": float(calibrated_error.mean()),
        "p95_absolute_error_f": float(calibrated_absolute_error.quantile(0.95)),
        "large_error_5f_pct": float(calibrated_absolute_error.ge(5.0).mean() * 100.0),
        "within_1f_pct": float(calibrated_absolute_error.le(1.0).mean() * 100.0),
        "within_2f_pct": float(calibrated_absolute_error.le(2.0).mean() * 100.0),
        "within_3f_pct": float(calibrated_absolute_error.le(3.0).mean() * 100.0),
    }
])
calibrated_metrics.to_csv(
    config.resolved_output_dir() / f"{STATION_ID}_oof_calibrated_metrics.csv", index=False
)
calibrated_metrics

,method,count,mae_f,rmse_f,bias_f,p95_absolute_error_f,large_error_5f_pct,within_1f_pct,within_2f_pct,within_3f_pct
0,ridge_stack_oof_calibrated,170,1.358732,1.787453,0.26462,3.708212,1.764706,51.176471,74.705882,90.588235

In [11]:
if EXPORT_MODEL_WEIGHTS:
    exported_weights = export_station_model_weights(
        project_root=PROJECT_ROOT,
        station_id=STATION_ID,
        artifact_dir=config.resolved_output_dir(),
        model_version=MODEL_VERSION,
        timing_mode=config.timing_mode,
        providers=tuple(config.providers),
        feature_version=config.effective_feature_version,
        optuna_metric=config.effective_optuna_metric,
        target_mode=config.effective_target_mode,
        target_source=config.effective_target_source,
        base_model_methods=tuple(config.effective_base_model_methods),
        stack_enabled=config.stack_enabled,
        source_pipeline="notebooks/station_stacking_v20_kdal_fix",
    )

    exported_weights.bundle_path, exported_weights.manifest_path
else:
    print("Model export disabled for this experimental notebook.")

Model export disabled for this experimental notebook.

## V11 Feature Coverage

In [12]:
v11_feature_coverage = (
    result.features[V11_FEATURE_COLUMNS]
    .notna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .rename("coverage_pct")
    .reset_index()
    .rename(columns={"index": "feature"})
)

v11_feature_coverage

                                              feature  coverage_pct
0                              v4_observed_precip_any    100.000000
1                        v4_forecast_wet_observed_dry    100.000000
2                   v4_forecast_observed_precip_match    100.000000
3                              v4_all_forecast_precip    100.000000
4                              v4_any_forecast_precip    100.000000
5                          climatology_high_10y_std_f    100.000000
6                              climatology_high_10y_f    100.000000
7                          climatology_high_10y_count    100.000000
8                     v8_month_remaining_warmup_count    100.000000
9                        v4_observed_wet_forecast_dry    100.000000
10              v8_recent_remaining_warmup_30d_mean_f     99.752598
11                          v2_recent_heat_momentum_f     99.653637
12                           v2_recent_heat_anomaly_f     99.059871
13               v8_recent_remaining_warmup_7d_mean_f     99.059871
14                     v3_high_so_far_above_current_f     98.911430
15       v8_provider_max_remaining_from_high_so_far_f     98.911430
16          v8_provider_spread_per_remaining_warmup_f     98.911430
17    v8_provider_median_remaining_from_high_so_far_f     98.911430
18            observed_high_so_far_change_since_9am_f     98.911430
19                   v3_remaining_warmup_per_spread_f     98.911430
20           v3_humidity_remaining_warmup_interaction     98.911430
21             v3_remaining_warmup_from_high_so_far_f     98.911430
22       v8_provider_min_remaining_from_high_so_far_f     98.911430
23                   v2_morning_warmup_to_consensus_f     98.911430
24                     v2_humidity_warmup_interaction     98.911430
25                             v2_spread_per_warmup_f     98.911430
26       observed_high_so_far_minus_climatology_10y_f     98.911430
27              observed_temp_minus_climatology_10y_f     98.911430
28            observed_morning_warmup_rate_f_per_hour     98.911430
29                     observed_temp_change_last_3h_f     98.911430
30              provider_mean_minus_climatology_10y_f     98.911430
31                     observed_temp_change_last_1h_f     98.911430
32                   v8_month_remaining_warmup_mean_f     98.812469
33                     v2_consensus_minus_7d_actual_f     98.812469
34                   v3_high_so_far_minus_7d_actual_f     98.812469
35                   v4_observed_precip_recent_mm_est     98.812469
36                      v3_high_so_far_minus_lag_1d_f     98.515586
37       v8_provider_mean_remaining_vs_month_normal_f     97.723899
38      v8_dewpoint_mean_remaining_warmup_interaction     79.069767
39  v8_dewpoint_depression_remaining_warmup_intera...     79.069767
40                        v8_forecast_dewpoint_mean_f     79.069767
41             v8_forecast_dewpoint_depression_mean_f     79.069767
42             v4_precip_remaining_warmup_interaction     78.624443
43                   v4_forecast_precip_intensity_max     78.624443
44                   v4_forecast_precip_total_mean_mm     78.624443
45                    v4_forecast_precip_total_max_mm     78.624443
46                 v4_forecast_precip_total_spread_mm     78.624443
47                  v4_forecast_precip_max_1h_mean_mm     78.624443
48                      v4_forecast_precip_hours_mean     78.624443
49                  v4_forecast_precip_intensity_mean     78.624443
50       v8_precip_total_remaining_warmup_interaction     78.624443
51                     v4_precip_humidity_interaction     78.624443
52      v8_precip_max_1h_remaining_warmup_interaction     78.624443
53         v4_forecast_total_minus_observed_recent_mm     78.525482
54    v8_cloud_cover_max_remaining_warmup_interaction     64.423553
55   v8_cloud_cover_mean_remaining_warmup_interaction     64.423553
56    v8_wind_speed_mean_remaining_warmup_interaction     35.823850
57      v8_wind_gust_max_remaining_warmup_interaction     35.823850

In [13]:
result.feature_columns.loc[result.feature_columns["feature"].isin(V11_FEATURE_COLUMNS)]

                                              feature     kind
3                      observed_temp_change_last_1h_f  numeric
4                      observed_temp_change_last_3h_f  numeric
5             observed_morning_warmup_rate_f_per_hour  numeric
6             observed_high_so_far_change_since_9am_f  numeric
26                           v2_recent_heat_anomaly_f  numeric
27                          v2_recent_heat_momentum_f  numeric
28                   v2_morning_warmup_to_consensus_f  numeric
29                     v2_consensus_minus_7d_actual_f  numeric
30                             v2_spread_per_warmup_f  numeric
31                     v2_humidity_warmup_interaction  numeric
32                     v3_high_so_far_above_current_f  numeric
33             v3_remaining_warmup_from_high_so_far_f  numeric
34                      v3_high_so_far_minus_lag_1d_f  numeric
35                   v3_high_so_far_minus_7d_actual_f  numeric
36                   v3_remaining_warmup_per_spread_f  numeric
37           v3_humidity_remaining_warmup_interaction  numeric
38                   v4_forecast_precip_total_mean_mm  numeric
39                    v4_forecast_precip_total_max_mm  numeric
40                 v4_forecast_precip_total_spread_mm  numeric
41                  v4_forecast_precip_max_1h_mean_mm  numeric
42                      v4_forecast_precip_hours_mean  numeric
43                  v4_forecast_precip_intensity_mean  numeric
44                   v4_forecast_precip_intensity_max  numeric
45                             v4_any_forecast_precip  numeric
46                             v4_all_forecast_precip  numeric
47                             v4_observed_precip_any  numeric
48                   v4_observed_precip_recent_mm_est  numeric
49         v4_forecast_total_minus_observed_recent_mm  numeric
50                  v4_forecast_observed_precip_match  numeric
51                       v4_forecast_wet_observed_dry  numeric
52                       v4_observed_wet_forecast_dry  numeric
53                     v4_precip_humidity_interaction  numeric
54             v4_precip_remaining_warmup_interaction  numeric
55       v8_provider_max_remaining_from_high_so_far_f  numeric
56       v8_provider_min_remaining_from_high_so_far_f  numeric
57    v8_provider_median_remaining_from_high_so_far_f  numeric
58          v8_provider_spread_per_remaining_warmup_f  numeric
59                   v8_month_remaining_warmup_mean_f  numeric
60                    v8_month_remaining_warmup_count  numeric
61               v8_recent_remaining_warmup_7d_mean_f  numeric
62              v8_recent_remaining_warmup_30d_mean_f  numeric
63       v8_provider_mean_remaining_vs_month_normal_f  numeric
64   v8_cloud_cover_mean_remaining_warmup_interaction  numeric
65    v8_cloud_cover_max_remaining_warmup_interaction  numeric
66       v8_precip_total_remaining_warmup_interaction  numeric
67      v8_precip_max_1h_remaining_warmup_interaction  numeric
68    v8_wind_speed_mean_remaining_warmup_interaction  numeric
69      v8_wind_gust_max_remaining_warmup_interaction  numeric
70                        v8_forecast_dewpoint_mean_f  numeric
71             v8_forecast_dewpoint_depression_mean_f  numeric
72      v8_dewpoint_mean_remaining_warmup_interaction  numeric
73  v8_dewpoint_depression_remaining_warmup_intera...  numeric
94                             climatology_high_10y_f  numeric
95                         climatology_high_10y_std_f  numeric
96                         climatology_high_10y_count  numeric
97              provider_mean_minus_climatology_10y_f  numeric
98              observed_temp_minus_climatology_10y_f  numeric
99       observed_high_so_far_minus_climatology_10y_f  numeric

## Dropped Feature Check

In [14]:
dropped_present = result.feature_columns.loc[
    result.feature_columns["feature"].isin(V11_DROPPED_FEATURE_COLUMNS)
]

dropped_present

Empty DataFrame
Columns: [feature, kind]
Index: []

## Morning Trend Coverage

In [15]:
trend_coverage = (
    result.features[TREND_COLUMNS]
    .notna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .rename("coverage_pct")
    .reset_index()
    .rename(columns={"index": "feature"})
)

trend_coverage

                                   feature  coverage_pct
0           observed_temp_change_last_1h_f      98.91143
1           observed_temp_change_last_3h_f      98.91143
2  observed_morning_warmup_rate_f_per_hour      98.91143
3  observed_high_so_far_change_since_9am_f      98.91143

## Rounded Within 1F Accuracy

In [16]:
preds = pd.concat(
    [
        result.validation_predictions.assign(period="validation_2024_2025"),
        result.test_predictions.assign(period="oof_2026"),
    ],
    ignore_index=True,
)

predicted_high = pd.to_numeric(preds["predicted_high_f"], errors="coerce")
preds["predicted_high_rounded_f"] = np.floor(predicted_high + 0.5)
preds["within_1f_after_round"] = (
    pd.to_numeric(preds["actual_high_f"], errors="coerce") - preds["predicted_high_rounded_f"]
).abs().le(1)

within_1f_accuracy_by_period = (
    preds
    .dropna(subset=["actual_high_f", "predicted_high_rounded_f"])
    .groupby(["period", "method"], as_index=False)
    .agg(
        count=("within_1f_after_round", "size"),
        within_1f_count=("within_1f_after_round", "sum"),
        within_1f_accuracy_pct=("within_1f_after_round", lambda x: x.mean() * 100),
    )
    .sort_values(["period", "within_1f_accuracy_pct"], ascending=[True, False])
)

within_1f_accuracy_by_period

,period,method,count,within_1f_count,within_1f_accuracy_pct
0,oof_2026,catboost,170,108,63.529412
7,oof_2026,ridge_stack,170,108,63.529412
3,oof_2026,lightgbm,170,104,61.176471
8,oof_2026,xgboost,170,103,60.588235
4,oof_2026,nbm_raw,170,84,49.411765
1,oof_2026,gfs_raw,170,69,40.588235
6,oof_2026,provider_median,170,69,40.588235
5,oof_2026,provider_mean,170,57,33.529412
2,oof_2026,hrrr_raw,170,17,10.000000
9,validation_2024_2025,catboost,1452,920,63.360882
12,validation_2024_2025,lightgbm,1452,915,63.016529
16,validation_2024_2025,xgboost,1452,896,61.707989
13,validation_2024_2025,nbm_raw,1452,707,48.691460
15,validation_2024_2025,provider_median,1452,630,43.388430
14,validation_2024_2025,provider_mean,1452,474,32.644628
10,validation_2024_2025,gfs_raw,1452,463,31.887052
11,validation_2024_2025,hrrr_raw,1452,234,16.115702

## Version Comparison

In [17]:
comparison_frames = []
for version, folder in [
    ("v1", PROJECT_ROOT / "data" / "calibration" / "station_stacking"),
    ("v2", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v2"),
    ("v3", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v3"),
    ("v4", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v4"),
    ("v5", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v5"),
    ("v6", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v6"),
    ("v7", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v7"),
    ("v8", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v8"),
    ("v9", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v9"),
    ("v10", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v10"),
    ("v11", PROJECT_ROOT / "data" / "calibration" / "station_stacking_v11"),
]:
    path = folder / f"{STATION_ID}_year_split_scoreboard.csv"
    if path.exists():
        frame = pd.read_csv(path)
        frame["version"] = version
        comparison_frames.append(frame)

version_comparison = pd.concat(comparison_frames, ignore_index=True) if comparison_frames else pd.DataFrame()
if not version_comparison.empty:
    version_comparison = version_comparison.sort_values(["period", "mae_f", "version", "method"]).reset_index(drop=True)
version_comparison

                  period       method  count     mae_f    rmse_f version
0              test_2026  ridge_stack    138  1.369446  1.890651      v9
1              test_2026      xgboost    138  1.402066  1.889472     v11
2              test_2026      xgboost    138  1.419940  1.895994      v9
3              test_2026  ridge_stack    138  1.429989  1.907881     v11
4              test_2026     lightgbm    138  1.454606  1.932482     v11
..                   ...          ...    ...       ...       ...     ...
83  validation_2024_2025     hrrr_raw    660  5.477361  6.266007      v3
84  validation_2024_2025     hrrr_raw    668  5.486824  6.274688      v7
85  validation_2024_2025     hrrr_raw    606  5.497186  6.283967      v5
86  validation_2024_2025     hrrr_raw    606  5.497186  6.283967      v6
87  validation_2024_2025     hrrr_raw    623  5.564150  6.352240      v1

[88 rows x 6 columns]

## 2026 OOF Weather Brackets

In [18]:
result.bracket_metrics

,method,count,mae_f,rmse_f,bucket_log_loss,bracket_accuracy_pct,p95_absolute_error_f,large_miss_5f_pct
0,xgboost,170,1.393122,1.808521,1.372603,43.529412,3.435454,1.176471
1,lightgbm,170,1.377104,1.806385,1.368934,45.294118,3.656903,1.176471
2,catboost,170,1.417672,1.864892,1.400749,43.529412,3.712265,2.352941
3,ridge_stack,170,1.371846,1.800089,1.356020,42.941176,3.742628,1.764706
4,provider_mean,170,2.583543,3.303107,1.678281,23.529412,5.481044,8.235294
5,provider_median,170,2.428105,3.214617,1.757808,22.941176,5.950489,8.823529
6,nbm_raw,170,2.045105,2.795566,1.726940,34.117647,5.718984,8.235294
7,hrrr_raw,170,4.927253,5.592931,1.838395,5.294118,9.733436,45.294118
8,gfs_raw,170,2.550131,3.455843,1.948382,27.058824,6.385804,11.176471

## Train-Fold 3% Missingness Audit

In [19]:
modeling_frame, candidate_categorical, candidate_numeric = _modeling_frame(result.features, config)
candidate_features = [*candidate_categorical, *candidate_numeric]
audit_specs = [
    (fold.name, fold.train_start_year, fold.train_end_year)
    for fold in V20_EXPANDING_FOLDS
] + [("test_refit_2021_2025", 2021, 2025)]

missingness_rows = []
years = pd.to_numeric(modeling_frame["year"], errors="coerce")
for fold_name, train_start, train_end in audit_specs:
    train = modeling_frame.loc[years.between(train_start, train_end)].copy()
    retained_categorical, retained_numeric = _fit_feature_columns(
        train,
        candidate_categorical,
        candidate_numeric,
        max_missing_fraction=config.effective_max_feature_missing_fraction,
    )
    retained = set(retained_categorical) | set(retained_numeric)
    for feature in candidate_features:
        numeric_feature = feature in candidate_numeric
        values = pd.to_numeric(train[feature], errors="coerce") if numeric_feature else train[feature]
        missingness_rows.append(
            {
                "fold": fold_name,
                "train_start_year": train_start,
                "train_end_year": train_end,
                "feature": feature,
                "kind": "numeric" if numeric_feature else "categorical",
                "missing_fraction": float(values.isna().mean()),
                "retained": feature in retained,
            }
        )

fold_feature_missingness = pd.DataFrame(missingness_rows)
retained_dropped_summary = (
    fold_feature_missingness.groupby(["fold", "retained"], as_index=False)
    .agg(feature_count=("feature", "nunique"), maximum_missing_fraction=("missing_fraction", "max"))
)
fold_feature_missingness.to_csv(config.resolved_output_dir() / f"{STATION_ID}_fold_feature_missingness.csv", index=False)
retained_dropped_summary, fold_feature_missingness.loc[~fold_feature_missingness["retained"]].sort_values(
    ["fold", "missing_fraction"], ascending=[True, False]
)

(                     fold  retained  feature_count  maximum_missing_fraction
 0  fold_2021_2022_to_2023     False             24                  0.915278
 1  fold_2021_2022_to_2023      True             76                  0.006944
 2  fold_2021_2023_to_2024     False             22                  0.907664
 3  fold_2021_2023_to_2024      True             78                  0.022161
 4  fold_2021_2024_to_2025     False             22                  0.911541
 5  fold_2021_2024_to_2025      True             78                  0.016586
 6       fold_2021_to_2022     False             24                  0.896936
 7       fold_2021_to_2022      True             76                  0.013928
 8    test_refit_2021_2025     False             22                  0.915516
 9    test_refit_2021_2025      True             78                  0.013252,
                        fold  train_start_year  train_end_year  \
 101  fold_2021_2022_to_2023              2021            2022
 168  fold_2021_2022_to_2023              2021            2022
 169  fold_2021_2022_to_2023              2021            2022
 164  fold_2021_2022_to_2023              2021            2022
 165  fold_2021_2022_to_2023              2021            2022
 ..                      ...               ...             ...
 470    test_refit_2021_2025              2021            2025
 471    test_refit_2021_2025              2021            2025
 472    test_refit_2021_2025              2021            2025
 473    test_refit_2021_2025              2021            2025
 412    test_refit_2021_2025              2021            2025

                                                feature         kind  \
 101                     observed_weather_code_at_as_of  categorical
 168    v8_wind_speed_mean_remaining_warmup_interaction      numeric
 169      v8_wind_gust_max_remaining_warmup_interaction      numeric
 164   v8_cloud_cover_mean_remaining_warmup_interaction      numeric
 165    v8_cloud_cover_max_remaining_warmup_interaction      numeric
 ..                                                 ...          ...
 470                        v8_forecast_dewpoint_mean_f      numeric
 471             v8_forecast_dewpoint_depression_mean_f      numeric
 472      v8_dewpoint_mean_remaining_warmup_interaction      numeric
 473  v8_dewpoint_depression_remaining_warmup_intera...      numeric
 412                       nbm_cooling_onset_hour_local      numeric

      missing_fraction  retained
 101          0.915278     False
 168          0.413889     False
 169          0.413889     False
 164          0.350000     False
 165          0.350000     False
 ..                ...       ...
 470          0.133076     False
 471          0.133076     False
 472          0.133076     False
 473          0.133076     False
 412          0.078962     False

 [114 rows x 7 columns])

## Expanded 11 AM Feature Coverage and Provider Count

In [20]:
new_feature_coverage = (
    result.features[V11_SETTLEMENT_FIX_TEMP_FEATURE_COLUMNS]
    .notna()
    .mean()
    .mul(100)
    .rename("coverage_pct")
    .reset_index()
    .rename(columns={"index": "feature"})
)
provider_count_coverage = (
    result.features["v11sf_forecast_temp_11am_provider_count"]
    .value_counts(dropna=False)
    .sort_index()
    .rename_axis("available_provider_count")
    .reset_index(name="row_count")
)
provider_count_coverage["row_pct"] = provider_count_coverage["row_count"] / len(result.features) * 100
new_feature_coverage.to_csv(config.resolved_output_dir() / f"{STATION_ID}_11am_feature_coverage.csv", index=False)
new_feature_coverage, provider_count_coverage

(                                              feature  coverage_pct
 0                     v11sf_forecast_temp_11am_mean_f      98.91143
 1                   v11sf_forecast_temp_11am_median_f      98.91143
 2           v11sf_forecast_temp_11am_minus_observed_f      98.91143
 3                v11sf_forecast_temp_11am_abs_error_f      98.91143
 4               v11sf_forecast_temp_11am_warm_error_f      98.91143
 5               v11sf_forecast_temp_11am_cool_error_f      98.91143
 6                   v11sf_forecast_temp_11am_spread_f      98.91143
 7             v11sf_forecast_temp_11am_provider_count     100.00000
 8   v11sf_forecast_temp_bias_remaining_warmup_inte...      98.91143
 9          v11sf_observation_adjusted_provider_high_f      98.91143
 10                 v11sf_forecast_warmup_after_11am_f      98.91143,
    available_provider_count  row_count    row_pct
 0                         0         22   1.088570
 1                         1         23   1.138050
 2                         2        349  17.268679
 3                         3       1627  80.504701)

## New-Feature Importance

In [21]:
new_feature_importance = result.feature_importance.loc[
    result.feature_importance["feature"].isin(V11_SETTLEMENT_FIX_TEMP_FEATURE_COLUMNS)
].sort_values(["method", "importance_mean_mae_f"], ascending=[True, False])
new_feature_importance

,method,param_key,feature,importance_mean_mae_f,importance_std_mae_f,n_repeats,train_start_year,train_end_year,test_year,train_rows,test_rows
21,catboost,trial_20,v11sf_forecast_temp_11am_median_f,0.050684,0.022572,10,2021,2025,2026,1811,170
29,catboost,trial_20,v11sf_observation_adjusted_provider_high_f,0.032357,0.020129,10,2021,2025,2026,1811,170
46,catboost,trial_20,v11sf_forecast_warmup_after_11am_f,0.017596,0.016837,10,2021,2025,2026,1811,170
64,catboost,trial_20,v11sf_forecast_temp_11am_minus_observed_f,0.009965,0.003971,10,2021,2025,2026,1811,170
67,catboost,trial_20,v11sf_forecast_temp_11am_mean_f,0.009887,0.007188,10,2021,2025,2026,1811,170
77,catboost,trial_20,v11sf_forecast_temp_11am_spread_f,0.007513,0.004547,10,2021,2025,2026,1811,170
93,catboost,trial_20,v11sf_forecast_temp_bias_remaining_warmup_inte...,0.004768,0.006900,10,2021,2025,2026,1811,170
95,catboost,trial_20,v11sf_forecast_temp_11am_warm_error_f,0.004589,0.003834,10,2021,2025,2026,1811,170
160,catboost,trial_20,v11sf_forecast_temp_11am_provider_count,0.000000,0.000000,10,2021,2025,2026,1811,170
214,catboost,trial_20,v11sf_forecast_temp_11am_abs_error_f,-0.002478,0.005585,10,2021,2025,2026,1811,170
224,catboost,trial_20,v11sf_forecast_temp_11am_cool_error_f,-0.005213,0.008587,10,2021,2025,2026,1811,170
57,lightgbm,trial_25,v11sf_forecast_warmup_after_11am_f,0.012557,0.008030,10,2021,2025,2026,1811,170
99,lightgbm,trial_25,v11sf_observation_adjusted_provider_high_f,0.003611,0.001917,10,2021,2025,2026,1811,170
100,lightgbm,trial_25,v11sf_forecast_temp_bias_remaining_warmup_inte...,0.003550,0.004387,10,2021,2025,2026,1811,170
118,lightgbm,trial_25,v11sf_forecast_temp_11am_minus_observed_f,0.001852,0.001499,10,2021,2025,2026,1811,170
124,lightgbm,trial_25,v11sf_forecast_temp_11am_median_f,0.001411,0.000773,10,2021,2025,2026,1811,170
134,lightgbm,trial_25,v11sf_forecast_temp_11am_warm_error_f,0.000789,0.000612,10,2021,2025,2026,1811,170
135,lightgbm,trial_25,v11sf_forecast_temp_11am_mean_f,0.000739,0.001427,10,2021,2025,2026,1811,170
137,lightgbm,trial_25,v11sf_forecast_temp_11am_cool_error_f,0.000689,0.000841,10,2021,2025,2026,1811,170
169,lightgbm,trial_25,v11sf_forecast_temp_11am_provider_count,0.000000,0.000000,10,2021,2025,2026,1811,170
201,lightgbm,trial_25,v11sf_forecast_temp_11am_spread_f,-0.001105,0.001324,10,2021,2025,2026,1811,170
208,lightgbm,trial_25,v11sf_forecast_temp_11am_abs_error_f,-0.001820,0.001412,10,2021,2025,2026,1811,170
15,xgboost,trial_26,v11sf_forecast_warmup_after_11am_f,0.074840,0.020978,10,2021,2025,2026,1811,170
51,xgboost,trial_26,v11sf_forecast_temp_11am_spread_f,0.016200,0.005404,10,2021,2025,2026,1811,170
63,xgboost,trial_26,v11sf_forecast_temp_11am_minus_observed_f,0.011239,0.005462,10,2021,2025,2026,1811,170
75,xgboost,trial_26,v11sf_forecast_temp_bias_remaining_warmup_inte...,0.007823,0.016483,10,2021,2025,2026,1811,170
86,xgboost,trial_26,v11sf_forecast_temp_11am_abs_error_f,0.005430,0.007444,10,2021,2025,2026,1811,170
88,xgboost,trial_26,v11sf_forecast_temp_11am_cool_error_f,0.005191,0.004787,10,2021,2025,2026,1811,170
96,xgboost,trial_26,v11sf_observation_adjusted_provider_high_f,0.004433,0.005142,10,2021,2025,2026,1811,170
108,xgboost,trial_26,v11sf_forecast_temp_11am_median_f,0.002592,0.003784,10,2021,2025,2026,1811,170
127,xgboost,trial_26,v11sf_forecast_temp_11am_warm_error_f,0.001123,0.002910,10,2021,2025,2026,1811,170
177,xgboost,trial_26,v11sf_forecast_temp_11am_provider_count,0.000000,0.000000,10,2021,2025,2026,1811,170
206,xgboost,trial_26,v11sf_forecast_temp_11am_mean_f,-0.001673,0.005078,10,2021,2025,2026,1811,170

## 2026 Monthly Metrics

In [22]:
monthly_predictions = result.test_predictions.copy()
monthly_predictions["month"] = pd.to_datetime(monthly_predictions["contract_date"], errors="coerce").dt.month
monthly_metrics = (
    monthly_predictions.dropna(subset=["month", "error_f"])
    .groupby(["method", "month"], as_index=False)
    .agg(
        count=("error_f", "size"),
        mae_f=("absolute_error_f", "mean"),
        rmse_f=("error_f", lambda values: float(np.sqrt(np.mean(np.square(values))))),
        bias_f=("error_f", "mean"),
    )
)
monthly_metrics.to_csv(config.resolved_output_dir() / f"{STATION_ID}_2026_monthly_metrics.csv", index=False)
monthly_metrics

             method  month  count     mae_f    rmse_f    bias_f
0          catboost      1     31  1.270353  1.745002  0.350432
1          catboost      2     28  1.279802  1.487835  0.244155
2          catboost      3     30  1.857212  2.265888  0.669492
3          catboost      4     29  1.170218  1.598603  0.033795
4          catboost      5     31  1.470230  2.118021 -0.039316
5          catboost      6     21  1.455194  1.794795 -0.103470
6           gfs_raw      1     31  2.272084  2.918034  1.454306
7           gfs_raw      2     28  2.593110  3.145965  2.344093
8           gfs_raw      3     30  2.316502  3.900639  1.927191
9           gfs_raw      4     29  2.979966  3.917502  1.035080
10          gfs_raw      5     31  2.462938  3.057074 -1.313341
11          gfs_raw      6     21  2.772160  3.766890 -1.882365
12         hrrr_raw      1     31  5.097723  5.694206  5.049364
13         hrrr_raw      2     28  5.920618  6.503826  5.863340
14         hrrr_raw      3     30  6.576098  7.210073  6.153609
15         hrrr_raw      4     29  3.755997  4.410109  3.527816
16         hrrr_raw      5     31  3.868945  4.347534  3.544661
17         hrrr_raw      6     21  4.175339  4.465224  4.175339
18         lightgbm      1     31  1.227776  1.622406  0.195752
19         lightgbm      2     28  1.305492  1.651344  0.340870
20         lightgbm      3     30  1.679445  2.078116  0.355620
21         lightgbm      4     29  1.166790  1.593688 -0.390659
22         lightgbm      5     31  1.458202  1.996763 -0.061153
23         lightgbm      6     21  1.431827  1.825096 -0.002118
24          nbm_raw      1     31  2.297808  3.062490  1.490712
25          nbm_raw      2     28  1.700431  2.032226  0.986146
26          nbm_raw      3     30  2.190935  3.409878  0.707346
27          nbm_raw      4     29  1.624618  2.487355 -0.159503
28          nbm_raw      5     31  2.302316  2.748128  1.340644
29          nbm_raw      6     21  2.124280  2.758901  1.330953
30    provider_mean      1     31  3.035519  3.483475  2.664794
31    provider_mean      2     28  3.086386  3.616570  3.064526
32    provider_mean      3     30  3.201143  4.272842  2.929382
33    provider_mean      4     29  2.180801  3.090271  1.467798
34    provider_mean      5     31  1.893032  2.356121  1.190655
35    provider_mean      6     21  1.939093  2.346607  1.207976
36  provider_median      1     31  2.393357  2.984986  1.813582
37  provider_median      2     28  2.587368  3.146662  2.336346
38  provider_median      3     30  2.695185  4.114605  1.986193
39  provider_median      4     29  2.354510  3.278241  1.208679
40  provider_median      5     31  2.272063  2.684389  1.418412
41  provider_median      6     21  2.217485  2.763204  1.434635
42      ridge_stack      1     31  1.245201  1.673381  0.417561
43      ridge_stack      2     28  1.300649  1.568982  0.454718
44      ridge_stack      3     30  1.690268  2.134750  0.641275
45      ridge_stack      4     29  1.100546  1.489516  0.001201
46      ridge_stack      5     31  1.438063  2.038174  0.190027
47      ridge_stack      6     21  1.475744  1.763191  0.267366
48          xgboost      1     31  1.265087  1.739719  0.076933
49          xgboost      2     28  1.289407  1.541293 -0.065464
50          xgboost      3     30  1.614138  2.037190 -0.073355
51          xgboost      4     29  1.243174  1.592068 -0.523892
52          xgboost      5     31  1.535671  2.104278 -0.229908
53          xgboost      6     21  1.401316  1.696045  0.023359

## Performance by Warm/Cool 11 AM Forecast Delta

In [23]:
delta_by_date = result.features[[
    "contract_date",
    "v11sf_forecast_temp_11am_minus_observed_f",
]].copy()
delta_predictions = result.test_predictions.merge(delta_by_date, on="contract_date", how="left")
delta_predictions["forecast_temp_delta_bucket"] = pd.cut(
    delta_predictions["v11sf_forecast_temp_11am_minus_observed_f"],
    bins=[-np.inf, -2.0, -0.5, 0.5, 2.0, np.inf],
    labels=["cool_gt_2f", "cool_0.5_to_2f", "near_match", "warm_0.5_to_2f", "warm_gt_2f"],
)
warm_cool_metrics = (
    delta_predictions.dropna(subset=["forecast_temp_delta_bucket", "error_f"])
    .groupby(["method", "forecast_temp_delta_bucket"], observed=True, as_index=False)
    .agg(count=("error_f", "size"), mae_f=("absolute_error_f", "mean"), bias_f=("error_f", "mean"))
)
warm_cool_metrics.to_csv(config.resolved_output_dir() / f"{STATION_ID}_warm_cool_delta_metrics.csv", index=False)
warm_cool_metrics

             method forecast_temp_delta_bucket  count     mae_f    bias_f
0          catboost                 cool_gt_2f     44  1.579404  0.230000
1          catboost             cool_0.5_to_2f     61  1.291800  0.365971
2          catboost                 near_match     30  1.346123  0.111178
3          catboost             warm_0.5_to_2f     27  1.440414  0.409092
4          catboost                 warm_gt_2f      8  1.679477 -1.431515
5           gfs_raw                 cool_gt_2f     44  2.320652  1.990974
6           gfs_raw             cool_0.5_to_2f     61  2.575091  0.574414
7           gfs_raw                 near_match     30  1.737724  0.214046
8           gfs_raw             warm_0.5_to_2f     27  2.405779  0.065448
9           gfs_raw                 warm_gt_2f      8  7.155651 -1.565332
10         hrrr_raw                 cool_gt_2f     44  5.681803  5.513503
11         hrrr_raw             cool_0.5_to_2f     61  4.816010  4.775554
12         hrrr_raw                 near_match     30  4.264444  4.081129
13         hrrr_raw             warm_0.5_to_2f     27  5.110833  4.641401
14         hrrr_raw                 warm_gt_2f      8  3.491401  2.941342
15         lightgbm                 cool_gt_2f     44  1.470491  0.162298
16         lightgbm             cool_0.5_to_2f     61  1.372210  0.217729
17         lightgbm                 near_match     30  1.299176 -0.061496
18         lightgbm             warm_0.5_to_2f     27  1.214326  0.274553
19         lightgbm                 warm_gt_2f      8  1.742403 -1.622335
20          nbm_raw                 cool_gt_2f     44  2.249912  1.607916
21          nbm_raw             cool_0.5_to_2f     61  1.785699  0.942561
22          nbm_raw                 near_match     30  1.410870  0.232474
23          nbm_raw             warm_0.5_to_2f     27  2.273411  0.999484
24          nbm_raw                 warm_gt_2f      8  4.504478 -0.284484
25    provider_mean                 cool_gt_2f     44  3.194849  3.037464
26    provider_mean             cool_0.5_to_2f     61  2.373537  2.097510
27    provider_mean                 near_match     30  1.820746  1.509216
28    provider_mean             warm_0.5_to_2f     27  2.348047  1.902111
29    provider_mean                 warm_gt_2f      8  4.477953  0.363842
30  provider_median                 cool_gt_2f     44  2.736250  2.526214
31  provider_median             cool_0.5_to_2f     61  2.206821  1.730982
32  provider_median                 near_match     30  1.661462  1.032189
33  provider_median             warm_0.5_to_2f     27  2.478296  1.472154
34  provider_median                 warm_gt_2f      8  5.126110  0.364650
35      ridge_stack                 cool_gt_2f     44  1.478581  0.366403
36      ridge_stack             cool_0.5_to_2f     61  1.371856  0.484794
37      ridge_stack                 near_match     30  1.257472  0.170284
38      ridge_stack             warm_0.5_to_2f     27  1.256068  0.567296
39      ridge_stack                 warm_gt_2f      8  1.604382 -1.208072
40          xgboost                 cool_gt_2f     44  1.496734 -0.204338
41          xgboost             cool_0.5_to_2f     61  1.416851 -0.014842
42          xgboost                 near_match     30  1.468394 -0.390092
43          xgboost             warm_0.5_to_2f     27  1.111164  0.281414
44          xgboost                 warm_gt_2f      8  1.311647 -1.184674

## Common-Date Comparison with Existing V11 Settlement Fix

In [24]:
baseline_path = (
    PROJECT_ROOT
    / "data"
    / "calibration"
    / "station_stacking_v11_settlement_fix"
    / f"{STATION_ID}_year_split_test_predictions.csv"
)
baseline_predictions = pd.read_csv(baseline_path)
baseline_predictions["contract_date"] = baseline_predictions["contract_date"].astype(str).str[:10]
v20_predictions = result.test_predictions.copy()
v20_predictions["contract_date"] = v20_predictions["contract_date"].astype(str).str[:10]
comparison = baseline_predictions.merge(
    v20_predictions,
    on=["contract_date", "method"],
    suffixes=("_baseline", "_v20"),
)
comparison["baseline_abs_error_f"] = (
    pd.to_numeric(comparison["actual_high_f_baseline"], errors="coerce")
    - pd.to_numeric(comparison["predicted_high_f_baseline"], errors="coerce")
).abs()
comparison["v20_abs_error_f"] = (
    pd.to_numeric(comparison["actual_high_f_v20"], errors="coerce")
    - pd.to_numeric(comparison["predicted_high_f_v20"], errors="coerce")
).abs()
common_date_comparison = (
    comparison.groupby("method", as_index=False)
    .agg(
        common_date_count=("contract_date", "size"),
        baseline_mae_f=("baseline_abs_error_f", "mean"),
        v20_mae_f=("v20_abs_error_f", "mean"),
        v20_better_days=("v20_abs_error_f", lambda values: int((values < comparison.loc[values.index, "baseline_abs_error_f"]).sum())),
        baseline_better_days=("v20_abs_error_f", lambda values: int((values > comparison.loc[values.index, "baseline_abs_error_f"]).sum())),
    )
)
common_date_comparison["v20_delta_mae_f"] = common_date_comparison["v20_mae_f"] - common_date_comparison["baseline_mae_f"]
common_date_comparison.to_csv(config.resolved_output_dir() / f"{STATION_ID}_v11_common_date_comparison.csv", index=False)
common_date_comparison.sort_values("v20_delta_mae_f")

,method,common_date_count,baseline_mae_f,v20_mae_f,v20_better_days,baseline_better_days,v20_delta_mae_f
1,gfs_raw,170,2.550131,2.550131,0,0,0.000000
2,hrrr_raw,170,4.927253,4.927253,0,0,0.000000
5,provider_mean,170,2.583543,2.583543,2,6,0.000000
4,nbm_raw,170,2.045105,2.045105,0,0,0.000000
6,provider_median,170,2.428105,2.428105,0,0,0.000000
3,lightgbm,170,1.344043,1.377104,75,91,0.033062
8,xgboost,170,1.326717,1.393122,85,82,0.066404
7,ridge_stack,170,1.300208,1.371846,70,100,0.071638
0,catboost,170,1.343391,1.417672,64,102,0.074281

## V20 Peak-Timing Feature Coverage

In [25]:
v20_feature_columns = [*V20_PEAK_TIMING_RAW_FEATURE_COLUMNS, *V20_ENGINEERED_FEATURE_COLUMNS]
v20_feature_coverage = (
    result.features[v20_feature_columns]
    .notna().mean().mul(100)
    .rename("coverage_pct").reset_index().rename(columns={"index": "feature"})
)
v20_feature_coverage.to_csv(
    config.resolved_output_dir() / f"{STATION_ID}_v20_peak_feature_coverage.csv", index=False
)
v20_feature_coverage.sort_values("coverage_pct")

                                              feature  coverage_pct
5                        nbm_cooling_onset_hour_local     92.083127
30                v20_nbm_observation_adjusted_high_f     98.861950
26                       v20_nbm_t11_minus_observed_f     98.861950
25                      v20_hrrr_t11_minus_observed_f     98.911430
29               v20_hrrr_observation_adjusted_high_f     98.911430
31                           v20_adjusted_high_mean_f     98.911430
32                         v20_adjusted_high_spread_f     98.911430
2                               nbm_hour_of_max_local     99.950520
17               hrrr_precip_wet_hours_11_to_nbm_peak     99.950520
22                    hrrr_tcc_11_to_nbm_peak_max_pct     99.950520
16                hrrr_precip_total_11_to_nbm_peak_mm     99.950520
1                                    nbm_max_post11_f     99.950520
3                                   nbm_slope_11_14_f     99.950520
4                                   nbm_slope_14_17_f     99.950520
13             hrrr_solar_energy_11_to_nbm_peak_wh_m2     99.950520
0                                          nbm_t11l_f     99.950520
28                           v20_nbm_remaining_rise_f     99.950520
24                   hrrr_lcc_11_to_nbm_peak_mean_pct     99.950520
23                  hrrr_blcc_11_to_nbm_peak_mean_pct     99.950520
21                   hrrr_tcc_11_to_nbm_peak_mean_pct     99.950520
40                           v20_rain_before_nbm_peak     99.950520
34                           v20_peak_hour_difference     99.950520
33                        v20_model_high_difference_f     99.950520
15              hrrr_precip_wet_hours_11_to_hrrr_peak    100.000000
6                                         hrrr_t11l_f    100.000000
14               hrrr_precip_total_11_to_hrrr_peak_mm    100.000000
12            hrrr_solar_energy_11_to_hrrr_peak_wh_m2    100.000000
11                            hrrr_slope_14_to_peak_f    100.000000
9                             hrrr_peak_at_window_end    100.000000
10                                 hrrr_slope_11_14_f    100.000000
8                              hrrr_hour_of_max_local    100.000000
7                                   hrrr_max_post11_f    100.000000
27                          v20_hrrr_remaining_rise_f    100.000000
18                               hrrr_no_precip_11_18    100.000000
19                  hrrr_tcc_11_to_hrrr_peak_mean_pct    100.000000
20                   hrrr_tcc_11_to_hrrr_peak_max_pct    100.000000
36                       v20_solar_energy_15_18_wh_m2    100.000000
37                 v20_tcc_change_11_to_hrrr_peak_pct    100.000000
38                  v20_tcc_change_11_to_nbm_peak_pct    100.000000
35                       v20_solar_energy_11_14_wh_m2    100.000000
39                          v20_rain_before_hrrr_peak    100.000000
41                             v20_rain_present_11_18    100.000000
42  v20_precip_onset_minus_hrrr_peak_hours_zero_fi...    100.000000
43  v20_precip_onset_minus_nbm_peak_hours_zero_filled    100.000000

## Fold Metrics and Peak-Feature Importance

In [26]:
fold_metrics = (
    result.validation_predictions.groupby(["fold", "method"], as_index=False)
    .agg(count=("absolute_error_f", "size"), mae_f=("absolute_error_f", "mean"), bias_f=("error_f", "mean"))
)
peak_feature_importance = result.feature_importance.loc[
    result.feature_importance["feature"].isin(v20_feature_columns)
].sort_values(["method", "importance_mean_mae_f"], ascending=[True, False])
fold_metrics.to_csv(config.resolved_output_dir() / f"{STATION_ID}_fold_metrics.csv", index=False)
fold_metrics, peak_feature_importance

(                      fold           method  count     mae_f    bias_f
 0   fold_2021_2022_to_2023         catboost    363  1.526815 -0.625061
 1   fold_2021_2022_to_2023          gfs_raw    363  3.028109 -0.132348
 2   fold_2021_2022_to_2023         hrrr_raw    363  5.080056  4.869236
 3   fold_2021_2022_to_2023         lightgbm    363  1.443462 -0.656240
 4   fold_2021_2022_to_2023          nbm_raw    363  2.039734  0.963740
 5   fold_2021_2022_to_2023    provider_mean    363  2.672864  1.900209
 6   fold_2021_2022_to_2023  provider_median    363  2.277639  1.410090
 7   fold_2021_2022_to_2023          xgboost    363  1.465844 -0.630829
 8   fold_2021_2023_to_2024         catboost    364  1.229084  0.030233
 9   fold_2021_2023_to_2024          gfs_raw    364  2.468857  0.110129
 10  fold_2021_2023_to_2024         hrrr_raw    364  4.475751  4.295993
 11  fold_2021_2023_to_2024         lightgbm    364  1.283255 -0.238633
 12  fold_2021_2023_to_2024          nbm_raw    364  1.880132  1.016588
 13  fold_2021_2023_to_2024    provider_mean    364  2.436153  1.807570
 14  fold_2021_2023_to_2024  provider_median    364  2.037473  1.335194
 15  fold_2021_2023_to_2024          xgboost    364  1.351037 -0.233339
 16  fold_2021_2024_to_2025         catboost    364  1.312091 -0.017354
 17  fold_2021_2024_to_2025          gfs_raw    364  2.820566 -0.746663
 18  fold_2021_2024_to_2025         hrrr_raw    364  4.609335  4.461602
 19  fold_2021_2024_to_2025         lightgbm    364  1.293800 -0.017147
 20  fold_2021_2024_to_2025          nbm_raw    364  1.885549  0.934016
 21  fold_2021_2024_to_2025    provider_mean    364  2.308677  1.549652
 22  fold_2021_2024_to_2025  provider_median    364  2.031523  1.233092
 23  fold_2021_2024_to_2025          xgboost    364  1.336245  0.002271
 24       fold_2021_to_2022         catboost    361  1.560101 -0.027195
 25       fold_2021_to_2022          gfs_raw    361  3.857138  1.936825
 26       fold_2021_to_2022         hrrr_raw    361  5.540105  5.394762
 27       fold_2021_to_2022         lightgbm    361  1.596466 -0.392891
 28       fold_2021_to_2022          nbm_raw    361  2.510377  2.031433
 29       fold_2021_to_2022    provider_mean    361  3.458945  3.121007
 30       fold_2021_to_2022  provider_median    361  3.037298  2.725399
 31       fold_2021_to_2022          xgboost    361  1.626714 -0.480936,
        method param_key                                 feature  \
 8    catboost  trial_20                       nbm_slope_11_14_f
 14   catboost  trial_20                v20_nbm_remaining_rise_f
 28   catboost  trial_20     v20_nbm_observation_adjusted_high_f
 39   catboost  trial_20     hrrr_precip_total_11_to_nbm_peak_mm
 40   catboost  trial_20  hrrr_solar_energy_11_to_nbm_peak_wh_m2
 ..        ...       ...                                     ...
 187   xgboost  trial_26                    hrrr_no_precip_11_18
 189   xgboost  trial_26                              nbm_t11l_f
 191   xgboost  trial_26                  v20_rain_present_11_18
 192   xgboost  trial_26        hrrr_tcc_11_to_nbm_peak_mean_pct
 215   xgboost  trial_26     v20_nbm_observation_adjusted_high_f

      importance_mean_mae_f  importance_std_mae_f  n_repeats  train_start_year  \
 8                 0.183982              0.033778         10              2021
 14                0.078877              0.028766         10              2021
 28                0.032870              0.024111         10              2021
 39                0.020432              0.006712         10              2021
 40                0.018998              0.006438         10              2021
 ..                     ...                   ...        ...               ...
 187              -0.000220              0.002042         10              2021
 189              -0.000237              0.001218         10              2021
 191              -0.000247              0.000517         10              2021
 192              -0.000355              0.005578         10              2021
 215              -0.002643              0.005468         10              2021

      train_end_year  test_year  train_rows  test_rows
 8              2025       2026        1811        170
 14             2025       2026        1811        170
 28             2025       2026        1811        170
 39             2025       2026        1811        170
 40             2025       2026        1811        170
 ..              ...        ...         ...        ...
 187            2025       2026        1811        170
 189            2025       2026        1811        170
 191            2025       2026        1811        170
 192            2025       2026        1811        170
 215            2025       2026        1811        170

 [81 rows x 11 columns])

## Calibrated Common-Date Comparison with KDAL V11 Settlement Fix

In [27]:
v11_fix_path = (
    PROJECT_ROOT / "data" / "calibration" / "station_stacking_v11_settlement_fix"
    / f"{STATION_ID}_year_split_test_predictions.csv"
)
v11_fix = pd.read_csv(v11_fix_path)
v11_fix = v11_fix.loc[v11_fix["method"].eq("ridge_stack")].copy()
v11_fix["contract_date"] = v11_fix["contract_date"].astype(str).str[:10]
candidate = calibrated_predictions.copy()
candidate["contract_date"] = candidate["contract_date"].astype(str).str[:10]
common = candidate.merge(v11_fix, on="contract_date", suffixes=("_candidate", "_v11_fix"))
common["candidate_absolute_error_f"] = (
    pd.to_numeric(common["actual_high_f_candidate"], errors="coerce")
    - pd.to_numeric(common["predicted_high_f_candidate"], errors="coerce")
).abs()
common["v11_fix_absolute_error_f"] = (
    pd.to_numeric(common["actual_high_f_v11_fix"], errors="coerce")
    - pd.to_numeric(common["predicted_high_f_v11_fix"], errors="coerce")
).abs()
common_date_comparison = pd.DataFrame([
    {
        "common_date_count": len(common),
        "candidate_mae_f": common["candidate_absolute_error_f"].mean(),
        "v11_fix_mae_f": common["v11_fix_absolute_error_f"].mean(),
        "delta_mae_f": common["candidate_absolute_error_f"].mean() - common["v11_fix_absolute_error_f"].mean(),
        "candidate_better_days": int((common["candidate_absolute_error_f"] < common["v11_fix_absolute_error_f"]).sum()),
        "v11_fix_better_days": int((common["candidate_absolute_error_f"] > common["v11_fix_absolute_error_f"]).sum()),
    }
])
common_date_comparison.to_csv(
    config.resolved_output_dir() / f"{STATION_ID}_calibrated_v11_fix_common_date_comparison.csv", index=False
)
common_date_comparison

,common_date_count,candidate_mae_f,v11_fix_mae_f,delta_mae_f,candidate_better_days,v11_fix_better_days
0,170,1.358732,1.300208,0.058524,69,101